<script lang="ts" setup>
definePageMeta({
  title: 'newRequest',
});

// --- Types ---
type FieldValue = {
  fieldId: number;
  value: string;
};

type SigningStep = {
  id: string;
  order: number;
  roleId?: number;
  roleName: string;
  assignedUserId?: string;
  color?: string;
};

type UserOption = {
  id: string;
  fullNameEn: string;
  fullNameTh: string;
  email: string;
};

type TemplateData = {
  id: number;
  name: string;
  documentUrl: string | null;
  placedFieldsData: any[] | null;
  signingFlowData: SigningStep[] | null;
};

// Staged file for new-request mode (client-side only, not yet uploaded)
type PendingAttachment = {
  id: string;
  file: File;
  localUrl: string;
  name: string;
  size: number;
};

// --- State ---
const route = useRoute();
const templateId = Number(route.params.templateId);
const isLoading = ref(true);
const isSaving = ref(false);
const error = ref<string | null>(null);
const successMessage = ref('');

const templateData = ref<TemplateData | null>(null);
const pdfFile = ref<File | null>(null);
const previewPdfFile = ref<File | null>(null);
const placedFields = ref<any[]>([]);
const fieldValues = ref<Record<number, string>>({});
const previewSyncedFieldValues = ref<Record<number, string>>({});
const scale = ref(1);
const isRefreshingPreview = ref(false);

const pendingAttachments = ref<PendingAttachment[]>([]);
const isUploadingAttachment = ref(false);
const fileInputRef = ref<HTMLInputElement | null>(null);

let previewRefreshTimer: ReturnType<typeof setTimeout> | null = null;
let previewRequestToken = 0;

// --- Recipient selection ---
const { locale } = useI18n();
const { user } = useUserSession();
const signingSteps = ref<SigningStep[]>([]);
const roleNameToId = ref<Record<string, number>>({}); // roleName -> roleId
const usersByRoleId = ref<Record<number, UserOption[]>>({});
const loadingUsersByRoleId = ref<Record<number, boolean>>({});
const selectedRecipients = ref<Record<string, string>>({}); // stepId -> userId

const recipientSteps = computed(() => {
  const steps = signingSteps.value;
  if (!steps.length)
    return [];
  const currentRoleName = user.value?.currentRole ?? '';
  // Show a UI picker only for steps that are:
  //   • NOT pre-assigned in the template (step.assignedUserId is empty/absent)
  //   • NOT the submitter's own step (roleName ≠ submitter's currentRole)
  // Steps that are pre-assigned (template creator locked a specific person) and
  // steps that belong to the submitter (self-signed by role match on the server)
  // are handled automatically — no user interaction needed.
  return steps.filter(s => !s.assignedUserId && s.roleName !== currentRoleName);
});

const allRecipientsSelected = computed(() =>
  recipientSteps.value.every(step => !!selectedRecipients.value[step.id]),
);

function getResolvedRoleId(step: SigningStep): number | undefined {
  return step.roleId ?? roleNameToId.value[step.roleName];
}

function getUserItems(step: SigningStep) {
  const roleId = getResolvedRoleId(step);
  if (!roleId)
    return [];
  return (usersByRoleId.value[roleId] ?? []).map(u => ({
    label: (locale.value === 'th' && u.fullNameTh?.trim()) ? u.fullNameTh.trim() : u.fullNameEn,
    value: u.id,
  }));
}

async function fetchUsersForRecipientSteps() {
  // Resolve any missing roleIds via roleName lookup
  const needsLookup = recipientSteps.value.filter(s => !s.roleId && !roleNameToId.value[s.roleName]);
  if (needsLookup.length > 0) {
    type RoleRecord = { id: number; name: string };
    const allRoles = await $fetch<RoleRecord[]>('/api/roles');
    allRoles.forEach((r) => {
      roleNameToId.value[r.name] = r.id;
    });
  }

  await Promise.all(
    recipientSteps.value.map(async (step) => {
      const roleId = getResolvedRoleId(step);
      if (!roleId || usersByRoleId.value[roleId])
        return;
      loadingUsersByRoleId.value[roleId] = true;
      try {
        const data = await $fetch<UserOption[]>(`/api/users/by-role/${roleId}`);
        usersByRoleId.value[roleId] = data;
      }
      catch (err) {
        console.error(`Failed to fetch users for role ${roleId}:`, err);
        usersByRoleId.value[roleId] = [];
      }
      finally {
        loadingUsersByRoleId.value[roleId] = false;
      }
    }),
  );
}

// --- Methods ---
async function urlToFile(url: string, filename: string) {
  try {
    const response = await fetch(url);
    const blob = await response.blob();
    return new File([blob], filename, { type: blob.type });
  }
  catch (err) {
    console.error('Error converting URL to File:', err);
    throw err;
  }
}

function normalizeFieldValue(value: unknown): string {
  return String(value ?? '').trim();
}

function getFieldType(field: any): string {
  return String(field?.type || field?.fieldType || '').toLowerCase();
}

function isAutoGeneratedField(field: any): boolean {
  const fieldType = getFieldType(field);
  if (fieldType === 'time') {
    return true;
  }

  return field?.isAutoGenerate === true || field?.isAutoGenerated === true || field?.is_auto_generated === true;
}

function isAutoGeneratedDateOrTimeField(field: any): boolean {
  const fieldType = getFieldType(field);
  return isAutoGeneratedField(field) && (fieldType === 'date' || fieldType === 'time');
}

function getCurrentDateValue(): string {
  return new Intl.DateTimeFormat('en-GB', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
    timeZone: 'Asia/Bangkok',
  }).format(new Date());
}

function getCurrentTimeValue(): string {
  return new Intl.DateTimeFormat('en-GB', {
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
    timeZone: 'Asia/Bangkok',
  }).format(new Date());
}

function resolveAutoGeneratedValue(field: any): string {
  if (!isAutoGeneratedDateOrTimeField(field)) {
    return '';
  }

  const fieldType = getFieldType(field);
  return fieldType === 'time' ? getCurrentTimeValue() : getCurrentDateValue();
}

function applyAutoGeneratedFieldValues(): void {
  for (const field of placedFields.value) {
    if (!isAutoGeneratedDateOrTimeField(field)) {
      continue;
    }

    const fieldId = Number.parseInt(String(field.id ?? ''), 10);
    if (!Number.isFinite(fieldId)) {
      continue;
    }

    const existingValue = normalizeFieldValue(fieldValues.value[fieldId]);
    if (existingValue.length > 0) {
      continue;
    }

    fieldValues.value[fieldId] = resolveAutoGeneratedValue(field);
  }
}

function clearPreviewRefreshTimer() {
  if (previewRefreshTimer) {
    clearTimeout(previewRefreshTimer);
    previewRefreshTimer = null;
  }
}

const previewDisplayFile = computed(() => previewPdfFile.value || pdfFile.value);

const previewOverlayFields = computed(() => {
  return placedFields.value.filter((field: any) => {
    const currentValue = normalizeFieldValue(fieldValues.value[field.id]);
    const syncedValue = normalizeFieldValue(previewSyncedFieldValues.value[field.id]);
    return currentValue.length === 0 || currentValue !== syncedValue;
  });
});

const previewOverlayFieldValues = computed<Record<number, string>>(() => {
  const values: Record<number, string> = {};

  for (const field of previewOverlayFields.value) {
    const currentValue = fieldValues.value[field.id] || '';
    const normalizedCurrent = normalizeFieldValue(currentValue);
    const normalizedSynced = normalizeFieldValue(previewSyncedFieldValues.value[field.id]);

    if (normalizedCurrent.length > 0 && normalizedCurrent !== normalizedSynced) {
      values[field.id] = currentValue;
    }
  }

  return values;
});

async function refreshPreviewPdf() {
  if (!pdfFile.value) {
    previewPdfFile.value = null;
    previewSyncedFieldValues.value = {};
    return;
  }

  applyAutoGeneratedFieldValues();

  const requestToken = ++previewRequestToken;
  const fieldValueSnapshot = Object.fromEntries(
    placedFields.value.map((field: any) => [field.id, fieldValues.value[field.id] || '']),
  );

  const formData = new FormData();
  formData.append('pdfFile', pdfFile.value, pdfFile.value.name);
  formData.append('fields', JSON.stringify(
    placedFields.value.map((field: any) => ({
      ...field,
      sampleValue: fieldValueSnapshot[field.id] || '',
      useFallbackLabel: false,
      showFieldHighlight: false,
    })),
  ));

  isRefreshingPreview.value = true;

  try {
    const response = await fetch('/api/preview-template-pdf', {
      method: 'POST',
      body: formData,
    });

    if (!response.ok) {
      throw new Error(`Preview request failed with status ${response.status}`);
    }

    const previewBytes = await response.arrayBuffer();

    if (requestToken !== previewRequestToken) {
      return;
    }

    previewPdfFile.value = new File([
      previewBytes,
    ], `template-preview-${templateId}.pdf`, { type: 'application/pdf' });
    previewSyncedFieldValues.value = fieldValueSnapshot;
  }
  catch (err) {
    console.error('Failed to refresh preview PDF:', err);
  }
  finally {
    if (requestToken === previewRequestToken) {
      isRefreshingPreview.value = false;
    }
  }
}

function schedulePreviewRefresh() {
  clearPreviewRefreshTimer();

  if (!pdfFile.value) {
    previewPdfFile.value = null;
    previewSyncedFieldValues.value = {};
    return;
  }

  previewRefreshTimer = setTimeout(() => {
    void refreshPreviewPdf();
  }, 1000);
}

async function fetchTemplateData() {
  isLoading.value = true;
  error.value = null;

  try {
    if (!templateId || Number.isNaN(templateId)) {
      error.value = 'No template selected';
      return;
    }

    const templateResult: any = await $fetch(`/api/pdf-templates/${templateId}`);

    if (templateResult.success && templateResult.data) {
      templateData.value = templateResult.data as TemplateData;

      if (templateData.value?.documentUrl) {
        const filename = templateData.value.documentUrl.split('/').pop() || 'template.pdf';
        pdfFile.value = await urlToFile(templateData.value.documentUrl, filename);
      }

      if (templateData.value?.signingFlowData) {
        signingSteps.value = templateData.value.signingFlowData;
        // fetchUsersForRecipientSteps is triggered via watcher on recipientSteps
      }

      if (templateData.value?.placedFieldsData) {
        // Show only the student's own fields (matched by signerStepId) or unassigned fields
        const currentRoleName = user.value?.currentRole ?? '';
        const studentStep = signingSteps.value.find(s => s.roleName === currentRoleName);
        const studentStepId = studentStep?.id ?? null;

        placedFields.value = (templateData.value.placedFieldsData as any[]).filter(
          (field: any) => {
            if (field.isFillable === false || field.is_fillable === false)
              return false;
            if (field.type === 'Signature')
              return false;
            if (studentStepId) {
              const stepId = field.signerStepId ?? field.signer_step_id ?? null;
              return !stepId || stepId === studentStepId;
            }
            return true;
          },
        );

        applyAutoGeneratedFieldValues();
      }
    }
    else {
      error.value = 'Template not found';
    }
  }
  catch (err: any) {
    console.error('Error fetching template:', err);
    error.value = err?.message || 'Failed to load template';
  }
  finally {
    isLoading.value = false;
  }
}

async function submitRequest() {
  isSaving.value = true;
  error.value = null;

  try {
    applyAutoGeneratedFieldValues();

    // 1. Create the DB record
    const createResult: any = await $fetch('/api/requests', {
      method: 'POST',
      body: {
        templateId,
        status: 'draft',
      },
    });

    if (!createResult.success || !createResult.data) {
      error.value = (createResult.error as string) || 'Failed to create request';
      return;
    }

    const activeRequestId = String(createResult.data.id);

    // 2. Upload staged attachments
    for (const pending of pendingAttachments.value) {
      try {
        const formData = new FormData();
        formData.append('file', pending.file, pending.name);
        await $fetch(`/api/requests/${activeRequestId}/attachments/upload`, {
          method: 'POST',
          body: formData,
        });
      }
      catch (uploadErr) {
        console.error('Failed to upload attachment:', pending.name, uploadErr);
      }
    }

    // 3. Save field values
    const fieldValuesArray: FieldValue[] = Object.entries(fieldValues.value).map(
      ([fieldId, value]) => ({
        fieldId: Number.parseInt(fieldId),
        value: value || '',
      }),
    );

    const saveResult: any = await $fetch(`/api/requests/${activeRequestId}/field-values`, {
      method: 'POST',
      body: { fieldValues: fieldValuesArray },
    });

    if (!saveResult.success) {
      error.value = (saveResult.error as string) || 'Failed to save field values';
      return;
    }

    // 4. Generate filled PDF
    const pdfResult = await $fetch(`/api/requests/${activeRequestId}/generate-filled-pdf`, {
      method: 'POST',
    });

    if (!pdfResult.success) {
      error.value = 'Failed to generate PDF';
      return;
    }

    // 5. Submit: initialize signing flow and update status
    const recipients = recipientSteps.value
      .filter(step => selectedRecipients.value[step.id])
      .map(step => ({ stepId: step.id, userId: selectedRecipients.value[step.id] }));

    const updateResult: any = await $fetch(`/api/requests/${activeRequestId}/submit`, {
      method: 'POST',
      body: { recipients },
    });

    if (updateResult.success) {
      navigateTo('/student/my-requests');
    }
    else {
      error.value = (updateResult.error as string) || 'Failed to submit request';
    }
  }
  catch (err: any) {
    console.error('Error submitting request:', err);
    error.value = err?.message || 'Failed to submit request';
  }
  finally {
    isSaving.value = false;
  }
}

const fillableFields = computed(() => {
  return placedFields.value.filter(
    (field: any) =>
      field.isFillable !== false
      && field.is_fillable !== false
      && field.type !== 'Signature'
      && !isAutoGeneratedField(field),
  );
});

function triggerFileUpload() {
  fileInputRef.value?.click();
}

async function handleFileUpload(event: Event) {
  const target = event.target as HTMLInputElement;
  const file = target.files?.[0];

  if (!file)
    return;

  const maxSize = 30 * 1024 * 1024; // 30MB
  if (file.size > maxSize) {
    error.value = 'File size must be less than 30MB';
    if (target)
      target.value = '';
    return;
  }

  pendingAttachments.value.push({
    id: crypto.randomUUID(),
    file,
    localUrl: URL.createObjectURL(file),
    name: file.name,
    size: file.size,
  });

  if (target)
    target.value = '';
}

function removePendingAttachment(id: string) {
  const idx = pendingAttachments.value.findIndex(a => a.id === id);
  if (idx !== -1) {
    const attachment = pendingAttachments.value[idx];
    if (attachment)
      URL.revokeObjectURL(attachment.localUrl);
    pendingAttachments.value.splice(idx, 1);
  }
}

function formatFileSize(bytes: number): string {
  if (bytes < 1024)
    return `${bytes} B`;
  if (bytes < 1024 * 1024)
    return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function getFileIcon(fileName: string | null) {
  if (!fileName)
    return 'i-heroicons-document';
  const ext = fileName.split('.').pop()?.toLowerCase();
  switch (ext) {
    case 'pdf': return 'i-heroicons-document-text';
    case 'jpg':
    case 'jpeg':
    case 'png':
    case 'gif': return 'i-heroicons-photo';
    case 'doc':
    case 'docx': return 'i-heroicons-document-text';
    case 'xls':
    case 'xlsx': return 'i-heroicons-table-cells';
    case 'zip':
    case 'rar': return 'i-heroicons-archive-box';
    default: return 'i-heroicons-document';
  }
}

onMounted(() => {
  fetchTemplateData();
});

onUnmounted(() => {
  clearPreviewRefreshTimer();
  for (const pending of pendingAttachments.value) {
    URL.revokeObjectURL(pending.localUrl);
  }
});

// Re-fetch users whenever recipientSteps changes (handles session hydration timing)
watch(recipientSteps, (steps) => {
  if (steps.length > 0)
    fetchUsersForRecipientSteps();
}, { immediate: true });

watch([pdfFile, placedFields, fieldValues], () => {
  schedulePreviewRefresh();
}, { deep: true, immediate: true });
</script>

<template>
  <div class="min-h-screen bg-gray-50">
    <!-- Header -->
    <div class="bg-white border-b">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
        <UBreadcrumb
          :links="[
            { label: 'My Requests', to: '/student/my-requests' },
            { label: 'New Request', to: `/student/new-requests/${templateId}` },
          ]"
        />
        <div class="mt-4 flex items-center justify-between">
          <div>
            <h1 class="text-2xl font-bold text-gray-900">
              {{ templateData?.name || 'Fill Request Form' }}
            </h1>
            <p class="mt-1 text-sm text-gray-500">
              Complete the form below and submit your request
            </p>
          </div>
        </div>
      </div>
    </div>

    <!-- Main Content -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <!-- Loading State -->
      <div v-if="isLoading" class="flex items-center justify-center h-96">
        <div class="text-center">
          <i class="fas fa-spinner fa-spin text-4xl text-gray-400 mb-4" />
          <p class="text-gray-500">
            Loading template...
          </p>
        </div>
      </div>

      <!-- Error State -->
      <UCard v-else-if="error && !templateData">
        <div class="text-center py-8">
          <i class="fas fa-exclamation-triangle text-4xl text-red-400 mb-4" />
          <p class="text-red-600 mb-4">
            {{ error }}
          </p>
          <UButton @click="$router.push('/student/new-request')">
            Back to Request
          </UButton>
        </div>
      </UCard>

      <!-- Form Content -->
      <div v-else class="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <!-- Left: PDF Preview (Read-only) -->
        <div class="lg:col-span-2">
          <!-- Zoom Controls -->
          <div class="mb-4 flex items-center gap-4 bg-white rounded-lg border border-gray-200 px-4 py-2">
            <span class="text-sm text-gray-600">Zoom:</span>
            <UButton
              icon="i-heroicons-minus"
              size="xs"
              variant="ghost"
              :disabled="scale <= 0.5"
              @click="scale = Math.max(0.5, scale - 0.25)"
            />
            <span class="text-sm font-medium w-12 text-center">{{ Math.round(scale * 100) }}%</span>
            <UButton
              icon="i-heroicons-plus"
              size="xs"
              variant="ghost"
              :disabled="scale >= 3"
              @click="scale = Math.min(3, scale + 0.25)"
            />
            <UButton
              size="xs"
              variant="ghost"
              @click="scale = 1"
            >
              Reset
            </UButton>
          </div>

          <!-- PDF Viewer -->
          <div v-if="previewDisplayFile" style="min-height: 600px;">
            <template-pdf-create
              :pdf-file="previewDisplayFile"
              :placed-fields="previewOverlayFields"
              :selected-field="undefined"
              :ui-scale="scale"
              :read-only="true"
              :fill-mode="true"
              :field-values="previewOverlayFieldValues"
            />
            <div v-if="isRefreshingPreview" class="mt-2 text-xs text-gray-500 text-right">
              Syncing preview...
            </div>
          </div>
        </div>

        <!-- Right: Form Fields -->
        <div class="space-y-6">
          <!-- Success Message -->
          <UCard v-if="successMessage" class="bg-green-50 border-green-200">
            <div class="flex items-center gap-2 text-green-800">
              <i class="fas fa-check-circle" />
              <span class="font-medium">{{ successMessage }}</span>
            </div>
          </UCard>

          <!-- Error Message -->
          <UCard v-if="error" class="bg-red-50 border-red-200">
            <div class="flex items-center gap-2 text-red-800">
              <i class="fas fa-exclamation-circle" />
              <span class="font-medium">{{ error }}</span>
            </div>
          </UCard>

          <!-- Form Fields Card -->
          <UCard>
            <template #header>
              <h3 class="text-sm font-semibold text-gray-500 uppercase">
                Request Information
              </h3>
            </template>

            <div class="space-y-4">
              <div
                v-for="field in fillableFields"
                :key="field.instanceId"
                class="field-group"
              >
                <form-field-input
                  v-model="fieldValues[field.id]"
                  :field="field"
                  :disabled="isSaving"
                />
              </div>

              <div v-if="fillableFields.length === 0" class="text-center py-8 text-gray-500">
                <i class="fas fa-inbox text-3xl mb-2" />
                <p class="text-sm">
                  No fillable fields in this template
                </p>
              </div>
            </div>
          </UCard>

          <!-- Attachments Card -->
          <UCard>
            <template #header>
              <div class="flex items-center justify-between">
                <h3 class="text-sm font-semibold text-gray-500 uppercase">
                  Attachments
                </h3>
                <UButton
                  size="xs"
                  color="primary"
                  icon="i-heroicons-paper-clip"
                  :loading="isUploadingAttachment"
                  @click="triggerFileUpload"
                >
                  Add File
                </UButton>
              </div>
            </template>

            <div class="space-y-3">
              <input
                ref="fileInputRef"
                type="file"
                class="hidden"
                accept="*/*"
                @change="handleFileUpload"
              >

              <div
                v-for="pending in pendingAttachments"
                :key="pending.id"
                class="flex items-center justify-between p-3 bg-blue-50 rounded-lg border border-blue-100"
              >
                <div class="flex items-center gap-3 flex-1 min-w-0">
                  <UIcon
                    :name="getFileIcon(pending.name)"
                    class="w-5 h-5 text-blue-600 shrink-0"
                  />
                  <div class="flex-1 min-w-0">
                    <p class="text-sm font-medium text-gray-900 truncate">
                      {{ pending.name }}
                    </p>
                    <p class="text-xs text-gray-500">
                      {{ formatFileSize(pending.size) }} · Will be uploaded on submit
                    </p>
                  </div>
                </div>
                <UButton
                  size="xs"
                  variant="ghost"
                  color="error"
                  icon="i-heroicons-trash"
                  @click="removePendingAttachment(pending.id)"
                />
              </div>

              <div v-if="pendingAttachments.length === 0" class="text-center py-8 text-gray-500">
                <i class="fas fa-paperclip text-3xl mb-2" />
                <p class="text-sm">
                  No attachments yet
                </p>
                <p class="text-xs mt-1">
                  Files will be uploaded when you submit
                </p>
              </div>
            </div>
          </UCard>

          <!-- Recipient Selection Card -->
          <UCard v-if="recipientSteps.length > 0">
            <template #header>
              <h3 class="text-sm font-semibold text-gray-500 uppercase">
                {{ locale === 'th' ? 'เลือกผู้รับเอกสาร' : 'Select Recipients' }}
              </h3>
            </template>

            <div class="space-y-4">
              <div
                v-for="step in recipientSteps"
                :key="step.id"
              >
                <label class="block text-sm font-medium text-gray-700 mb-1">
                  {{ locale === 'th' ? `ผู้รับลำดับที่ ${step.order}` : `Recipient for step ${step.order}` }}
                  <span class="ml-1 text-xs text-gray-500">({{ step.roleName }})</span>
                  <span class="ml-1 text-red-500">*</span>
                </label>
                <USelectMenu
                  v-model="selectedRecipients[step.id]"
                  :items="getUserItems(step)"
                  value-key="value"
                  label-key="label"
                  :placeholder="loadingUsersByRoleId[getResolvedRoleId(step) ?? 0] ? (locale === 'th' ? 'กำลังโหลด...' : 'Loading...') : (locale === 'th' ? 'เลือกผู้รับ...' : 'Select recipient...')"
                  :disabled="isSaving || !!loadingUsersByRoleId[getResolvedRoleId(step) ?? 0]"
                  :loading="!!loadingUsersByRoleId[getResolvedRoleId(step) ?? 0]"
                  :search-input="{ placeholder: locale === 'th' ? 'ค้นหา...' : 'Search...' }"
                  icon="i-heroicons-user"
                  class="w-full"
                />
                <p
                  v-if="!getUserItems(step).length && !loadingUsersByRoleId[getResolvedRoleId(step) ?? 0]"
                  class="mt-1 text-xs text-gray-400"
                >
                  {{ locale === 'th' ? 'ไม่พบผู้ใช้ที่มีบทบาทนี้' : 'No users found with this role' }}
                </p>
              </div>
            </div>
          </UCard>

          <!-- Action Buttons -->
          <div class="flex flex-col gap-3">
            <UButton
              block
              color="success"
              size="lg"
              :loading="isSaving"
              :disabled="!allRecipientsSelected || isSaving"
              @click="submitRequest"
            >
              <i class="fas fa-paper-plane mr-2" />
              Submit Request
            </UButton>

            <UButton
              block
              variant="ghost"
              color="neutral"
              @click="$router.push('/student/new-request')"
            >
              <i class="fas fa-arrow-left mr-2" />
              Back to Request
            </UButton>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.field-group {
  padding: 0.5rem 0;
  border-bottom: 1px solid #f3f4f6;
}

.field-group:last-child {
  border-bottom: none;
}
</style>
