<script setup lang="ts">
import { LazyBaseConfirmDialogWithReason } from '#components';
import { resolveAutoGeneratedDateTimeValue } from '~~/shared/auto-date-time-format';
import { isFormFieldRequired } from '~~/shared/form-field-required';
import { validateVisibleRequiredStudentFields } from '~~/shared/student-visible-required-validation';

definePageMeta({
  title: 'signerSignDetail.title',
  middleware: ['permission'],
  permission: 'request.sign',
});

type FlowStep = {
  id: number;
  requestId: number;
  stepId: string;
  stepOrder: number;
  roleId: number;
  roleName: string;
  roleNameTh: string;
  assignedFieldInstanceIds: string[];
  status: string;
  signedBy: string | null;
  signedAt: string | null;
  acknowledgeOnly?: boolean;
};

type SignatureField = {
  instanceId: string;
  pageNumber: number;
  normalizedX?: number;
  normalizedY?: number;
  normalizedWidth?: number;
  normalizedHeight?: number;
  x?: number;
  y?: number;
  width?: number;
  height?: number;
};

type Attachment = {
  id: number;
  requestId: number;
  fileName: string | null;
  fileUrl: string | null;
  createdAt: string;
};

type SavedUserSignature = {
  id: number;
  dataUrl: string;
  createdAt: string;
  updatedAt: string;
};

type SigningStatus = {
  requestId: number;
  status: string;
  filledDocumentUrl: string | null;
  templateName: string | null;
  note: string | null;
  flowSteps: FlowStep[];
  pendingStep: FlowStep | null;
  pendingStepsForCurrentUser?: FlowStep[];
  acknowledgeStepsForCurrentUser?: FlowStep[];
  activeStageOrder?: number | null;
  signatureFields: SignatureField[];
  documentWidth?: number;
  documentHeight?: number;
};

type VisibilityRule = {
  enabled?: boolean;
  sourceFieldInstanceId?: string | null;
  sourceGroupId?: string | null;
  operator?: 'isChecked' | 'isUnchecked';
};

type RejectMode = 'status_only' | 'with_signature_and_field';

const route = useRoute();
const router = useRouter();
const requestId = Number(route.params.id);
const { t, locale } = useI18n();

const overlay = useOverlay();
const toast = useToast();
const confirmDialogWithReason = overlay.create(LazyBaseConfirmDialogWithReason);

const isLoading = ref(true);
const isSigning = ref(false);
const isRejecting = ref(false);
const error = ref<string | null>(null);
const successMessage = ref('');

const signingStatus = ref<SigningStatus | null>(null);
const signatureDataUrl = ref<string | null>(null);
const signatureSource = ref<'none' | 'saved' | 'drawn'>('none');
const savedUserSignature = ref<SavedUserSignature | null>(null);
const selectedSavedSignatureId = ref<number | null>(null);
const isLoadingSavedSignature = ref(false);
const isSavingSignature = ref(false);
const showSignaturePopup = ref(false);
const showSignatureSubmitError = ref(false);
const showRequiredFieldErrors = ref(false);
const attachments = ref<Attachment[]>([]);
const previewAttachment = ref<Attachment | null>(null);
const isPreviewOpen = ref(false);

const templatePlacedFields = ref<any[]>([]);
const fieldValues = ref<Record<string, string>>({});
const previewPdfFile = ref<File | null>(null);
const previewPdfBlobUrl = ref<string | null>(null);
const isRefreshingPreview = ref(false);

let previewRefreshTimer: ReturnType<typeof setTimeout> | null = null;
let previewRequestToken = 0;

function openPreview(att: Attachment) {
  previewAttachment.value = att;
  isPreviewOpen.value = true;
}

function closePreview() {
  isPreviewOpen.value = false;
  previewAttachment.value = null;
}

function getFieldType(field: any): string {
  return String(field?.type || field?.fieldType || '').toLowerCase();
}

function isCheckboxField(field: any): boolean {
  const fieldType = getFieldType(field);
  const fieldName = String(field?.name || '').trim().toLowerCase();
  return fieldType === 'checkbox' || fieldName === 'check mark';
}

function isAutoGeneratedField(field: any): boolean {
  return Boolean(field?.isAutoGenerated ?? field?.isAutoGenerate ?? field?.is_auto_generated ?? false);
}

function normalizeCheckboxValue(value: unknown): string {
  const normalized = String(value ?? '').trim().toLowerCase();
  return ['true', '1', 'yes', 'y', 'checked', 'on'].includes(normalized) ? 'true' : '';
}

function getFieldValueKey(field: any): string {
  const instanceKey = String(field?.instanceId ?? '').trim();
  if (instanceKey.length > 0)
    return instanceKey;
  const fieldId = Number.parseInt(String(field?.id ?? ''), 10);
  return Number.isFinite(fieldId) ? String(fieldId) : '';
}

function getVisibilityRule(field: any): VisibilityRule | null {
  const rawRule = field?.visibilityRule ?? field?.visibility_rule;
  if (!rawRule || typeof rawRule !== 'object')
    return null;
  const sourceFieldInstanceId = String(rawRule.sourceFieldInstanceId ?? rawRule.source_field_instance_id ?? '').trim();
  const sourceGroupId = String(rawRule.sourceGroupId ?? rawRule.source_group_id ?? '').trim();
  if (!sourceFieldInstanceId.length && !sourceGroupId.length)
    return null;
  return {
    enabled: rawRule.enabled !== false,
    sourceFieldInstanceId: sourceFieldInstanceId || null,
    sourceGroupId: sourceGroupId || null,
    operator: rawRule.operator === 'isUnchecked' ? 'isUnchecked' : 'isChecked',
  };
}

function resolveCurrentFieldValue(field: any): string {
  if (isAutoGeneratedField(field))
    return resolveAutoGeneratedDateTimeValue(field);
  const valueKey = getFieldValueKey(field);
  const value = valueKey ? (fieldValues.value[valueKey] || '') : '';
  return isCheckboxField(field) ? normalizeCheckboxValue(value) : value;
}

function getCheckboxGroupId(field: any): string {
  return String(field?.groupId ?? '').trim();
}

function isFieldVisible(field: any): boolean {
  const rule = getVisibilityRule(field);
  if (!rule || rule.enabled === false)
    return true;

  let isChecked = false;
  if (rule.sourceGroupId) {
    const groupFields = templatePlacedFields.value.filter((candidate) => {
      return isCheckboxField(candidate) && getCheckboxGroupId(candidate) === rule.sourceGroupId;
    });
    isChecked = groupFields.some(candidate => normalizeCheckboxValue(resolveCurrentFieldValue(candidate)) === 'true');
  }
  else {
    const sourceField = templatePlacedFields.value.find(
      candidate => String(candidate?.instanceId ?? '').trim() === String(rule.sourceFieldInstanceId ?? ''),
    );
    if (!sourceField)
      return true;
    const sourceValue = normalizeCheckboxValue(resolveCurrentFieldValue(sourceField));
    isChecked = sourceValue === 'true';
  }

  return rule.operator === 'isUnchecked' ? !isChecked : isChecked;
}

const approvalStepsForCurrentUser = computed<FlowStep[]>(() => {
  return signingStatus.value?.pendingStepsForCurrentUser
    ?? (signingStatus.value?.pendingStep ? [signingStatus.value.pendingStep] : []);
});

const acknowledgeStepsForCurrentUser = computed<FlowStep[]>(() =>
  signingStatus.value?.acknowledgeStepsForCurrentUser ?? [],
);

const isAcknowledgeMode = computed(() =>
  approvalStepsForCurrentUser.value.length === 0 && acknowledgeStepsForCurrentUser.value.length > 0,
);

const currentPendingSteps = computed<FlowStep[]>(() =>
  isAcknowledgeMode.value ? acknowledgeStepsForCurrentUser.value : approvalStepsForCurrentUser.value,
);

const hasCurrentPendingSteps = computed(() => currentPendingSteps.value.length > 0);

const signerFillableFields = computed(() => {
  const pendingSteps = currentPendingSteps.value;
  if (!pendingSteps.length || !templatePlacedFields.value.length)
    return [];

  const assignedIds = new Set(pendingSteps.flatMap(step => step.assignedFieldInstanceIds ?? []));

  return templatePlacedFields.value.filter((field: any) => {
    if (field.isFillable === false || field.is_fillable === false)
      return false;
    if (getFieldType(field) === 'signature')
      return false;
    if (isAutoGeneratedField(field))
      return assignedIds.has(field.instanceId);
    return assignedIds.has(field.instanceId);
  });
});

const visibleSignerFillableFields = computed(() =>
  signerFillableFields.value.filter(field => isFieldVisible(field)),
);

const visibleSignerInputFields = computed(() =>
  visibleSignerFillableFields.value.filter(field => !isAutoGeneratedField(field)),
);

const hasSignerInputFields = computed(() => visibleSignerInputFields.value.length > 0);

const hasSignerProcessableFields = computed(() => visibleSignerFillableFields.value.length > 0);

const hasAnyEnteredSignerInputValue = computed(() => {
  return visibleSignerInputFields.value.some((field) => {
    const value = resolveCurrentFieldValue(field);
    return normalizeFieldValue(value).length > 0;
  });
});

const canShowRejectWithFieldButton = computed(() => {
  const hasConfirmedSignatureValue = String(signatureDataUrl.value ?? '').length > 0;
  return hasAnyEnteredSignerInputValue.value || hasConfirmedSignatureValue;
});

function normalizeFieldValue(value: unknown): string {
  return String(value ?? '').trim();
}

function validateRequiredSignerFields(): string | null {
  return validateVisibleRequiredStudentFields(visibleSignerInputFields.value, resolveCurrentFieldValue);
}

function getInvalidRequiredFieldKeys(): Set<string> {
  const invalidKeys = new Set<string>();
  const validatedCheckboxGroups = new Set<string>();
  const visibleFields = visibleSignerInputFields.value;

  for (const field of visibleFields) {
    if (!isFormFieldRequired(field)) {
      continue;
    }

    if (isCheckboxField(field)) {
      const groupId = getCheckboxGroupId(field);
      if (groupId.length > 0) {
        if (validatedCheckboxGroups.has(groupId)) {
          continue;
        }
        validatedCheckboxGroups.add(groupId);
        const groupFields = visibleFields.filter(candidate => isCheckboxField(candidate) && getCheckboxGroupId(candidate) === groupId);
        const anyChecked = groupFields.some(candidate => normalizeCheckboxValue(resolveCurrentFieldValue(candidate)) === 'true');
        if (!anyChecked) {
          for (const candidate of groupFields) {
            const key = getFieldValueKey(candidate);
            if (key) {
              invalidKeys.add(key);
            }
          }
        }
        continue;
      }

      if (normalizeCheckboxValue(resolveCurrentFieldValue(field)) !== 'true') {
        const key = getFieldValueKey(field);
        if (key) {
          invalidKeys.add(key);
        }
      }
      continue;
    }

    if (!normalizeFieldValue(resolveCurrentFieldValue(field)).length) {
      const key = getFieldValueKey(field);
      if (key) {
        invalidKeys.add(key);
      }
    }
  }

  return invalidKeys;
}

const invalidRequiredFieldKeys = computed(() =>
  showRequiredFieldErrors.value ? getInvalidRequiredFieldKeys() : new Set<string>(),
);

function hasFieldValidationError(field: any): boolean {
  const key = getFieldValueKey(field);
  return Boolean(key) && invalidRequiredFieldKeys.value.has(key);
}

function getFieldValidationMessage(field: any): string {
  return isCheckboxField(field)
    ? t('signerSignDetail.validation.checkboxRequired')
    : t('signerSignDetail.validation.fieldRequired');
}

function getFieldContainerId(field: any): string {
  const key = getFieldValueKey(field);
  return key ? `required-field-${encodeURIComponent(key)}` : '';
}

function getFirstInvalidFieldKey(): string | null {
  for (const field of visibleSignerInputFields.value) {
    const key = getFieldValueKey(field);
    if (key && invalidRequiredFieldKeys.value.has(key)) {
      return key;
    }
  }
  return null;
}

async function scrollToFirstInvalidField() {
  const firstInvalidKey = getFirstInvalidFieldKey();
  if (!firstInvalidKey) {
    return;
  }

  await nextTick();
  const targetId = `required-field-${encodeURIComponent(firstInvalidKey)}`;
  const targetEl = document.getElementById(targetId);
  if (!targetEl) {
    return;
  }

  targetEl.scrollIntoView({ behavior: 'smooth', block: 'center' });
}

function handleSignerFieldValueUpdate(field: any, value: string) {
  const key = getFieldValueKey(field);
  if (!key)
    return;

  if (!isCheckboxField(field)) {
    fieldValues.value = { ...fieldValues.value, [key]: value };
    return;
  }

  const normalizedNextValue = normalizeCheckboxValue(value);
  const groupId = getCheckboxGroupId(field);
  const nextValues = { ...fieldValues.value, [key]: normalizedNextValue };

  if (groupId.length > 0 && normalizedNextValue === 'true') {
    for (const candidate of templatePlacedFields.value) {
      if (!isCheckboxField(candidate) || getCheckboxGroupId(candidate) !== groupId) {
        continue;
      }
      const candidateKey = getFieldValueKey(candidate);
      if (!candidateKey || candidateKey === key) {
        continue;
      }
      nextValues[candidateKey] = '';
    }
  }

  fieldValues.value = nextValues;
}

function isCheckboxTemporarilyDisabled(field: any): boolean {
  if (!isCheckboxField(field)) {
    return false;
  }

  const groupId = getCheckboxGroupId(field);
  if (!groupId.length) {
    return false;
  }

  const isCurrentChecked = normalizeCheckboxValue(resolveCurrentFieldValue(field)) === 'true';
  if (isCurrentChecked) {
    return false;
  }

  return templatePlacedFields.value.some((candidate) => {
    if (!isCheckboxField(candidate) || getCheckboxGroupId(candidate) !== groupId) {
      return false;
    }
    return normalizeCheckboxValue(resolveCurrentFieldValue(candidate)) === 'true';
  });
}

function clearPreviewTimer() {
  if (previewRefreshTimer) {
    clearTimeout(previewRefreshTimer);
    previewRefreshTimer = null;
  }
}

async function refreshPreviewPdf() {
  const baseUrl = signingStatus.value?.filledDocumentUrl;
  if (!baseUrl || !hasSignerProcessableFields.value) {
    previewPdfFile.value = null;
    return;
  }

  const requestToken = ++previewRequestToken;
  const fieldValueSnapshot = Object.fromEntries(
    visibleSignerFillableFields.value.map(field => [getFieldValueKey(field), resolveCurrentFieldValue(field)]),
  );

  isRefreshingPreview.value = true;
  try {
    const pdfResponse = await fetch(baseUrl);
    if (!pdfResponse.ok)
      throw new Error('Failed to fetch base PDF');
    const pdfBlob = await pdfResponse.blob();
    const pdfFile = new File([pdfBlob], 'base.pdf', { type: 'application/pdf' });

    const formData = new FormData();
    formData.append('pdfFile', pdfFile, 'base.pdf');
    formData.append('fields', JSON.stringify(
      visibleSignerFillableFields.value.map((field: any) => ({
        ...field,
        sampleValue: fieldValueSnapshot[getFieldValueKey(field)] || '',
        useFallbackLabel: false,
        showFieldHighlight: false,
      })),
    ));

    const response = await fetch('/api/preview-template-pdf', {
      method: 'POST',
      body: formData,
    });

    if (!response.ok)
      throw new Error('Preview generation failed');
    if (requestToken !== previewRequestToken)
      return;

    const previewBytes = await response.arrayBuffer();
    previewPdfFile.value = new File([previewBytes], `preview-${requestId}.pdf`, { type: 'application/pdf' });
  }
  catch (err) {
    console.error('Failed to refresh preview PDF:', err);
  }
  finally {
    if (requestToken === previewRequestToken)
      isRefreshingPreview.value = false;
  }
}

function schedulePreviewRefresh() {
  clearPreviewTimer();
  if (!hasSignerProcessableFields.value || !signingStatus.value?.filledDocumentUrl)
    return;
  previewRefreshTimer = setTimeout(() => {
    void refreshPreviewPdf();
  }, 800);
}

watch(previewPdfFile, (file) => {
  if (previewPdfBlobUrl.value) {
    URL.revokeObjectURL(previewPdfBlobUrl.value);
    previewPdfBlobUrl.value = null;
  }
  if (file)
    previewPdfBlobUrl.value = URL.createObjectURL(file);
});

const displayPdfUrl = computed(() => {
  return previewPdfBlobUrl.value ?? signingStatus.value?.filledDocumentUrl ?? null;
});

async function fetchTemplateData(templateId: number) {
  try {
    const result = await $fetch<{ success: boolean; data: any }>(`/api/pdf-templates/${templateId}`);
    if (result.success && result.data?.placedFieldsData) {
      templatePlacedFields.value = (result.data.placedFieldsData as any[]).filter(
        (f: any) => f.isFillable !== false && f.is_fillable !== false,
      );
    }
  }
  catch (err) {
    console.error('Failed to fetch template:', err);
  }
}

async function saveSignerFieldValues(): Promise<boolean> {
  if (!hasSignerProcessableFields.value)
    return true;

  const fieldValuesArray = visibleSignerFillableFields.value
    .map((field) => {
      const fieldId = Number.parseInt(String(field?.id ?? ''), 10);
      if (!Number.isFinite(fieldId))
        return null;
      const instanceId = String(field?.instanceId ?? '').trim();
      return { fieldId, instanceId: instanceId || undefined, value: resolveCurrentFieldValue(field) || '' };
    })
    .filter(Boolean) as Array<{ fieldId: number; instanceId?: string; value: string }>;

  if (!fieldValuesArray.length)
    return true;

  try {
    const result = await $fetch<{ success: boolean; error?: string }>(
      `/api/requests/${requestId}/field-values`,
      { method: 'POST', body: { fieldValues: fieldValuesArray } },
    );
    if (!result.success) {
      error.value = result.error ?? t('signerSignDetail.errors.saveFieldValuesFailed');
      return false;
    }
    return true;
  }
  catch (err: any) {
    error.value = err?.message ?? t('signerSignDetail.errors.saveFieldValuesError');
    return false;
  }
}

// Compute aspect ratio (width / height) of the pending signature field so the canvas
// matches the actual field box defined in the PDF template.
const pendingSignatureField = computed<SignatureField | undefined>(() => {
  const status = signingStatus.value;
  const pendingSteps = currentPendingSteps.value;
  if (!pendingSteps.length)
    return undefined;
  const assignedIds = pendingSteps.flatMap(step => step.assignedFieldInstanceIds ?? []);
  return status?.signatureFields.find(f => assignedIds.includes(f.instanceId))
    ?? status?.signatureFields[0];
});

const signatureFieldAspectRatio = computed<number | undefined>(() => {
  const status = signingStatus.value;
  const field = pendingSignatureField.value;
  if (!status || !field)
    return undefined;

  const { normalizedWidth: nw, normalizedHeight: nh } = field;
  const docW = status.documentWidth ?? 595;
  const docH = status.documentHeight ?? 842;

  // Prefer normalized dimensions (template-relative), then fall back to absolute values.
  if (nw && nh) {
    return (nw * docW) / (nh * docH);
  }

  if (field.width && field.height) {
    return field.width / field.height;
  }

  return undefined;
});

// Real field width in PDF points — lets the canvas calibrate stroke thickness
// so lines appear identical in the PDF regardless of canvas CSS size.
const signatureFieldWidthPt = computed<number | undefined>(() => {
  const status = signingStatus.value;
  const field = pendingSignatureField.value;
  if (!status || !field)
    return undefined;

  if (field.normalizedWidth) {
    return field.normalizedWidth * (status.documentWidth ?? 595);
  }

  return field.width;
});

const signatureFieldScale = 5.5;

function getPositiveDimension(value: unknown): number | null {
  const parsed = Number(value);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : null;
}

function getSignaturePopupFieldDimensions(
  field: SignatureField | undefined,
  status: SigningStatus | null,
): { width: number | null; height: number | null } {
  if (!field || !status) {
    return { width: null, height: null };
  }

  const documentWidth = getPositiveDimension(status.documentWidth) ?? 595;
  const documentHeight = getPositiveDimension(status.documentHeight) ?? 842;

  const normalizedWidth = getPositiveDimension(field.normalizedWidth);
  const normalizedHeight = getPositiveDimension(field.normalizedHeight);
  if (normalizedWidth !== null && normalizedHeight !== null) {
    return {
      width: Math.round(normalizedWidth * documentWidth * signatureFieldScale),
      height: Math.round(normalizedHeight * documentHeight * signatureFieldScale),
    };
  }

  const displayWidth = getPositiveDimension((field as any).displayWidth);
  const displayHeight = getPositiveDimension((field as any).displayHeight);
  if (displayWidth !== null && displayHeight !== null) {
    return {
      width: Math.round(displayWidth * signatureFieldScale),
      height: Math.round(displayHeight * signatureFieldScale),
    };
  }

  const width = getPositiveDimension(field.width);
  const height = getPositiveDimension(field.height);
  if (width !== null && height !== null) {
    return {
      width: Math.round(width * signatureFieldScale),
      height: Math.round(height * signatureFieldScale),
    };
  }

  return {
    width: null,
    height: null,
  };
}

const signaturePopupStyle = computed(() => {
  const dimensions = getSignaturePopupFieldDimensions(pendingSignatureField.value, signingStatus.value);
  const popupWidth = (dimensions.width ?? 320) + 32;

  return {
    width: `min(calc(100vw - 2rem), ${popupWidth}px)`,
    maxHeight: 'calc(100vh - 2rem)',
  };
});

const signatureFieldBoxStyle = computed(() => {
  const dimensions = getSignaturePopupFieldDimensions(pendingSignatureField.value, signingStatus.value);

  return {
    width: `${dimensions.width ?? 320}px`,
    maxWidth: '100%',
  };
});

function openSignaturePopup() {
  showSignaturePopup.value = true;
  showSignatureSubmitError.value = false;
}

function closeSignaturePopup() {
  showSignaturePopup.value = false;
}

function clearConfirmedSignature() {
  signatureDataUrl.value = null;
  signatureSource.value = 'none';
  selectedSavedSignatureId.value = null;
  showSignatureSubmitError.value = false;
}

async function fetchSavedUserSignature() {
  isLoadingSavedSignature.value = true;
  try {
    const result = await $fetch<{ success: boolean; data: SavedUserSignature | null; error?: string }>(
      '/api/users/signature',
    );
    if (!result.success) {
      throw new Error(result.error ?? t('signerSignDetail.errors.loadSavedSignatureFailed'));
    }
    savedUserSignature.value = result.data ?? null;
  }
  catch (err: any) {
    console.error('Failed to fetch saved signer signature:', err);
  }
  finally {
    isLoadingSavedSignature.value = false;
  }
}

function useSavedSignatureForCurrentSign() {
  if (!savedUserSignature.value)
    return;
  signatureDataUrl.value = savedUserSignature.value.dataUrl;
  signatureSource.value = 'saved';
  selectedSavedSignatureId.value = savedUserSignature.value.id;
  showSignatureSubmitError.value = false;
}

async function saveCurrentSignatureForFuture() {
  if (!signatureDataUrl.value)
    return;

  isSavingSignature.value = true;
  try {
    const result = await $fetch<{ success: boolean; data: SavedUserSignature; error?: string }>(
      '/api/users/signature',
      {
        method: 'PUT',
        body: {
          signatureDataUrl: signatureDataUrl.value,
        },
      },
    );

    if (!result.success) {
      throw new Error(result.error ?? t('signerSignDetail.errors.saveSignatureFailed'));
    }

    savedUserSignature.value = result.data;
    signatureSource.value = 'saved';
    signatureDataUrl.value = result.data.dataUrl;
    selectedSavedSignatureId.value = result.data.id;
    toast.add({
      title: t('signerSignDetail.toast.signatureSavedTitle'),
      description: t('signerSignDetail.toast.signatureSavedDescription'),
      color: 'success',
    });
  }
  catch (err: any) {
    toast.add({
      title: t('signerSignDetail.toast.signatureSaveFailedTitle'),
      description: err?.message ?? t('signerSignDetail.errors.generic'),
      color: 'error',
    });
  }
  finally {
    isSavingSignature.value = false;
  }
}

// Enriches signature fields with the confirmed signature image URL so TemplatePdfPreview can overlay it
const signatureFieldsForDisplay = computed(() => {
  const fields = signingStatus.value?.signatureFields ?? [];
  return fields.map(f => ({
    ...f,
    type: 'Signature',
    ...(signatureDataUrl.value ? { imageUrl: signatureDataUrl.value } : {}),
  }));
});

const currentPendingStep = computed<FlowStep | null>(() => currentPendingSteps.value[0] ?? null);
const hasSignatureField = computed(() => {
  if (!currentPendingSteps.value.length)
    return false;
  const assignedIds = new Set(currentPendingSteps.value.flatMap(step => step.assignedFieldInstanceIds ?? []));
  const sigFields = signingStatus.value?.signatureFields ?? [];
  return sigFields.some(f => assignedIds.has(f.instanceId));
});

const TRANSPARENT_1PX_PNG
  = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==';

async function fetchStatus() {
  isLoading.value = true;
  error.value = null;
  try {
    const result = await $fetch<{ success: boolean; data: SigningStatus; error?: string }>(
      `/api/requests/${requestId}/signing-status`,
    );
    if (result.success) {
      signingStatus.value = result.data;
      templatePlacedFields.value = [];
      previewPdfFile.value = null;

      const reqResult = await $fetch<{ success: boolean; data: any }>(
        `/api/requests/${requestId}`,
      );
      if (reqResult.success && reqResult.data?.request?.templateId) {
        await fetchTemplateData(Number(reqResult.data.request.templateId));
      }

      const pendingSteps = currentPendingSteps.value;
      if (pendingSteps.length > 0 && hasSignerProcessableFields.value) {
        schedulePreviewRefresh();
      }
    }
    else {
      error.value = result.error ?? t('signerSignDetail.errors.loadSigningStatus');
    }
  }
  catch (err: any) {
    error.value = err?.message ?? t('signerSignDetail.errors.loadDocument');
  }
  finally {
    isLoading.value = false;
  }
}

function handleSignatureConfirmed(dataUrl: string) {
  signatureDataUrl.value = dataUrl;
  signatureSource.value = 'drawn';
  selectedSavedSignatureId.value = null;
  showSignaturePopup.value = false;
  showSignatureSubmitError.value = false;
}

function getFirstEnteredFieldPayload(): { fieldId: number; instanceId: string; value: string } | null {
  for (const field of visibleSignerInputFields.value) {
    const instanceId = String(field?.instanceId ?? '').trim();
    if (!instanceId.length) {
      continue;
    }

    const fieldId = Number.parseInt(String(field?.id ?? ''), 10);
    if (!Number.isFinite(fieldId) || fieldId <= 0) {
      continue;
    }

    const value = resolveCurrentFieldValue(field);
    const normalized = normalizeFieldValue(value);
    if (!normalized.length) {
      continue;
    }

    return {
      fieldId,
      instanceId,
      value,
    };
  }

  return null;
}

function buildRejectFieldValuesPayload(): Array<{ fieldId: number; instanceId: string; value: string }> {
  return visibleSignerFillableFields.value
    .map((field) => {
      const instanceId = String(field?.instanceId ?? '').trim();
      const fieldId = Number.parseInt(String(field?.id ?? ''), 10);
      if (!instanceId.length || !Number.isFinite(fieldId) || fieldId <= 0) {
        return null;
      }
      return {
        fieldId,
        instanceId,
        value: resolveCurrentFieldValue(field) || '',
      };
    })
    .filter(Boolean) as Array<{ fieldId: number; instanceId: string; value: string }>;
}

function validateAllVisibleSignerFieldsForRejectWithData(): string | null {
  const fields = visibleSignerInputFields.value;
  const validatedCheckboxGroups = new Set<string>();

  if (!fields.length) {
    return null;
  }

  for (const field of fields) {
    if (isCheckboxField(field)) {
      const groupId = getCheckboxGroupId(field);
      if (groupId.length > 0) {
        if (validatedCheckboxGroups.has(groupId)) {
          continue;
        }

        validatedCheckboxGroups.add(groupId);
        const groupFields = fields.filter(candidate => isCheckboxField(candidate) && getCheckboxGroupId(candidate) === groupId);
        const anyChecked = groupFields.some(candidate => normalizeCheckboxValue(resolveCurrentFieldValue(candidate)) === 'true');
        if (!anyChecked) {
          return t('signerSignDetail.validation.completeAllFieldsBeforeRejectWithData');
        }

        continue;
      }

      if (normalizeCheckboxValue(resolveCurrentFieldValue(field)) !== 'true') {
        return t('signerSignDetail.validation.completeAllFieldsBeforeRejectWithData');
      }

      continue;
    }

    if (!normalizeFieldValue(resolveCurrentFieldValue(field)).length) {
      return t('signerSignDetail.validation.completeAllFieldsBeforeRejectWithData');
    }
  }

  return null;
}

async function rejectRequest(mode: RejectMode = 'status_only') {
  const pendingRoleNames = Array.from(new Set(currentPendingSteps.value.map(step => step.roleName))).join(', ');
  const instance = confirmDialogWithReason.open({
    title: mode === 'with_signature_and_field'
      ? t('signerSignDetail.rejectDialog.titleWithData')
      : t('signerSignDetail.rejectDialog.title'),
    description: t('signerSignDetail.rejectDialog.description', {
      step: currentPendingStep.value?.stepOrder ?? '-',
      roles: pendingRoleNames || '-',
    }),
    reasonRequired: true,
    reasonPlaceholder: t('signerSignDetail.rejectDialog.reasonPlaceholder'),
    reasonErrorMessage: t('signerSignDetail.rejectDialog.reasonErrorMessage'),
    cancelButton: { label: t('common.actions.cancel') },
    confirmButton: { label: t('signerSignDetail.rejectDialog.confirm'), color: 'error' },
  });

  const result = await instance.result;
  if (!result.confirmed) {
    return;
  }

  const reason = String(result.confirmationReason || '').trim();
  if (!reason.length) {
    return;
  }

  let selectedFieldPayload: { fieldId: number; instanceId: string; value: string } | null = null;
  if (mode === 'with_signature_and_field') {
    const allFieldsValidationError = validateAllVisibleSignerFieldsForRejectWithData();
    if (allFieldsValidationError) {
      toast.add({
        title: t('signerSignDetail.toast.incompleteDataTitle'),
        description: allFieldsValidationError,
        color: 'warning',
      });
      return;
    }

    selectedFieldPayload = getFirstEnteredFieldPayload();
    if (!selectedFieldPayload && visibleSignerInputFields.value.length > 0) {
      toast.add({
        title: t('signerSignDetail.toast.noFieldValueForModeTitle'),
        description: t('signerSignDetail.toast.noFieldValueForModeDescription'),
        color: 'warning',
      });
      return;
    }

    if (!signatureDataUrl.value && !selectedSavedSignatureId.value) {
      toast.add({
        title: t('signerSignDetail.toast.signatureRequiredTitle'),
        description: t('signerSignDetail.toast.signatureRequiredDescription'),
        color: 'error',
      });
      return;
    }
  }

  isRejecting.value = true;
  error.value = null;

  try {
    const requestBody: Record<string, unknown> = {
      reason,
      rejectMode: mode,
    };

    if (mode === 'with_signature_and_field') {
      if (selectedFieldPayload) {
        requestBody.selectedField = selectedFieldPayload;
      }
      requestBody.fieldValues = buildRejectFieldValuesPayload();
      if (signatureSource.value === 'saved' && selectedSavedSignatureId.value) {
        requestBody.userSignatureId = selectedSavedSignatureId.value;
      }
      else {
        requestBody.signatureDataUrl = signatureDataUrl.value;
      }
    }

    const res = await $fetch<{ success: boolean; data: any; error?: string }>(
      `/api/requests/${requestId}/reject`,
      {
        method: 'POST',
        body: requestBody,
      },
    );

    if (res.success) {
      const rejectionMode = String(res.data?.rejectionMode ?? 'full_request');
      const rejectDataMode = String(res.data?.rejectDataMode ?? mode);
      const isLocalReject = rejectionMode === 'local_step';
      const rejectedWithData = rejectDataMode === 'with_signature_and_field';

      toast.add({
        title: rejectedWithData
          ? (isLocalReject
              ? t('signerSignDetail.toast.rejectWithDataLocalTitle')
              : t('signerSignDetail.toast.rejectWithDataGlobalTitle'))
          : (isLocalReject
              ? t('signerSignDetail.toast.rejectLocalTitle')
              : t('signerSignDetail.toast.rejectTitle')),
        description: isLocalReject
          ? (res.data?.status === 'completed'
              ? t('signerSignDetail.toast.rejectLocalCompletedDescription')
              : (res.data?.nextRole
                  ? t('signerSignDetail.toast.rejectLocalForwardedDescription', { role: res.data.nextRole })
                  : t('signerSignDetail.toast.rejectLocalContinuesDescription')))
          : t('signerSignDetail.toast.rejectDescription'),
        color: isLocalReject ? 'warning' : 'error',
      });

      router.push('/signer/to-sign');

      signatureDataUrl.value = null;
      signatureSource.value = 'none';
      selectedSavedSignatureId.value = null;
      showSignaturePopup.value = false;
      await fetchStatus();
    }
    else {
      error.value = res.error ?? t('signerSignDetail.errors.rejectFailed');
    }
  }
  catch (err: any) {
    error.value = err?.message ?? t('signerSignDetail.errors.generic');
  }
  finally {
    isRejecting.value = false;
  }
}

async function scrollToSignerSignatureSection() {
  await nextTick();
  document.getElementById('signer-signature-section')?.scrollIntoView({ behavior: 'smooth', block: 'center' });
}

async function applySignSuccessResponse(data: any, opts: { noSignatureField: boolean }) {
  const newStatus = data?.status;
  const noSig = opts.noSignatureField;

  if (newStatus === 'completed') {
    successMessage.value = noSig
      ? t('signerSignDetail.success.completedWithoutSignature')
      : t('signerSignDetail.success.completedWithSignature');
  }
  else if (newStatus === 'in_progress') {
    successMessage.value = noSig
      ? t('signerSignDetail.success.forwardedWithoutSignature', { role: data?.nextRole ?? t('signerSignDetail.success.nextStepFallback') })
      : t('signerSignDetail.success.forwardedWithSignature', { role: data?.nextRole ?? t('signerSignDetail.success.nextStepFallback') });
    await fetchStatus();
  }
  else {
    successMessage.value = noSig
      ? t('signerSignDetail.success.forwardedWithoutSignature', { role: data?.nextRole ?? t('signerSignDetail.success.nextStepFallback') })
      : t('signerSignDetail.success.forwardedWithSignature', { role: data?.nextRole ?? t('signerSignDetail.success.nextStepFallback') });
  }

  await router.push('/signer/to-sign');

  signatureDataUrl.value = null;
  signatureSource.value = 'none';
  selectedSavedSignatureId.value = null;
  showSignaturePopup.value = false;
  showSignatureSubmitError.value = false;

  if (newStatus !== 'in_progress') {
    await fetchStatus();
  }
}

async function submitSignature(action: 'sign' | 'acknowledge' = 'sign') {
  error.value = null;
  showSignatureSubmitError.value = false;
  showRequiredFieldErrors.value = true;
  const validationError = validateRequiredSignerFields();
  if (validationError) {
    await scrollToFirstInvalidField();
    return;
  }

  if (hasSignatureField.value && !signatureDataUrl.value) {
    showSignatureSubmitError.value = true;
    await scrollToSignerSignatureSection();
    return;
  }

  showRequiredFieldErrors.value = false;
  showSignatureSubmitError.value = false;
  isSigning.value = true;

  try {
    if (hasSignerProcessableFields.value) {
      const saved = await saveSignerFieldValues();
      if (!saved) {
        isSigning.value = false;
        return;
      }
    }

    const signBody: { signatureDataUrl?: string; userSignatureId?: number; regenerateFilledPdf?: boolean; action?: 'sign' | 'acknowledge' } = {};

    if (hasSignatureField.value) {
      if (signatureSource.value === 'saved' && selectedSavedSignatureId.value) {
        signBody.userSignatureId = selectedSavedSignatureId.value;
      }
      else {
        signBody.signatureDataUrl = signatureDataUrl.value ?? TRANSPARENT_1PX_PNG;
      }
    }
    else {
      signBody.signatureDataUrl = TRANSPARENT_1PX_PNG;
    }

    if (hasSignerProcessableFields.value) {
      signBody.regenerateFilledPdf = true;
    }

    if (action === 'acknowledge') {
      signBody.action = 'acknowledge';
    }

    const result = await $fetch<{ success: boolean; data: any; error?: string }>(
      `/api/requests/${requestId}/sign`,
      { method: 'POST', body: signBody },
    );

    if (result.success) {
      if (action === 'acknowledge') {
        successMessage.value = t('signerSignDetail.success.acknowledged');
        await router.push('/signer/to-sign');
        signatureDataUrl.value = null;
        signatureSource.value = 'none';
        selectedSavedSignatureId.value = null;
        showSignaturePopup.value = false;
        showSignatureSubmitError.value = false;
        await fetchStatus();
      }
      else {
        await applySignSuccessResponse(
          result.data ?? {},
          { noSignatureField: !(hasSignatureField.value && signatureDataUrl.value) },
        );
      }
    }
    else {
      error.value = result.error
        ?? (hasSignatureField.value && signatureDataUrl.value
          ? t('signerSignDetail.errors.signFailed')
          : t('signerSignDetail.errors.processFailed'));
    }
  }
  catch (err: any) {
    error.value = err?.message ?? t('signerSignDetail.errors.generic');
  }
  finally {
    isSigning.value = false;
  }
}

const canSubmit = computed(() => {
  if (isSigning.value || isRejecting.value)
    return false;
  return true;
});

const statusColor: Record<string, 'success' | 'error' | 'warning' | 'info' | 'neutral' | 'primary' | 'secondary'> = {
  waiting: 'neutral',
  pending: 'warning',
  signed: 'success',
  acknowledged: 'primary',
  rejected: 'error',
  cancelled: 'neutral',
};

const statusLabel = computed<Record<string, string>>(() => ({
  waiting: t('signerSignDetail.status.waiting'),
  pending: t('signerSignDetail.status.pending'),
  signed: t('signerSignDetail.status.signed'),
  acknowledged: t('signerSignDetail.status.acknowledged'),
  rejected: t('signerSignDetail.status.rejected'),
  cancelled: t('signerSignDetail.status.cancelled'),
}));

async function fetchAttachments() {
  try {
    const result = await $fetch<{ success: boolean; data: Attachment[] }>(
      `/api/requests/${requestId}/attachments`,
    );
    if (result.success) {
      attachments.value = result.data;
    }
  }
  catch {}
}

function getFileIcon(fileName: string | null): string {
  if (!fileName)
    return 'i-heroicons-document';
  const ext = fileName.split('.').pop()?.toLowerCase();
  switch (ext) {
    case 'pdf': return 'i-heroicons-document-text';
    case 'jpg':
    case 'jpeg':
    case 'png':
    case 'gif': return 'i-heroicons-photo';
    case 'doc':
    case 'docx': return 'i-heroicons-document-text';
    case 'xls':
    case 'xlsx': return 'i-heroicons-table-cells';
    case 'zip':
    case 'rar': return 'i-heroicons-archive-box';
    default: return 'i-heroicons-document';
  }
}

const breadcrumbLinks = computed(() => [
  { label: t('signerSignDetail.breadcrumb.list'), to: '/signer/to-sign' },
  { label: signingStatus.value?.templateName ?? t('signerSignDetail.breadcrumb.requestNumber', { id: requestId }) },
]);

const hasConfirmedSignature = computed(() => (signatureDataUrl.value ?? '').length > 0);
const hasSavedSignature = computed(() => Boolean(savedUserSignature.value?.dataUrl));
const isUsingSavedSignature = computed(() => signatureSource.value === 'saved' && Boolean(selectedSavedSignatureId.value));

watch(
  () => currentPendingSteps.value.map(step => step.stepId).join('|'),
  (newId, oldId) => {
    if (oldId !== undefined && newId !== oldId) {
      fieldValues.value = {};
      signatureDataUrl.value = null;
      signatureSource.value = 'none';
      selectedSavedSignatureId.value = null;
      showSignaturePopup.value = false;
      showSignatureSubmitError.value = false;
    }
  },
);

watch(
  () => currentPendingSteps.value.length,
  (pendingCount) => {
    if (!pendingCount)
      showSignaturePopup.value = false;
  },
);

watch([fieldValues, signerFillableFields], () => {
  schedulePreviewRefresh();
}, { deep: true });

onMounted(() => {
  fetchStatus();
  fetchAttachments();
  fetchSavedUserSignature();
});

onUnmounted(() => {
  clearPreviewTimer();
  if (previewPdfBlobUrl.value) {
    URL.revokeObjectURL(previewPdfBlobUrl.value);
    previewPdfBlobUrl.value = null;
  }
});
</script>

<template>
  <div class="min-h-screen bg-gray-50">
    <!-- Header (aligned with student new-request) -->
    <div class="bg-white border-b">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
        <UBreadcrumb :links="breadcrumbLinks" />
        <div class="mt-4 flex items-center justify-between">
          <div>
            <h1 class="text-2xl font-bold text-gray-900">
              {{ signingStatus?.templateName ?? $t('signerSignDetail.header.defaultTitle') }}
            </h1>
            <p class="mt-1 text-sm text-gray-500">
              {{ $t('signerSignDetail.header.requestAndHint', { id: requestId }) }}
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <!-- Loading -->
      <div v-if="isLoading" class="flex items-center justify-center h-96">
        <div class="text-center">
          <i class="fas fa-spinner fa-spin text-4xl text-gray-400 mb-4" />
          <p class="text-gray-500">
            {{ $t('signerSignDetail.loading') }}
          </p>
        </div>
      </div>

      <!-- Load error -->
      <UCard v-else-if="!signingStatus">
        <div class="text-center py-8">
          <i class="fas fa-exclamation-triangle text-4xl text-red-400 mb-4" />
          <p class="text-red-600 mb-4">
            {{ error ?? $t('signerSignDetail.errors.loadData') }}
          </p>
          <UButton to="/signer/to-sign">
            {{ $t('signerSignDetail.actions.backToList') }}
          </UButton>
        </div>
      </UCard>

      <template v-else>
        <div class="grid grid-cols-1 lg:grid-cols-3 gap-6 items-start">
          <!-- Left: PDF preview (sticky on large screens) -->
          <div
            class="lg:col-span-2 lg:sticky lg:top-4 lg:z-10 lg:max-h-[min(100vh-5rem,100dvh-5rem)] lg:overflow-y-auto lg:pr-1 lg:-ml-1 lg:pl-1"
          >
            <div v-if="displayPdfUrl" style="min-height: 600px;">
              <div
                v-if="isRefreshingPreview && hasSignerProcessableFields"
                class="mb-2 text-xs text-gray-500 text-right"
              >
                {{ $t('signerSignDetail.preview.updating') }}
              </div>
              <TemplatePdfPreview
                :pdf-url="displayPdfUrl"
                :placed-fields="signatureFieldsForDisplay"
                :open-in-new-tab-url="signingStatus.filledDocumentUrl ?? displayPdfUrl"
                :open-in-new-tab-label="$t('signerSignDetail.preview.openInNewTab')"
              />
            </div>
            <div
              v-else
              class="flex items-center justify-center rounded-lg border border-gray-200 bg-white"
              style="min-height: 600px;"
            >
              <p class="text-sm text-gray-500 px-4 text-center">
                {{ $t('signerSignDetail.preview.empty') }}
              </p>
            </div>
          </div>

          <!-- Right: status, flow, attachments, actions -->
          <div class="space-y-6">
            <UCard v-if="successMessage" color="success">
              <div class="flex items-center gap-2">
                <i class="fas fa-check-circle" />
                <span class="font-medium">{{ successMessage }}</span>
              </div>
            </UCard>

            <UCard v-if="error" class="bg-red-50 border-red-200">
              <div class="flex items-center gap-2 text-red-800">
                <i class="fas fa-exclamation-circle" />
                <span class="font-medium">{{ error }}</span>
              </div>
            </UCard>

            <UCard>
              <template #header>
                <h3 class="text-sm font-semibold text-gray-500 uppercase">
                  {{ $t('signerSignDetail.signFlow.title') }}
                </h3>
              </template>
              <div class="space-y-2">
                <div
                  v-for="step in signingStatus.flowSteps"
                  :key="step.id"
                  class="flex items-center gap-3 p-3 rounded-lg border transition-colors"
                  :class="step.status === 'pending' ? 'bg-amber-50 border-amber-200' : 'bg-gray-50 border-gray-100'"
                >
                  <span
                    class="w-7 h-7 rounded-full flex items-center justify-center text-white text-xs font-bold shrink-0"
                    :class="{
                      'bg-green-500': step.status === 'signed',
                      'bg-blue-600': step.status === 'acknowledged',
                      'bg-amber-500': step.status === 'pending',
                      'bg-slate-300': step.status === 'waiting' || step.status === 'cancelled',
                      'bg-red-500': step.status === 'rejected',
                    }"
                  >
                    <UIcon v-if="step.status === 'signed'" name="i-heroicons-check" class="w-4 h-4" />
                    <UIcon v-else-if="step.status === 'acknowledged'" name="i-heroicons-hand-thumb-up" class="w-4 h-4" />
                    <UIcon v-else-if="step.status === 'rejected'" name="i-heroicons-x-mark" class="w-4 h-4" />
                    <template v-else>{{ step.stepOrder }}</template>
                  </span>
                  <div class="flex-1 min-w-0 flex items-center gap-2">
                    <span class="font-medium text-sm text-gray-900">{{ locale === 'th' ? step.roleNameTh : step.roleName }}</span>
                    <UBadge
                      v-if="step.acknowledgeOnly"
                      :label="$t('signerSignDetail.stepType.acknowledger')"
                      color="primary"
                      variant="subtle"
                      size="xs"
                    />
                  </div>
                  <UBadge
                    :color="(statusColor[step.status] ?? 'neutral')"
                    :label="statusLabel[step.status] ?? step.status"
                    variant="soft"
                    size="sm"
                    class="shrink-0"
                  />
                </div>
              </div>
            </UCard>

            <UCard>
              <template #header>
                <div class="flex items-center justify-between gap-2">
                  <h3 class="text-sm font-semibold text-gray-500 uppercase">
                    {{ $t('signerSignDetail.attachments.title') }}
                  </h3>
                  <UBadge
                    v-if="attachments.length > 0"
                    :label="String(attachments.length)"
                    color="neutral"
                    variant="soft"
                    size="sm"
                  />
                </div>
              </template>

              <div v-if="attachments.length === 0" class="text-center py-8 text-gray-500">
                <i class="fas fa-paperclip text-3xl mb-2" />
                <p class="text-sm">
                  {{ $t('signerSignDetail.attachments.empty') }}
                </p>
              </div>
              <div v-else class="space-y-3">
                <div
                  v-for="att in attachments"
                  :key="att.id"
                  class="flex items-center justify-between gap-3 p-3 bg-blue-50 rounded-lg border border-blue-100"
                >
                  <div class="flex items-center gap-3 flex-1 min-w-0">
                    <UIcon
                      :name="getFileIcon(att.fileName)"
                      class="w-5 h-5 text-blue-600 shrink-0"
                    />
                    <span class="text-sm font-medium text-gray-900 truncate">{{ att.fileName ?? $t('signerSignDetail.attachments.unnamed') }}</span>
                  </div>
                  <div class="flex items-center gap-2 shrink-0">
                    <UButton
                      v-if="att.fileUrl"
                      size="xs"
                      variant="soft"
                      color="primary"
                      icon="i-heroicons-eye"
                      @click="openPreview(att)"
                    >
                      {{ $t('signerSignDetail.attachments.actions.preview') }}
                    </UButton>
                    <UButton
                      v-if="att.fileUrl"
                      size="xs"
                      variant="outline"
                      color="neutral"
                      icon="i-heroicons-arrow-top-right-on-square"
                      :to="att.fileUrl"
                      target="_blank"
                    >
                      {{ $t('signerSignDetail.attachments.actions.openNew') }}
                    </UButton>
                  </div>
                </div>
              </div>
            </UCard>

            <UCard v-if="hasCurrentPendingSteps && hasSignerInputFields">
              <template #header>
                <h3 class="text-sm font-semibold text-gray-500 uppercase">
                  {{ $t('signerSignDetail.fieldsToFill.title') }}
                </h3>
              </template>

              <div class="space-y-4">
                <div
                  v-for="field in visibleSignerInputFields"
                  :id="getFieldContainerId(field)"
                  :key="field.instanceId"
                  class="field-group rounded-lg px-3 py-3 transition-colors"
                  :class="hasFieldValidationError(field) ? 'border border-red-400 bg-white' : 'border border-transparent bg-white'"
                >
                  <form-field-input
                    :model-value="fieldValues[getFieldValueKey(field)] ?? ''"
                    :field="{ ...field, label: field.formQuestionLabel || field.label }"
                    :disabled="isSigning || isCheckboxTemporarilyDisabled(field)"
                    @update:model-value="(v) => handleSignerFieldValueUpdate(field, String(v ?? ''))"
                  />
                  <p
                    v-if="hasFieldValidationError(field)"
                    class="mt-2 text-sm text-red-600"
                  >
                    {{ getFieldValidationMessage(field) }}
                  </p>
                </div>
              </div>
            </UCard>

            <UAlert
              v-if="hasCurrentPendingSteps && hasSignatureField && !isAcknowledgeMode"
              color="info"
              variant="soft"
              icon="i-heroicons-pencil-square"
              :title="$t('signerSignDetail.signature.alertTitle')"
              :description="$t('signerSignDetail.signature.alertDescription', { step: currentPendingStep?.stepOrder ?? '-', roles: Array.from(new Set(currentPendingSteps.map(step => locale === 'th' ? step.roleNameTh : step.roleName))).join(', ') || '-' })"
            />

            <UAlert
              v-else-if="isAcknowledgeMode && hasCurrentPendingSteps"
              color="primary"
              variant="soft"
              icon="i-heroicons-hand-thumb-up"
              :title="$t('signerSignDetail.acknowledge.alertTitle')"
              :description="$t('signerSignDetail.acknowledge.alertDescription', { step: currentPendingStep?.stepOrder ?? '-', roles: Array.from(new Set(currentPendingSteps.map(step => locale === 'th' ? step.roleNameTh : step.roleName))).join(', ') || '-' })"
            />

            <UCard
              v-if="hasCurrentPendingSteps && hasSignatureField && !isAcknowledgeMode"
              id="signer-signature-section"
              class="rounded-lg transition-colors"
              :class="showSignatureSubmitError ? 'border border-red-400 bg-white' : ''"
            >
              <template #header>
                <h3 class="text-sm font-semibold text-gray-500 uppercase">
                  {{ $t('signerSignDetail.signature.sectionTitle') }}
                </h3>
              </template>

              <div class="space-y-3">
                <p class="text-xs leading-5 text-gray-500">
                  {{ $t('signerSignDetail.signature.helper') }}
                </p>

                <div
                  v-if="showSignatureSubmitError"
                  class="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700"
                >
                  {{ $t('signerSignDetail.signature.submitError') }}
                </div>

                <div
                  v-else-if="isUsingSavedSignature"
                  class="rounded-md border border-blue-200 bg-blue-50 px-3 py-2 text-sm text-blue-700"
                >
                  {{ $t('signerSignDetail.signature.usingSaved') }}
                </div>

                <div
                  v-else-if="hasConfirmedSignature"
                  class="rounded-md border border-green-200 bg-green-50 px-3 py-2 text-sm text-green-700"
                >
                  {{ $t('signerSignDetail.signature.confirmed') }}
                </div>

                <div class="flex flex-col gap-2">
                  <UButton
                    color="primary"
                    icon="i-heroicons-pencil-square"
                    block
                    :disabled="isSigning"
                    @click="openSignaturePopup"
                  >
                    {{ hasConfirmedSignature ? $t('signerSignDetail.signature.drawOrEdit') : $t('signerSignDetail.signature.openPad') }}
                  </UButton>

                  <UButton
                    v-if="hasSavedSignature"
                    color="neutral"
                    variant="soft"
                    icon="i-heroicons-bookmark"
                    block
                    :disabled="isSigning || isLoadingSavedSignature"
                    @click="useSavedSignatureForCurrentSign"
                  >
                    {{ $t('signerSignDetail.signature.useSaved') }}
                  </UButton>

                  <div
                    v-if="hasConfirmedSignature"
                    class="flex items-center justify-end gap-2"
                  >
                    <UTooltip
                      v-if="signatureSource === 'drawn'"
                      :text="$t('signerSignDetail.signature.saveForNextTime')"
                      :popper="{ placement: 'top' }"
                    >
                      <UButton
                        size="sm"
                        color="neutral"
                        variant="outline"
                        icon="i-heroicons-bookmark-square"
                        :loading="isSavingSignature"
                        :disabled="isSigning"
                        :aria-label="$t('signerSignDetail.signature.saveForNextTime')"
                        @click="saveCurrentSignatureForFuture"
                      >
                        {{ $t('signerSignDetail.signature.saveShort') }}
                      </UButton>
                    </UTooltip>

                    <UTooltip
                      :text="$t('signerSignDetail.signature.clearConfirmed')"
                      :popper="{ placement: 'top' }"
                    >
                      <UButton
                        size="sm"
                        color="error"
                        variant="ghost"
                        icon="i-heroicons-trash"
                        :disabled="isSigning"
                        :aria-label="$t('signerSignDetail.signature.clearConfirmed')"
                        @click="clearConfirmedSignature"
                      >
                        {{ $t('signerSignDetail.signature.clearShort') }}
                      </UButton>
                    </UTooltip>
                  </div>
                </div>
              </div>
            </UCard>

            <div v-if="hasCurrentPendingSteps" class="flex flex-col gap-3">
              <template v-if="!isAcknowledgeMode && !canShowRejectWithFieldButton">
                <UButton
                  color="error"
                  variant="soft"
                  size="lg"
                  block
                  icon="i-heroicons-x-circle"
                  :loading="isRejecting"
                  :disabled="isSigning"
                  @click="rejectRequest('status_only')"
                >
                  {{ $t('signerSignDetail.actions.reject') }}
                </UButton>
              </template>
              <div v-else-if="!isAcknowledgeMode" class="grid grid-cols-1 sm:grid-cols-2 gap-2">
                <UButton
                  color="error"
                  variant="soft"
                  size="lg"
                  block
                  icon="i-heroicons-x-circle"
                  :loading="isRejecting"
                  :disabled="isSigning"
                  @click="rejectRequest('status_only')"
                >
                  {{ $t('signerSignDetail.actions.reject') }}
                </UButton>
                <UButton
                  color="error"
                  variant="outline"
                  size="lg"
                  block
                  icon="i-heroicons-document-text"
                  :loading="isRejecting"
                  :disabled="isSigning"
                  @click="rejectRequest('with_signature_and_field')"
                >
                  {{ $t('signerSignDetail.actions.rejectWithSignature') }}
                </UButton>
              </div>
              <UButton
                :color="isAcknowledgeMode ? 'primary' : 'success'"
                size="lg"
                block
                :icon="isAcknowledgeMode ? 'i-heroicons-hand-thumb-up' : 'i-heroicons-paper-airplane'"
                :loading="isSigning"
                :disabled="!canSubmit"
                @click="submitSignature(isAcknowledgeMode ? 'acknowledge' : 'sign')"
              >
                {{ isAcknowledgeMode
                  ? $t('signerSignDetail.actions.acknowledge')
                  : (hasSignatureField ? $t('signerSignDetail.actions.signAndContinue') : $t('signerSignDetail.actions.confirmAndContinue')) }}
              </UButton>
            </div>

            <UCard v-else-if="signingStatus.status === 'rejected'">
              <div class="text-center py-8">
                <UIcon name="i-heroicons-x-circle" class="w-16 h-16 text-red-500 mx-auto mb-4" />
                <h3 class="text-xl font-bold text-gray-900 mb-2">
                  {{ $t('signerSignDetail.rejected.title') }}
                </h3>
                <p v-if="signingStatus.note" class="text-gray-500 mb-4 max-w-md mx-auto text-sm">
                  {{ $t('signerSignDetail.rejected.reasonPrefix') }}: {{ signingStatus.note }}
                </p>
                <p v-else class="text-gray-500 mb-4 text-sm">
                  {{ $t('signerSignDetail.rejected.description') }}
                </p>
              </div>
            </UCard>

            <UCard v-else-if="signingStatus.status === 'completed'">
              <div class="text-center py-8">
                <UIcon name="i-heroicons-check-circle" class="w-16 h-16 text-green-500 mx-auto mb-4" />
                <h3 class="text-xl font-bold text-gray-900 mb-2">
                  {{ $t('signerSignDetail.completed.title') }}
                </h3>
                <p class="text-gray-500 mb-4 text-sm">
                  {{ $t('signerSignDetail.completed.description') }}
                </p>
                <UButton
                  v-if="signingStatus.filledDocumentUrl"
                  :to="signingStatus.filledDocumentUrl"
                  target="_blank"
                  color="success"
                  icon="i-heroicons-arrow-down-tray"
                >
                  {{ $t('signerSignDetail.completed.download') }}
                </UButton>
              </div>
            </UCard>

            <UCard v-else-if="!hasCurrentPendingSteps && signingStatus.status !== 'completed'">
              <div class="text-center py-8">
                <UIcon name="i-heroicons-clock" class="w-12 h-12 text-amber-400 mx-auto mb-4" />
                <h3 class="font-semibold text-gray-900 mb-2">
                  {{ $t('signerSignDetail.notYourTurn.title') }}
                </h3>
                <p class="text-sm text-gray-500">
                  {{ $t('signerSignDetail.notYourTurn.description') }}
                </p>
              </div>
            </UCard>

            <UButton
              block
              variant="outline"
              color="neutral"
              to="/signer/to-sign"
              class="rounded-md"
            >
              <i class="fas fa-arrow-left mr-2" />
              {{ $t('signerSignDetail.actions.backToList') }}
            </UButton>
          </div>
        </div>

        <UModal v-model:open="isPreviewOpen" class="max-w-4xl" @close="closePreview">
          <template #header>
            <div class="flex items-center gap-2 min-w-0">
              <UIcon :name="getFileIcon(previewAttachment?.fileName ?? null)" class="text-gray-500 shrink-0" />
              <span class="font-semibold text-gray-900 truncate">{{ previewAttachment?.fileName ?? $t('signerSignDetail.attachments.title') }}</span>
            </div>
          </template>
          <template #body>
            <div v-if="previewAttachment?.fileUrl" class="w-full">
              <iframe
                v-if="previewAttachment.fileName?.toLowerCase().endsWith('.pdf')"
                :src="previewAttachment.fileUrl"
                class="w-full rounded border border-gray-200"
                style="height: 70vh;"
                frameborder="0"
              />
              <img
                v-else-if="/\.(jpe?g|png|gif|webp)$/i.test(previewAttachment.fileName ?? '')"
                :src="previewAttachment.fileUrl"
                :alt="previewAttachment.fileName ?? ''"
                class="max-w-full mx-auto rounded"
              >
              <div v-else class="text-center py-12 text-gray-500">
                <UIcon name="i-heroicons-document" class="w-12 h-12 mx-auto mb-3 text-gray-300" />
                <p class="text-sm">
                  {{ $t('signerSignDetail.attachments.previewNotAvailable') }}
                </p>
                <UButton
                  :to="previewAttachment.fileUrl"
                  target="_blank"
                  color="primary"
                  variant="soft"
                  icon="i-heroicons-arrow-down-tray"
                  class="mt-3"
                >
                  {{ $t('signerSignDetail.attachments.actions.download') }}
                </UButton>
              </div>
            </div>
          </template>
        </UModal>

        <!-- Signature popup (same pattern as student new-request) -->
        <div
          v-if="showSignaturePopup && hasCurrentPendingSteps"
          class="fixed inset-0 z-50 bg-black/20 backdrop-blur-[1px]"
          @click.self="closeSignaturePopup"
        >
          <div class="absolute bottom-4 right-4" :style="signaturePopupStyle">
            <UCard class="overflow-hidden border border-gray-200 shadow-2xl bg-white">
              <template #header>
                <div class="flex items-start justify-between gap-3">
                  <div>
                    <h3 class="text-sm font-semibold text-gray-900">
                      {{ $t('signerSignDetail.signature.popupTitle', { step: currentPendingStep?.stepOrder ?? '-', roles: Array.from(new Set(currentPendingSteps.map(step => locale === 'th' ? step.roleNameTh : step.roleName))).join(', ') || '-' }) }}
                    </h3>
                  </div>
                  <UButton
                    color="neutral"
                    variant="ghost"
                    icon="i-heroicons-x-mark"
                    @click="closeSignaturePopup"
                  />
                </div>
              </template>

              <div class="space-y-3 p-1">
                <div class="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-3">
                  <div class="mb-2 flex items-center justify-between text-xs text-slate-500">
                    <span>{{ $t('signerSignDetail.signature.popupHint') }}</span>
                  </div>

                  <div :style="signatureFieldBoxStyle" class="mx-auto">
                    <SignatureCanvas
                      class="w-full"
                      :disabled="isSigning"
                      :aspect-ratio="signatureFieldAspectRatio"
                      :pdf-field-width-pt="signatureFieldWidthPt"
                      @confirm="handleSignatureConfirmed"
                    />
                  </div>
                </div>
              </div>
            </UCard>
          </div>
        </div>
      </template>
    </div>
  </div>
</template>
