import type { H3Event } from 'h3';

import { eq } from 'drizzle-orm';

import db from '../../../lib/db/index';
import { requestTemplateFields } from '../../../lib/db/schema';

function parsePositiveInteger(value: unknown): number | null {
  const parsed = Number.parseInt(String(value ?? ''), 10);
  if (!Number.isFinite(parsed) || parsed <= 0) {
    return null;
  }
  return parsed;
}

function parseFiniteNumber(value: unknown, fallback: number): number {
  const parsed = Number.parseFloat(String(value ?? ''));
  if (!Number.isFinite(parsed)) {
    return fallback;
  }
  return parsed;
}

function normalizeEnum<T extends string>(value: unknown, allowed: readonly T[], fallback: T): T {
  const normalized = String(value ?? '').trim() as T;
  if (allowed.includes(normalized)) {
    return normalized;
  }
  return fallback;
}

function supportsMaxLength(fieldType: unknown): boolean {
  const type = String(fieldType ?? '').toLowerCase();
  return !['signature', 'icon', 'date', 'time', 'checkbox'].includes(type);
}

function resolveStrikeLineThickness(value: unknown): number {
  const parsed = parseFiniteNumber(value, 1.5);
  if (!Number.isFinite(parsed) || parsed <= 0) {
    return 1.5;
  }
  return Math.min(8, Math.max(0.5, parsed));
}

function normalizeSessionField(value: unknown): 'studentName' | 'studentId' | null {
  const normalized = String(value ?? '').trim();
  if (normalized === 'studentName' || normalized === 'studentId') {
    return normalized;
  }
  return null;
}

export default defineEventHandler(async (event: H3Event) => {
  // await requirePermission(event, '<permission>', '<permission>', ...);

  try {
    const id = getRouterParam(event, 'id');
    if (!id) {
      throw createError({
        statusCode: 400,
        message: 'ไม่พบ ID ของ Field',
      });
    }

    const body = await readBody(event);

    // Validate required fields
    if (!body.name || !body.type || !body.label || !body.icon) {
      throw createError({
        statusCode: 400,
        message: 'กรุณากรอกข้อมูลให้ครบถ้วน',
      });
    }

    const width = parsePositiveInteger(body.width) ?? 150;
    const height = parsePositiveInteger(body.height) ?? 40;
    const amount = parsePositiveInteger(body.amount) ?? 1;
    const fontSize = parsePositiveInteger(body.fontSize) ?? 14;
    const maxLength = supportsMaxLength(body.type) ? parsePositiveInteger(body.maxLength) : null;
    const isCheckboxGroup = String(body.type || '').toLowerCase() === 'checkbox' && amount > 1;
    const strikeThroughGroupMode = isCheckboxGroup ? Boolean(body.strikeThroughGroupMode ?? body.strike_through_group_mode ?? false) : false;
    const strikeLineThickness = resolveStrikeLineThickness(body.strikeLineThickness ?? body.strike_line_thickness);
    const sessionField = normalizeSessionField(body.sessionField ?? body.session_field);

    // Update field
    const [updatedField] = await db
      .update(requestTemplateFields)
      .set({
        name: body.name,
        type: body.type,
        label: body.label,
        icon: body.icon,
        width,
        height,
        amount,
        font: body.font || null,
        fontSize,
        fontWeight: normalizeEnum(body.fontWeight, ['normal', 'bold'], 'normal'),
        fontStyle: normalizeEnum(body.fontStyle, ['normal', 'italic'], 'normal'),
        textDecoration: normalizeEnum(body.textDecoration, ['none', 'underline'], 'none'),
        textAlign: normalizeEnum(body.textAlign, ['left', 'center', 'right'], 'left'),
        letterSpacing: parseFiniteNumber(body.letterSpacing, 0),
        lineHeight: parseFiniteNumber(body.lineHeight, 1.5),
        sessionField,
        strikeThroughGroupMode,
        strikeLineThickness,
        maxLength,
        isFillable: body.isFillable ?? true,
        isAutoGenerated: String(body.type || '').toLowerCase() === 'time'
          ? true
          : (body.isAutoGenerated ?? false),
      })
      .where(eq(requestTemplateFields.id, Number(id)))
      .returning();

    if (!updatedField) {
      throw createError({
        statusCode: 404,
        message: 'ไม่พบ Field ที่ต้องการอัพเดท',
      });
    }

    // Map ข้อมูลให้ตรงกับ format ที่ frontend ต้องการ
    const mappedField = {
      id: updatedField.id,
      name: updatedField.name,
      label: updatedField.label,
      type: updatedField.type,
      icon: updatedField.icon,
      default_width: updatedField.width,
      default_height: updatedField.height,
      amount: updatedField.amount || 1,
      font: updatedField.font,
      fontSize: updatedField.fontSize,
      fontWeight: updatedField.fontWeight,
      fontStyle: updatedField.fontStyle,
      textDecoration: updatedField.textDecoration,
      textAlign: updatedField.textAlign,
      letterSpacing: updatedField.letterSpacing,
      lineHeight: updatedField.lineHeight,
      sessionField: updatedField.sessionField,
      session_field: updatedField.sessionField,
      strikeThroughGroupMode: updatedField.strikeThroughGroupMode,
      strike_through_group_mode: updatedField.strikeThroughGroupMode,
      strikeLineThickness: updatedField.strikeLineThickness,
      strike_line_thickness: updatedField.strikeLineThickness,
      maxLength: updatedField.maxLength,
      isFillable: updatedField.isFillable,
      isAutoGenerated: updatedField.isAutoGenerated,
    };

    return {
      success: true,
      data: mappedField,
      message: 'อัพเดท Field สำเร็จ',
    };
  }
  catch (error: any) {
    console.error('Error updating template field:', error);
    throw createError({
      statusCode: error.statusCode || 500,
      message: error.message || 'เกิดข้อผิดพลาดในการอัพเดท Field',
    });
  }
});
