<script setup lang="ts">
import { formatAutoGeneratedDate, getAutoDateTimeFormatConfig } from '~~/shared/auto-date-time-format';
import { getFieldDisplayInstanceNumber } from '~~/shared/field-instance-number';

type Field = any;

const props = withDefaults(defineProps<{
  selectedField?: Field;
  placedFields?: Field[];
  pdfRef?: any;
  scale?: number;
  isSavingDefaults?: boolean;
}>(), {
  placedFields: () => [],
  isSavingDefaults: false,
});

const emit = defineEmits<{
  fieldUpdated: [data: { instanceId: string; updates: any }];
  fieldRemoved: [instanceId: string];
  saveDefaults: [data: { fieldId: number | string; defaults: any }];
}>();

const localField = ref<any>({});

function getFieldType(field?: Field): string {
  return String(field?.type || field?.fieldType || '').toLowerCase();
}

function supportsConditionalSource(field?: Field): boolean {
  if (!field) {
    return false;
  }

  const fieldType = getFieldType(field);
  const fieldName = String(field.name || '').trim().toLowerCase();
  return fieldType === 'checkbox' || fieldName === 'check mark';
}

function normalizeVisibilityRule(rawRule: any) {
  if (!rawRule || typeof rawRule !== 'object') {
    return null;
  }

  const sourceFieldInstanceId = String(rawRule.sourceFieldInstanceId ?? rawRule.source_field_instance_id ?? '').trim();
  const sourceGroupId = String(rawRule.sourceGroupId ?? rawRule.source_group_id ?? '').trim();
  if (!sourceFieldInstanceId.length && !sourceGroupId.length) {
    return null;
  }

  return {
    enabled: rawRule.enabled !== false,
    sourceFieldInstanceId: sourceFieldInstanceId || null,
    sourceGroupId: sourceGroupId || null,
    operator: rawRule.operator === 'isUnchecked' ? 'isUnchecked' : 'isChecked',
    // Always preserve hidden field values.
    clearWhenHidden: false,
  };
}

function getConditionalSourceLabel(field?: Field): string {
  if (!field) {
    return 'Checkbox';
  }

  const baseLabel = String(field.label || field.name || 'Checkbox').trim();
  const instanceSuffix = ` #${getFieldDisplayInstanceNumber(field, props.placedFields)}`;
  return `${baseLabel}${instanceSuffix}`;
}

const conditionalSourceOptions = computed(() => {
  const selectedInstanceId = String(props.selectedField?.instanceId || '').trim();

  return (props.placedFields || [])
    .filter((field: any) => {
      if (!field) {
        return false;
      }

      const instanceId = String(field.instanceId || '').trim();
      if (!instanceId.length || instanceId === selectedInstanceId) {
        return false;
      }

      return supportsConditionalSource(field);
    })
    .map((field: any) => {
      return {
        value: String(field.instanceId),
        label: getConditionalSourceLabel(field),
      };
    });
});

const conditionalGroupSourceOptions = computed(() => {
  const groupedCheckboxes = (props.placedFields || []).filter((field: any) => {
    if (!field || !supportsConditionalSource(field)) {
      return false;
    }

    const groupId = String(field.groupId || '').trim();
    return groupId.length > 0;
  });

  const uniqueGroups = new Map<string, string>();
  for (const field of groupedCheckboxes) {
    const groupId = String(field.groupId || '').trim();
    if (!groupId || uniqueGroups.has(groupId)) {
      continue;
    }
    const baseLabel = String(field.label || field.name || 'Checkbox Group').trim();
    uniqueGroups.set(groupId, `${baseLabel} (ทั้งกลุ่ม)`);
  }

  return Array.from(uniqueGroups.entries()).map(([value, label]) => ({ value, label }));
});

function normalizeMaxLength(value: unknown): number | null {
  const parsed = Number.parseInt(String(value ?? ''), 10);
  if (!Number.isFinite(parsed) || parsed <= 0)
    return null;
  return parsed;
}

function normalizeFontSize(value: unknown): number {
  const parsed = Number.parseFloat(String(value ?? ''));
  if (!Number.isFinite(parsed) || parsed <= 0)
    return 14;
  return parsed;
}

const fontSizeInput = ref('');
const fontSizeCommitted = ref(14);

function setFontSize(nextFontSize: unknown): void {
  const normalizedFontSize = normalizeFontSize(nextFontSize);
  fontSizeCommitted.value = normalizedFontSize;
  fontSizeInput.value = String(normalizedFontSize);
  localField.value.fontSize = normalizedFontSize;
  onPropertyChange();
}

function handleFontSizeInput(): void {
  const rawValue = String(fontSizeInput.value ?? '').trim();
  if (!rawValue.length) {
    return;
  }

  const parsedFontSize = Number.parseFloat(rawValue);
  if (!Number.isFinite(parsedFontSize) || parsedFontSize <= 0) {
    return;
  }

  localField.value.fontSize = parsedFontSize;
  onPropertyChange();
}

function handleFontSizeBlur(): void {
  const rawValue = String(fontSizeInput.value ?? '').trim();
  const restoredFontSize = fontSizeCommitted.value || 14;

  if (!rawValue.length) {
    setFontSize(restoredFontSize);
    return;
  }

  const parsedFontSize = Number.parseFloat(rawValue);
  if (!Number.isFinite(parsedFontSize) || parsedFontSize <= 0) {
    setFontSize(restoredFontSize);
    return;
  }

  setFontSize(parsedFontSize);
}

const selectedFieldType = computed(() => String(props.selectedField?.type || props.selectedField?.fieldType || '').toLowerCase());
const isDateField = computed(() => selectedFieldType.value === 'date');

// Use live current date so preview always matches actual output
const dateFormatPreview = computed(() => {
  if (!isDateField.value)
    return '';
  return formatAutoGeneratedDate(localField.value, new Date());
});
const isTimeField = computed(() => selectedFieldType.value === 'time');
const isCheckboxType = computed(() => selectedFieldType.value === 'checkbox');
const supportsAutoGenerateToggle = computed(() => isDateField.value || isTimeField.value);

const supportsMaxLength = computed(() => {
  return selectedFieldType.value !== 'signature'
    && selectedFieldType.value !== 'icon'
    && selectedFieldType.value !== 'date'
    && selectedFieldType.value !== 'time'
    && selectedFieldType.value !== 'checkbox';
});

const fontSizeDropdownItems = [6, 8, 10, 12, 14, 16, 18, 20, 22, 24].map(size => ({
  label: String(size),
  onSelect: () => {
    setFontSize(size);
  },
}));

// Use computed for display coordinates to ensure they recalculate when scale changes
const displayCoords = computed(() => {
  const field = props.selectedField;
  const _scale = props.scale; // Force dependency tracking on scale
  const pdfRef = props.pdfRef; // Force dependency tracking on pdfRef

  if (!field) {
    return { x: 0, y: 0, width: 0, height: 0 };
  }

  // For PDF with normalized coordinates, calculate display coords using scale
  if (pdfRef && field.normalizedX !== undefined && field.normalizedY !== undefined) {
    if (typeof pdfRef.normalizedToDisplay === 'function') {
      const display = pdfRef.normalizedToDisplay(
        field.normalizedX,
        field.normalizedY,
        field.normalizedWidth,
        field.normalizedHeight,
      );
      return {
        x: Math.round(display.x),
        y: Math.round(display.y),
        width: Math.round(display.width),
        height: Math.round(display.height),
      };
    }
  }

  // For images or fields without normalized coords, use pixel coordinates
  return {
    x: field.displayX !== undefined ? Math.round(field.displayX) : (field.x || 50),
    y: field.displayY !== undefined ? Math.round(field.displayY) : (field.y || 50),
    width: field.displayWidth !== undefined ? Math.round(field.displayWidth) : (field.width || 150),
    height: field.displayHeight !== undefined ? Math.round(field.displayHeight) : (field.height || 40),
  };
});

// Editable values that user can modify (Still keeping X, Y in state to preserve them when saving other properties)
const editableX = ref(0);
const editableY = ref(0);
const editableWidth = ref(0);
const editableHeight = ref(0);

// Watch displayCoords and update editable values
watch(displayCoords, (newCoords) => {
  editableX.value = newCoords.x;
  editableY.value = newCoords.y;
  editableWidth.value = newCoords.width;
  editableHeight.value = newCoords.height;
}, { immediate: true });

// Watch selectedField for font properties
watch(
  () => props.selectedField?.instanceId,
  () => {
    const newField = props.selectedField;

    if (newField) {
      const fieldType = getFieldType(newField);
      const autoDateTimeConfig = getAutoDateTimeFormatConfig(newField);
      const visibilityRule = normalizeVisibilityRule(newField.visibilityRule ?? newField.visibility_rule);
      const fontSize = normalizeFontSize(newField.fontSize ?? newField.font_size);
      localField.value = {
        ...newField,
        fontSize,
        ...autoDateTimeConfig,
        isAutoGenerated: Boolean(newField.isAutoGenerated ?? newField.isAutoGenerate ?? newField.is_auto_generated ?? false),
        fontWeight: newField.fontWeight || 'normal',
        fontStyle: newField.fontStyle || 'normal',
        textDecoration: newField.textDecoration || 'none',
        textAlign: newField.textAlign || 'left',
        letterSpacing: fieldType === 'date' || fieldType === 'time' ? 0 : (newField.letterSpacing ?? 0),
        lineHeight: newField.lineHeight ?? 1.5,
        maxLength: normalizeMaxLength(newField.maxLength ?? newField.max_length),
        strikeThroughGroupMode: Boolean(newField.strikeThroughGroupMode ?? newField.strike_through_group_mode ?? false),
        strikeLineThickness: Number.parseFloat(String(newField.strikeLineThickness ?? newField.strike_line_thickness ?? 1.5)) || 1.5,
        conditionalEnabled: Boolean(visibilityRule),
        conditionalSourceType: visibilityRule?.sourceGroupId ? 'group' : 'single',
        conditionalSourceFieldInstanceId: visibilityRule?.sourceFieldInstanceId || '',
        conditionalSourceGroupId: visibilityRule?.sourceGroupId || '',
        conditionalOperator: visibilityRule?.operator || 'isChecked',
      };

      fontSizeCommitted.value = fontSize;
      fontSizeInput.value = String(fontSize);
    }
    else {
      localField.value = {};
      fontSizeInput.value = '';
      fontSizeCommitted.value = 14;
    }
  },
  { immediate: true },
);

function toggleConditionalVisibility() {
  if (!localField.value) {
    return;
  }

  localField.value.conditionalEnabled = !localField.value.conditionalEnabled;
  if (!localField.value.conditionalEnabled) {
    localField.value.conditionalSourceFieldInstanceId = '';
    localField.value.conditionalSourceGroupId = '';
  }

  onPropertyChange();
}

function onPropertyChange() {
  if (!localField.value || !props.selectedField)
    return;

  const autoDateTimeConfig = getAutoDateTimeFormatConfig(localField.value);

  const dateTimeFormatUpdates = isDateField.value
    ? {
        dateSeparator: autoDateTimeConfig.dateSeparator,
        dateSeparatorSpacing: autoDateTimeConfig.dateSeparatorSpacing,
        dateShowDay: autoDateTimeConfig.dateShowDay,
        dateShowMonth: autoDateTimeConfig.dateShowMonth,
        dateShowYear: autoDateTimeConfig.dateShowYear,
        dateShowDayOfWeek: autoDateTimeConfig.dateShowDayOfWeek,
        dateDayOfWeekStyle: autoDateTimeConfig.dateDayOfWeekStyle,
        dateDayOfWeekGap: autoDateTimeConfig.dateDayOfWeekGap,
        dateMonthStyle: autoDateTimeConfig.dateMonthStyle,
        dateCalendar: autoDateTimeConfig.dateCalendar,
      }
    : isTimeField.value
      ? {
          timeSeparator: autoDateTimeConfig.timeSeparator,
          timeSeparatorSpacing: autoDateTimeConfig.timeSeparatorSpacing,
          timeShowHour: autoDateTimeConfig.timeShowHour,
          timeShowMinute: autoDateTimeConfig.timeShowMinute,
        }
      : {};

  const sourceType = localField.value.conditionalSourceType === 'group' ? 'group' : 'single';
  const sourceFieldInstanceId = sourceType === 'single'
    ? String(localField.value.conditionalSourceFieldInstanceId || '').trim()
    : '';
  const sourceGroupId = sourceType === 'group'
    ? String(localField.value.conditionalSourceGroupId || '').trim()
    : '';

  const commonStyleUpdates = {
    fontSize: normalizeFontSize(localField.value.fontSize),
    fontFamily: localField.value.fontFamily || 'Arial',
    fontWeight: localField.value.fontWeight || 'normal',
    fontStyle: localField.value.fontStyle || 'normal',
    textDecoration: localField.value.textDecoration || 'none',
    textAlign: localField.value.textAlign || 'left',
    letterSpacing: isDateField.value || isTimeField.value ? 0 : (localField.value.letterSpacing ?? 0),
    lineHeight: localField.value.lineHeight ?? 1.5,
    maxLength: supportsMaxLength.value ? normalizeMaxLength(localField.value.maxLength) : null,
    strikeThroughGroupMode: isCheckboxType.value ? Boolean(localField.value.strikeThroughGroupMode) : false,
    strikeLineThickness: isCheckboxType.value
      ? Math.min(8, Math.max(0.5, Number.parseFloat(String(localField.value.strikeLineThickness ?? 1.5)) || 1.5))
      : 1.5,
    isAutoGenerate: supportsAutoGenerateToggle.value
      ? Boolean(localField.value.isAutoGenerated)
      : false,
    isAutoGenerated: supportsAutoGenerateToggle.value
      ? Boolean(localField.value.isAutoGenerated)
      : false,
    is_auto_generated: supportsAutoGenerateToggle.value
      ? Boolean(localField.value.isAutoGenerated)
      : false,
    visibilityRule: localField.value.conditionalEnabled
      ? normalizeVisibilityRule({
          enabled: true,
          sourceFieldInstanceId,
          sourceGroupId,
          operator: localField.value.conditionalOperator,
          clearWhenHidden: false,
        })
      : null,
    ...dateTimeFormatUpdates,
  };

  // For PDF with normalized coordinates, convert display back to normalized
  if (props.pdfRef && props.selectedField.normalizedX !== undefined) {
    if (typeof props.pdfRef.displayToNormalized === 'function') {
      const normalized = props.pdfRef.displayToNormalized(
        editableX.value,
        editableY.value,
        editableWidth.value,
        editableHeight.value,
      );

      // Emit normalized coordinates directly
      emit('fieldUpdated', {
        instanceId: props.selectedField.instanceId,
        updates: {
          normalizedX: normalized.x,
          normalizedY: normalized.y,
          normalizedWidth: normalized.width,
          normalizedHeight: normalized.height,
          ...commonStyleUpdates,
        },
      });
      return;
    }
  }

  // For images, emit pixel coordinates
  emit('fieldUpdated', {
    instanceId: props.selectedField.instanceId,
    updates: {
      x: editableX.value,
      y: editableY.value,
      width: editableWidth.value,
      height: editableHeight.value,
      ...commonStyleUpdates,
    },
  });
}

function saveDefaults() {
  const fieldId = props.selectedField?.id;
  if (fieldId === undefined || fieldId === null) {
    return;
  }

  const autoDateTimeConfig = getAutoDateTimeFormatConfig(localField.value);

  const dateTimeDefaults = isDateField.value
    ? {
        dateSeparator: autoDateTimeConfig.dateSeparator,
        dateSeparatorSpacing: autoDateTimeConfig.dateSeparatorSpacing,
        dateShowDay: autoDateTimeConfig.dateShowDay,
        dateShowMonth: autoDateTimeConfig.dateShowMonth,
        dateShowYear: autoDateTimeConfig.dateShowYear,
        dateShowDayOfWeek: autoDateTimeConfig.dateShowDayOfWeek,
        dateDayOfWeekStyle: autoDateTimeConfig.dateDayOfWeekStyle,
        dateDayOfWeekGap: autoDateTimeConfig.dateDayOfWeekGap,
        dateMonthStyle: autoDateTimeConfig.dateMonthStyle,
        dateCalendar: autoDateTimeConfig.dateCalendar,
      }
    : isTimeField.value
      ? {
          timeSeparator: autoDateTimeConfig.timeSeparator,
          timeSeparatorSpacing: autoDateTimeConfig.timeSeparatorSpacing,
          timeShowHour: autoDateTimeConfig.timeShowHour,
          timeShowMinute: autoDateTimeConfig.timeShowMinute,
        }
      : {};

  emit('saveDefaults', {
    fieldId,
    defaults: {
      width: editableWidth.value,
      height: editableHeight.value,
      font: localField.value.fontFamily || localField.value.font || 'Arial',
      fontSize: normalizeFontSize(localField.value.fontSize),
      fontWeight: localField.value.fontWeight || 'normal',
      fontStyle: localField.value.fontStyle || 'normal',
      textDecoration: localField.value.textDecoration || 'none',
      textAlign: localField.value.textAlign || 'left',
      letterSpacing: isDateField.value || isTimeField.value ? 0 : (localField.value.letterSpacing ?? 0),
      lineHeight: localField.value.lineHeight ?? 1.5,
      maxLength: supportsMaxLength.value ? normalizeMaxLength(localField.value.maxLength) : null,
      strikeThroughGroupMode: isCheckboxType.value ? Boolean(localField.value.strikeThroughGroupMode) : false,
      strikeLineThickness: isCheckboxType.value
        ? Math.min(8, Math.max(0.5, Number.parseFloat(String(localField.value.strikeLineThickness ?? 1.5)) || 1.5))
        : 1.5,
      isAutoGenerated: supportsAutoGenerateToggle.value
        ? Boolean(localField.value.isAutoGenerated)
        : false,
      ...dateTimeDefaults,
    },
  });
}

function toggleDatePart(partKey: 'dateShowDay' | 'dateShowMonth' | 'dateShowYear') {
  const parts: Array<'dateShowDay' | 'dateShowMonth' | 'dateShowYear'> = ['dateShowDay', 'dateShowMonth', 'dateShowYear'];
  const activeCount = parts.filter(key => localField.value[key] !== false).length;
  const isActive = localField.value[partKey] !== false;

  if (isActive && activeCount <= 1) {
    return;
  }

  localField.value[partKey] = !isActive;
  onPropertyChange();
}

function toggleTimePart(partKey: 'timeShowHour' | 'timeShowMinute') {
  const parts: Array<'timeShowHour' | 'timeShowMinute'> = ['timeShowHour', 'timeShowMinute'];
  const activeCount = parts.filter(key => localField.value[key] !== false).length;
  const isActive = localField.value[partKey] !== false;

  if (isActive && activeCount <= 1) {
    return;
  }

  localField.value[partKey] = !isActive;
  onPropertyChange();
}

function removeField() {
  if (!props.selectedField)
    return;
  emit('fieldRemoved', props.selectedField.instanceId);
}

function clampLetterSpacing(value: number): number {
  if (!Number.isFinite(value)) {
    return 0;
  }
  return Math.min(20, Math.max(-5, value));
}

function clampLineHeight(value: number): number {
  if (!Number.isFinite(value)) {
    return 1.5;
  }
  return Math.min(5, Math.max(0.5, Math.round(value * 10) / 10));
}

function onMaxLengthNumberInput(event: Event) {
  const str = String((event.target as HTMLInputElement).value).trim();
  if (!str.length) {
    localField.value.maxLength = null;
    onPropertyChange();
    return;
  }
  const parsed = Number.parseInt(str, 10);
  localField.value.maxLength = normalizeMaxLength(parsed);
  onPropertyChange();
}

function onMaxLengthNumberBlur() {
  localField.value.maxLength = normalizeMaxLength(localField.value.maxLength);
  onPropertyChange();
}

function onLetterSpacingNumberPopoverInput() {
  onPropertyChange();
}

function onLetterSpacingNumberPopoverBlur() {
  localField.value.letterSpacing = clampLetterSpacing(Number(localField.value.letterSpacing) || 0);
  onPropertyChange();
}

function onLineHeightNumberPopoverInput() {
  onPropertyChange();
}

function onLineHeightNumberPopoverBlur() {
  localField.value.lineHeight = clampLineHeight(Number(localField.value.lineHeight) || 1.5);
  onPropertyChange();
}

const FIELD_DIM_MIN = 16;
const FIELD_DIM_MAX = 8000;
const LETTER_SPACING_STEP = 0.5;
const LINE_HEIGHT_STEP = 0.1;
const MAX_LENGTH_STEP = 1;
const FIELD_DIM_STEP = 1;

function bumpLetterSpacing(delta: number) {
  const cur = Number(localField.value.letterSpacing) || 0;
  localField.value.letterSpacing = clampLetterSpacing(cur + delta * LETTER_SPACING_STEP);
  onPropertyChange();
}

function bumpLineHeight(delta: number) {
  const cur = Number(localField.value.lineHeight) || 1.5;
  localField.value.lineHeight = clampLineHeight(cur + delta * LINE_HEIGHT_STEP);
  onPropertyChange();
}

function bumpMaxLength(delta: number) {
  const cur = normalizeMaxLength(localField.value.maxLength);
  if (delta < 0) {
    if (cur === null) {
      return;
    }
    if (cur <= 1) {
      localField.value.maxLength = null;
    }
    else {
      localField.value.maxLength = cur - MAX_LENGTH_STEP;
    }
  }
  else {
    const next = cur === null || cur < 1 ? 1 : cur + MAX_LENGTH_STEP;
    localField.value.maxLength = Math.min(5000, next);
  }
  onPropertyChange();
}

function clampEditableWidth(value: number): number {
  if (!Number.isFinite(value)) {
    return FIELD_DIM_MIN;
  }
  return Math.min(FIELD_DIM_MAX, Math.max(FIELD_DIM_MIN, Math.round(value)));
}

function clampEditableHeight(value: number): number {
  return clampEditableWidth(value);
}

function bumpFieldWidth(delta: number) {
  editableWidth.value = clampEditableWidth(editableWidth.value + delta * FIELD_DIM_STEP);
  onPropertyChange();
}

function bumpFieldHeight(delta: number) {
  editableHeight.value = clampEditableHeight(editableHeight.value + delta * FIELD_DIM_STEP);
  onPropertyChange();
}

function onFieldWidthPopoverBlur() {
  editableWidth.value = clampEditableWidth(Number(editableWidth.value));
  onPropertyChange();
}

function onFieldHeightPopoverBlur() {
  editableHeight.value = clampEditableHeight(Number(editableHeight.value));
  onPropertyChange();
}

function onFieldWidthPopoverInput() {
  onPropertyChange();
}

function onFieldHeightPopoverInput() {
  onPropertyChange();
}
</script>

<template>
  <div class="field-toolbar-wrapper bg-white shadow-sm border border-gray-200 rounded-lg px-3 py-1.5 mx-auto">
    <div class="field-toolbar-inline">
      <!-- Font (text fields only) -->
      <template v-if="selectedFieldType !== 'icon' && selectedFieldType !== 'signature' && selectedFieldType !== 'checkbox'">
        <div class="h-5 w-px bg-gray-200" />
        <div class="flex items-center gap-1.5">
          <UTooltip text="ขนาดตัวอักษร" :popper="{ placement: 'top' }">
            <div class="toolbar-input-group">
              <span class="toolbar-prefix text-gray-400">
                <UIcon name="i-lucide-type" class="w-3.5 h-3.5" />
              </span>
              <input
                v-model="fontSizeInput"
                type="number"
                class="toolbar-input w-10"
                min="8"
                max="72"
                placeholder="14"
                @input="handleFontSizeInput"
                @blur="handleFontSizeBlur"
              >

              <UDropdownMenu
                :items="fontSizeDropdownItems"
                :content="{
                  align: 'end',
                  side: 'bottom',
                }"
                :ui="{
                  content: 'min-w-15 w-15',
                }"
              >
                <button
                  type="button"
                  class="font-size-dropdown-trigger"
                  aria-label="เลือกขนาดตัวอักษร"
                >
                  <UIcon name="i-lucide-chevron-down" class="w-3.5 h-3.5" />
                </button>
              </UDropdownMenu>
            </div>
          </UTooltip>

          <UTooltip text="รูปแบบฟอนต์" :popper="{ placement: 'top' }">
            <select
              v-model="localField.fontFamily"
              class="toolbar-select"
              @change="onPropertyChange"
            >
              <option value="Sarabun">
                Sarabun (สารบรรณ)
              </option>
            </select>
          </UTooltip>

          <div class="h-5 w-px bg-gray-200" />

          <!-- Bold / Italic / Underline -->
          <div class="flex items-center gap-0.5">
            <UTooltip text="ตัวหนา (Bold)" :popper="{ placement: 'top' }">
              <button
                class="toolbar-fmt-btn"
                :class="{ active: localField.fontWeight === 'bold' }"
                @click="localField.fontWeight = localField.fontWeight === 'bold' ? 'normal' : 'bold'; onPropertyChange()"
              >
                <strong>B</strong>
              </button>
            </UTooltip>
            <UTooltip text="ตัวเอียง (Italic)" :popper="{ placement: 'top' }">
              <button
                class="toolbar-fmt-btn"
                :class="{ active: localField.fontStyle === 'italic' }"
                @click="localField.fontStyle = localField.fontStyle === 'italic' ? 'normal' : 'italic'; onPropertyChange()"
              >
                <em>I</em>
              </button>
            </UTooltip>
            <UTooltip text="ขีดเส้นใต้ (Underline)" :popper="{ placement: 'top' }">
              <button
                class="toolbar-fmt-btn"
                :class="{ active: localField.textDecoration === 'underline' }"
                @click="localField.textDecoration = localField.textDecoration === 'underline' ? 'none' : 'underline'; onPropertyChange()"
              >
                <span style="text-decoration: underline;">U</span>
              </button>
            </UTooltip>
          </div>

          <div class="h-5 w-px bg-gray-200" />

          <!-- Text alignment -->
          <div class="flex items-center gap-0.5">
            <UTooltip text="ชิดซ้าย" :popper="{ placement: 'top' }">
              <button
                class="toolbar-fmt-btn"
                :class="{ active: !localField.textAlign || localField.textAlign === 'left' }"
                @click="localField.textAlign = 'left'; onPropertyChange()"
              >
                <UIcon name="i-heroicons-bars-3-bottom-left" class="w-3.5 h-3.5" />
              </button>
            </UTooltip>
            <UTooltip text="กึ่งกลาง" :popper="{ placement: 'top' }">
              <button
                class="toolbar-fmt-btn"
                :class="{ active: localField.textAlign === 'center' }"
                @click="localField.textAlign = 'center'; onPropertyChange()"
              >
                <UIcon name="i-heroicons-bars-3" class="w-3.5 h-3.5" />
              </button>
            </UTooltip>
            <UTooltip text="ชิดขวา" :popper="{ placement: 'top' }">
              <button
                class="toolbar-fmt-btn"
                :class="{ active: localField.textAlign === 'right' }"
                @click="localField.textAlign = 'right'; onPropertyChange()"
              >
                <UIcon name="i-heroicons-bars-3-bottom-right" class="w-3.5 h-3.5" />
              </button>
            </UTooltip>
          </div>

          <div class="h-5 w-px bg-gray-200" />

          <!-- Spacing & limits: popover with numeric inputs only -->
          <UPopover
            :content="{ align: 'center', side: 'bottom', sideOffset: 6 }"
            :ui="{ content: 'w-fit min-w-0 max-w-[min(100vw,18rem)] p-0 overflow-visible' }"
          >
            <template #default="{ open }">
              <UTooltip
                text="การตั้งค่าขั้นสูง — ระยะห่างตัวอักษร ความสูงบรรทัด จำนวนตัวอักษรสูงสุด"
                :popper="{ placement: 'top' }"
              >
                <button
                  type="button"
                  class="toolbar-fmt-btn spacing-popover-trigger"
                  :class="{ active: open }"
                  aria-haspopup="dialog"
                  :aria-expanded="open"
                  aria-label="การตั้งค่าระยะห่างและขีดจำกัดข้อความ"
                >
                  <span class="spacing-trigger-icon" aria-hidden="true">
                    <span class="spacing-trigger-t">T</span>
                    <UIcon name="i-lucide-arrow-up-down" class="w-3 h-3 opacity-85" />
                  </span>
                </button>
              </UTooltip>
            </template>

            <template #content>
              <div class="spacing-popover-panel">
                <template v-if="!isDateField && !isTimeField">
                  <div class="spacing-popover-section">
                    <label class="spacing-popover-label">ระยะห่างระหว่างตัวอักษร</label>
                    <div class="spacing-popover-stepper">
                      <button
                        type="button"
                        class="spacing-stepper-btn"
                        aria-label="ลดระยะห่างตัวอักษร"
                        :disabled="Number(localField.letterSpacing) <= -5"
                        @click="bumpLetterSpacing(-1)"
                      >
                        −
                      </button>
                      <input
                        v-model.number="localField.letterSpacing"
                        type="number"
                        class="spacing-popover-input-compact"
                        min="-5"
                        max="20"
                        step="0.5"
                        placeholder="0"
                        @input="onLetterSpacingNumberPopoverInput"
                        @blur="onLetterSpacingNumberPopoverBlur"
                      >
                      <button
                        type="button"
                        class="spacing-stepper-btn"
                        aria-label="เพิ่มระยะห่างตัวอักษร"
                        :disabled="Number(localField.letterSpacing) >= 20"
                        @click="bumpLetterSpacing(1)"
                      >
                        +
                      </button>
                    </div>
                  </div>
                </template>

                <div class="spacing-popover-section">
                  <label class="spacing-popover-label">ระยะห่างระหว่างบรรทัด</label>
                  <div class="spacing-popover-stepper">
                    <button
                      type="button"
                      class="spacing-stepper-btn"
                      aria-label="ลดระยะห่างบรรทัด"
                      :disabled="Number(localField.lineHeight) <= 0.5"
                      @click="bumpLineHeight(-1)"
                    >
                      −
                    </button>
                    <input
                      v-model.number="localField.lineHeight"
                      type="number"
                      class="spacing-popover-input-compact"
                      min="0.5"
                      max="5"
                      step="0.1"
                      placeholder="1.5"
                      @input="onLineHeightNumberPopoverInput"
                      @blur="onLineHeightNumberPopoverBlur"
                    >
                    <button
                      type="button"
                      class="spacing-stepper-btn"
                      aria-label="เพิ่มระยะห่างบรรทัด"
                      :disabled="Number(localField.lineHeight) >= 5"
                      @click="bumpLineHeight(1)"
                    >
                      +
                    </button>
                  </div>
                </div>

                <template v-if="supportsMaxLength">
                  <div class="spacing-popover-divider" />
                  <div class="spacing-popover-section">
                    <label class="spacing-popover-label">จำนวนตัวอักษรสูงสุด</label>
                    <p class="spacing-popover-hint">
                      ใส่ 0 หรือเว้นว่าง = ไม่จำกัด
                    </p>
                    <div class="spacing-popover-stepper">
                      <button
                        type="button"
                        class="spacing-stepper-btn"
                        aria-label="ลดจำนวนตัวอักษรสูงสุด"
                        :disabled="localField.maxLength === null || localField.maxLength === undefined || Number(localField.maxLength) <= 0"
                        @click="bumpMaxLength(-1)"
                      >
                        −
                      </button>
                      <input
                        type="number"
                        class="spacing-popover-input-compact"
                        min="0"
                        max="5000"
                        step="1"
                        :value="localField.maxLength ?? ''"
                        placeholder="∞"
                        @input="onMaxLengthNumberInput"
                        @blur="onMaxLengthNumberBlur"
                      >
                      <button
                        type="button"
                        class="spacing-stepper-btn"
                        aria-label="เพิ่มจำนวนตัวอักษรสูงสุด"
                        :disabled="Number(localField.maxLength) >= 5000"
                        @click="bumpMaxLength(1)"
                      >
                        +
                      </button>
                    </div>
                  </div>
                </template>
              </div>
            </template>
          </UPopover>

          <template v-if="isDateField">
            <div class="h-5 w-px bg-gray-200" />

            <UPopover
              :content="{ align: 'center', side: 'bottom', sideOffset: 6 }"
              :ui="{ content: 'w-fit min-w-0 max-w-[min(100vw,22rem)] p-0 overflow-visible' }"
            >
              <template #default="{ open }">
                <UTooltip text="รูปแบบวันที่" :popper="{ placement: 'top' }">
                  <button
                    type="button"
                    class="toolbar-fmt-btn"
                    :class="{ active: open }"
                    aria-haspopup="dialog"
                    :aria-expanded="open"
                    aria-label="ตั้งค่ารูปแบบวันที่"
                  >
                    <UIcon name="i-heroicons-calendar-days" class="w-3.5 h-3.5" />
                  </button>
                </UTooltip>
              </template>

              <template #content>
                <div class="spacing-popover-panel date-format-panel">
                  <!-- Preview -->
                  <div class="spacing-popover-section">
                    <label class="spacing-popover-label">ตัวอย่าง</label>
                    <p class="date-format-preview">
                      {{ dateFormatPreview }}
                    </p>
                  </div>

                  <div class="spacing-popover-divider" />

                  <!-- Show parts: วัน เดือน ปี -->
                  <div class="spacing-popover-section">
                    <label class="spacing-popover-label">แสดงส่วนของวันที่</label>
                    <div class="date-fmt-toggle-row">
                      <button
                        type="button"
                        class="date-fmt-part-btn"
                        :class="{ active: localField.dateShowDay !== false }"
                        @click="toggleDatePart('dateShowDay')"
                      >
                        วัน
                      </button>
                      <button
                        type="button"
                        class="date-fmt-part-btn"
                        :class="{ active: localField.dateShowMonth !== false }"
                        @click="toggleDatePart('dateShowMonth')"
                      >
                        เดือน
                      </button>
                      <button
                        type="button"
                        class="date-fmt-part-btn"
                        :class="{ active: localField.dateShowYear !== false }"
                        @click="toggleDatePart('dateShowYear')"
                      >
                        ปี
                      </button>
                    </div>
                  </div>

                  <div class="spacing-popover-divider" />

                  <!-- Day of week -->
                  <div class="spacing-popover-section">
                    <label class="spacing-popover-label">ชื่อวัน</label>
                    <label class="date-fmt-checkbox-row">
                      <input
                        v-model="localField.dateShowDayOfWeek"
                        type="checkbox"
                        @change="onPropertyChange"
                      >
                      แสดงชื่อวัน
                    </label>
                    <template v-if="localField.dateShowDayOfWeek">
                      <div class="date-fmt-toggle-row" style="margin-top: 0.35rem;">
                        <button
                          type="button"
                          class="date-fmt-part-btn"
                          :class="{ active: !localField.dateDayOfWeekStyle || localField.dateDayOfWeekStyle === 'long' }"
                          @click="localField.dateDayOfWeekStyle = 'long'; onPropertyChange()"
                        >
                          เต็ม
                        </button>
                        <button
                          type="button"
                          class="date-fmt-part-btn"
                          :class="{ active: localField.dateDayOfWeekStyle === 'short' }"
                          @click="localField.dateDayOfWeekStyle = 'short'; onPropertyChange()"
                        >
                          ย่อ
                        </button>
                        <span class="date-fmt-row-label">gap</span>
                        <div class="spacing-popover-stepper">
                          <button
                            type="button"
                            class="spacing-stepper-btn"
                            aria-label="ลด gap ชื่อวัน"
                            :disabled="Number(localField.dateDayOfWeekGap) <= 0"
                            @click="localField.dateDayOfWeekGap = Math.max(0, Number(localField.dateDayOfWeekGap) - 1); onPropertyChange()"
                          >
                            −
                          </button>
                          <input
                            v-model.number="localField.dateDayOfWeekGap"
                            type="number"
                            class="spacing-popover-input-compact"
                            style="width: 2rem; min-width: 2rem;"
                            min="0"
                            max="10"
                            step="1"
                            placeholder="1"
                            @input="onPropertyChange"
                          >
                          <button
                            type="button"
                            class="spacing-stepper-btn"
                            aria-label="เพิ่ม gap ชื่อวัน"
                            :disabled="Number(localField.dateDayOfWeekGap) >= 10"
                            @click="localField.dateDayOfWeekGap = Math.min(10, Number(localField.dateDayOfWeekGap) + 1); onPropertyChange()"
                          >
                            +
                          </button>
                        </div>
                      </div>
                      <p class="spacing-popover-hint">
                        เต็ม = วันเสาร์ · ย่อ = ส.
                      </p>
                    </template>
                  </div>

                  <div class="spacing-popover-divider" />

                  <!-- Month style -->
                  <div class="spacing-popover-section">
                    <label class="spacing-popover-label">รูปแบบเดือน</label>
                    <div class="date-fmt-toggle-row">
                      <button
                        type="button"
                        class="date-fmt-part-btn"
                        :class="{ active: !localField.dateMonthStyle || localField.dateMonthStyle === 'numeric' }"
                        @click="localField.dateMonthStyle = 'numeric'; onPropertyChange()"
                      >
                        เลข
                      </button>
                      <button
                        type="button"
                        class="date-fmt-part-btn"
                        :class="{ active: localField.dateMonthStyle === 'short' }"
                        @click="localField.dateMonthStyle = 'short'; onPropertyChange()"
                      >
                        ย่อ
                      </button>
                      <button
                        type="button"
                        class="date-fmt-part-btn"
                        :class="{ active: localField.dateMonthStyle === 'long' }"
                        @click="localField.dateMonthStyle = 'long'; onPropertyChange()"
                      >
                        เต็ม
                      </button>
                    </div>
                    <p class="spacing-popover-hint">
                      เลข = 09 · ย่อ = ก.ย. · เต็ม = กันยายน
                    </p>
                  </div>

                  <div class="spacing-popover-divider" />

                  <!-- Year calendar: ค.ศ. / พ.ศ. -->
                  <div class="spacing-popover-section">
                    <label class="spacing-popover-label">รูปแบบปี</label>
                    <div class="date-fmt-toggle-row">
                      <button
                        type="button"
                        class="date-fmt-part-btn"
                        :class="{ active: !localField.dateCalendar || localField.dateCalendar === 'ad' }"
                        @click="localField.dateCalendar = 'ad'; onPropertyChange()"
                      >
                        ค.ศ.
                      </button>
                      <button
                        type="button"
                        class="date-fmt-part-btn"
                        :class="{ active: localField.dateCalendar === 'be' }"
                        @click="localField.dateCalendar = 'be'; onPropertyChange()"
                      >
                        พ.ศ.
                      </button>
                    </div>
                  </div>

                  <div class="spacing-popover-divider" />

                  <!-- Separator + spacing -->
                  <div class="spacing-popover-section">
                    <label class="spacing-popover-label">ตัวคั่น &amp; ระยะห่าง</label>
                    <div class="date-fmt-row">
                      <div class="toolbar-input-group">
                        <span class="toolbar-prefix">/</span>
                        <input
                          v-model="localField.dateSeparator"
                          type="text"
                          class="toolbar-input w-10"
                          maxlength="3"
                          placeholder="/"
                          @input="onPropertyChange"
                        >
                      </div>
                      <span class="date-fmt-row-label">gap</span>
                      <div class="spacing-popover-stepper">
                        <button
                          type="button"
                          class="spacing-stepper-btn"
                          aria-label="ลด gap ตัวคั่น"
                          :disabled="Number(localField.dateSeparatorSpacing) <= 0"
                          @click="localField.dateSeparatorSpacing = Math.max(0, Number(localField.dateSeparatorSpacing) - 1); onPropertyChange()"
                        >
                          −
                        </button>
                        <input
                          v-model.number="localField.dateSeparatorSpacing"
                          type="number"
                          class="spacing-popover-input-compact"
                          style="width: 2rem; min-width: 2rem;"
                          min="0"
                          step="1"
                          placeholder="0"
                          @input="onPropertyChange"
                        >
                        <button
                          type="button"
                          class="spacing-stepper-btn"
                          aria-label="เพิ่ม gap ตัวคั่น"
                          :disabled="Number(localField.dateSeparatorSpacing) >= 10"
                          @click="localField.dateSeparatorSpacing = Math.min(10, Number(localField.dateSeparatorSpacing) + 1); onPropertyChange()"
                        >
                          +
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </template>
            </UPopover>
          </template>

          <template v-if="isTimeField">
            <div class="h-5 w-px bg-gray-200" />

            <UTooltip text="ตัวคั่นเวลา (เว้นว่าง = ไม่คั่น)" :popper="{ placement: 'top' }">
              <div class="toolbar-input-group">
                <span class="toolbar-prefix">:</span>
                <input
                  v-model="localField.timeSeparator"
                  type="text"
                  class="toolbar-input w-10"
                  maxlength="3"
                  placeholder=":"
                  @input="onPropertyChange"
                >
              </div>
            </UTooltip>

            <UTooltip text="ระยะห่างตัวคั่นเวลา" :popper="{ placement: 'top' }">
              <div class="toolbar-input-group">
                <span class="toolbar-prefix">gap</span>
                <input
                  v-model.number="localField.timeSeparatorSpacing"
                  type="number"
                  class="toolbar-input w-10"
                  min="0"
                  step="1"
                  placeholder="0"
                  @input="onPropertyChange"
                >
              </div>
            </UTooltip>

            <div class="flex items-center gap-0.5">
              <UTooltip text="แสดงชั่วโมง" :popper="{ placement: 'top' }">
                <button
                  class="toolbar-fmt-btn"
                  :class="{ active: localField.timeShowHour !== false }"
                  @click="toggleTimePart('timeShowHour')"
                >
                  H
                </button>
              </UTooltip>
              <UTooltip text="แสดงนาที" :popper="{ placement: 'top' }">
                <button
                  class="toolbar-fmt-btn"
                  :class="{ active: localField.timeShowMinute !== false }"
                  @click="toggleTimePart('timeShowMinute')"
                >
                  M
                </button>
              </UTooltip>
            </div>
          </template>

          <template v-if="supportsAutoGenerateToggle">
            <div class="h-5 w-px bg-gray-200" />
            <UTooltip text="ใส่ข้อมูลอัตโนมัติ" :popper="{ placement: 'top' }">
              <button
                class="toolbar-fmt-btn"
                :class="{ active: localField.isAutoGenerated }"
                @click="localField.isAutoGenerated = !localField.isAutoGenerated; onPropertyChange()"
              >
                <UIcon name="i-heroicons-bolt" class="w-3.5 h-3.5" />
              </button>
            </UTooltip>
          </template>
        </div>
      </template>

      <template v-if="isCheckboxType">
        <div class="h-5 w-px bg-gray-200" />
        <label class="toolbar-inline-checkbox">
          <input
            v-model="localField.strikeThroughGroupMode"
            type="checkbox"
            @change="onPropertyChange"
          >
          โหมดขีดฆ่าช่องที่ไม่ติ๊กในกลุ่ม
        </label>
      </template>

      <template v-if="isCheckboxType && localField.strikeThroughGroupMode">
        <UTooltip text="ความหนาเส้นขีดฆ่า (ใช้เมื่อเปิดโหมดขีดฆ่า)" :popper="{ placement: 'top' }">
          <div class="toolbar-input-group">
            <span class="toolbar-prefix text-gray-400">
              <UIcon name="i-heroicons-minus-small" class="w-3.5 h-3.5" />
            </span>
            <input
              v-model.number="localField.strikeLineThickness"
              type="number"
              class="toolbar-input w-12"
              min="0.5"
              max="8"
              step="0.1"
              @input="onPropertyChange"
            >
          </div>
        </UTooltip>
      </template>

      <div class="h-5 w-px bg-gray-200" />

      <!-- Field width × height (all field types) -->
      <UPopover
        :content="{ align: 'center', side: 'bottom', sideOffset: 6 }"
        :ui="{ content: 'w-fit min-w-0 max-w-[min(100vw,18rem)] p-0 overflow-visible' }"
      >
        <template #default="{ open }">
          <UTooltip text="ขนาดช่อง — ความกว้าง × ความสูง (พิกเซล)" :popper="{ placement: 'top' }">
            <button
              type="button"
              class="toolbar-fmt-btn"
              :class="{ active: open }"
              aria-haspopup="dialog"
              :aria-expanded="open"
              aria-label="ปรับความกว้างและความสูงของช่อง"
            >
              <UIcon name="i-heroicons-arrows-pointing-out" class="w-3.5 h-3.5" />
            </button>
          </UTooltip>
        </template>
        <template #content>
          <div class="spacing-popover-panel">
            <div class="spacing-popover-section">
              <label class="spacing-popover-label">ความกว้าง (px)</label>
              <div class="spacing-popover-stepper">
                <button
                  type="button"
                  class="spacing-stepper-btn"
                  aria-label="ลดความกว้าง"
                  :disabled="editableWidth <= FIELD_DIM_MIN"
                  @click="bumpFieldWidth(-1)"
                >
                  −
                </button>
                <input
                  v-model.number="editableWidth"
                  type="number"
                  class="spacing-popover-input-compact"
                  :min="FIELD_DIM_MIN"
                  :max="FIELD_DIM_MAX"
                  step="1"
                  @input="onFieldWidthPopoverInput"
                  @blur="onFieldWidthPopoverBlur"
                >
                <button
                  type="button"
                  class="spacing-stepper-btn"
                  aria-label="เพิ่มความกว้าง"
                  :disabled="editableWidth >= FIELD_DIM_MAX"
                  @click="bumpFieldWidth(1)"
                >
                  +
                </button>
              </div>
            </div>
            <div class="spacing-popover-section">
              <label class="spacing-popover-label">ความสูง (px)</label>
              <div class="spacing-popover-stepper">
                <button
                  type="button"
                  class="spacing-stepper-btn"
                  aria-label="ลดความสูง"
                  :disabled="editableHeight <= FIELD_DIM_MIN"
                  @click="bumpFieldHeight(-1)"
                >
                  −
                </button>
                <input
                  v-model.number="editableHeight"
                  type="number"
                  class="spacing-popover-input-compact"
                  :min="FIELD_DIM_MIN"
                  :max="FIELD_DIM_MAX"
                  step="1"
                  @input="onFieldHeightPopoverInput"
                  @blur="onFieldHeightPopoverBlur"
                >
                <button
                  type="button"
                  class="spacing-stepper-btn"
                  aria-label="เพิ่มความสูง"
                  :disabled="editableHeight >= FIELD_DIM_MAX"
                  @click="bumpFieldHeight(1)"
                >
                  +
                </button>
              </div>
            </div>
          </div>
        </template>
      </UPopover>

      <div class="h-5 w-px bg-gray-200" />

      <!-- Conditional visibility toggle (details shown in second row) -->
      <UTooltip text="แสดงช่องนี้ตามเงื่อนไขจาก Checkbox" :popper="{ placement: 'top' }">
        <button
          class="toolbar-fmt-btn"
          :class="{ active: localField.conditionalEnabled }"
          @click="toggleConditionalVisibility"
        >
          <UIcon name="i-heroicons-adjustments-horizontal" class="w-3.5 h-3.5" />
        </button>
      </UTooltip>

      <div class="h-5 w-px bg-gray-200" />

      <!-- Save as default -->
      <UTooltip text="บันทึกค่าช่องนี้เป็นค่าเริ่มต้นของ Field" :popper="{ placement: 'top' }">
        <button
          class="flex items-center justify-center w-7 h-7 text-gray-400 hover:text-primary-600 hover:bg-primary-50 rounded-md transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          :disabled="!selectedField?.id || isSavingDefaults"
          @click="saveDefaults"
        >
          <UIcon :name="isSavingDefaults ? 'i-heroicons-arrow-path' : 'i-heroicons-bookmark-square'" class="w-4 h-4" :class="{ 'animate-spin': isSavingDefaults }" />
        </button>
      </UTooltip>

      <div class="h-5 w-px bg-gray-200" />

      <!-- Delete -->
      <UTooltip text="ลบช่องข้อมูลนี้" :popper="{ placement: 'top' }">
        <button
          class="flex items-center justify-center w-7 h-7 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-md transition-colors"
          @click="removeField"
        >
          <UIcon name="i-heroicons-trash-20-solid" class="w-4 h-4" />
        </button>
      </UTooltip>
    </div>

    <div v-if="localField.conditionalEnabled" class="conditional-toolbar-row">
      <div class="conditional-toolbar-inline">
        <span class="conditional-toolbar-label">
          <UIcon name="i-heroicons-funnel" class="w-3.5 h-3.5" />
          เงื่อนไขการแสดงผลจาก Checkbox
        </span>

        <select
          v-model="localField.conditionalSourceType"
          class="toolbar-select conditional-select"
          @change="onPropertyChange"
        >
          <option value="single">
            Checkbox เดี่ยว
          </option>
          <option value="group">
            Checkbox Group
          </option>
        </select>

        <select
          v-if="localField.conditionalSourceType !== 'group'"
          v-model="localField.conditionalSourceFieldInstanceId"
          class="toolbar-select conditional-select"
          @change="onPropertyChange"
        >
          <option value="" disabled>
            เลือก Checkbox
          </option>
          <option
            v-for="option in conditionalSourceOptions"
            :key="option.value"
            :value="option.value"
          >
            {{ option.label }}
          </option>
        </select>

        <select
          v-else
          v-model="localField.conditionalSourceGroupId"
          class="toolbar-select conditional-select"
          @change="onPropertyChange"
        >
          <option value="" disabled>
            เลือก Checkbox Group
          </option>
          <option
            v-for="option in conditionalGroupSourceOptions"
            :key="option.value"
            :value="option.value"
          >
            {{ option.label }}
          </option>
        </select>

        <select
          v-model="localField.conditionalOperator"
          class="toolbar-select conditional-select"
          @change="onPropertyChange"
        >
          <option value="isChecked">
            ติ๊กแล้ว
          </option>
          <option value="isUnchecked">
            ไม่ติ๊ก
          </option>
        </select>
      </div>
    </div>
  </div>
</template>

<style scoped>
.field-toolbar-wrapper {
  display: inline-flex;
  flex-direction: column;
  align-items: stretch;
  gap: 0.5rem;
  max-width: 100%;
  box-shadow:
    0 2px 8px -2px rgba(0, 0, 0, 0.05),
    0 4px 16px -4px rgba(0, 0, 0, 0.02);
}

.field-toolbar-inline {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  max-width: 100%;
  overflow-x: auto;
  overflow-y: hidden;
  scrollbar-width: thin;
  -webkit-user-select: none;
  user-select: none;
}

.conditional-toolbar-row {
  border-top: 1px dashed #e5e7eb;
  padding-top: 0.5rem;
}

.conditional-toolbar-inline {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 0.5rem;
}

.conditional-toolbar-label {
  display: inline-flex;
  align-items: center;
  gap: 0.25rem;
  font-size: 0.72rem;
  font-weight: 600;
  color: #92400e;
  background: #fffbeb;
  border: 1px solid #fcd34d;
  border-radius: 9999px;
  padding: 0.2rem 0.5rem;
  white-space: nowrap;
}

.conditional-select {
  max-width: 16rem;
}

/* Figma-style Input Group */
.toolbar-input-group {
  display: flex;
  align-items: center;
  background-color: #ffffff;
  border: 1px solid #e5e7eb;
  border-radius: 6px;
  overflow: hidden;
  transition: all 0.15s ease-in-out;
}

.toolbar-input-group:focus-within {
  border-color: #3b82f6;
  box-shadow: 0 0 0 1px #3b82f6;
}

.toolbar-prefix {
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #f9fafb;
  color: #6b7280;
  font-size: 0.65rem;
  font-weight: 600;
  padding: 0 6px;
  height: 26px;
  border-right: 1px solid #e5e7eb;
}

.toolbar-input {
  width: 2.75rem;
  height: 26px;
  padding: 0 4px;
  font-size: 0.75rem;
  text-align: center;
  color: #374151;
  border: none;
  background: transparent;
  outline: none;
  -webkit-user-select: text;
  user-select: text;
}

.toolbar-input:focus {
  outline: none;
}

.font-size-dropdown-trigger {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 20px;
  height: 26px;
  padding: 0;
  border: none;
  border-left: 1px solid #e5e7eb;
  background-color: #f9fafb;
  color: #6b7280;
  cursor: pointer;
  transition: all 0.15s ease-in-out;
  flex-shrink: 0;
}

.font-size-dropdown-trigger:hover {
  background-color: #f3f4f6;
  color: #374151;
}

.font-size-dropdown-trigger:focus {
  outline: none;
}

.toolbar-select {
  height: 26px;
  padding: 0 24px 0 8px;
  font-size: 0.75rem;
  color: #374151;
  background-color: #ffffff;
  border: 1px solid #e5e7eb;
  border-radius: 6px;
  max-width: 9rem;
  -webkit-user-select: text;
  user-select: text;
  transition: all 0.15s ease-in-out;
  cursor: pointer;
}

.toolbar-select:focus {
  outline: none;
  border-color: #3b82f6;
  box-shadow: 0 0 0 1px #3b82f6;
}

.toolbar-inline-checkbox {
  display: flex;
  align-items: center;
  gap: 0.25rem;
  font-size: 0.7rem;
  font-weight: 500;
  color: #6b7280;
  white-space: nowrap;
}

.toolbar-inline-checkbox input {
  width: 0.75rem;
  height: 0.75rem;
  accent-color: #3b82f6;
}

/* Hide number spin buttons completely */
.toolbar-input::-webkit-inner-spin-button,
.toolbar-input::-webkit-outer-spin-button {
  -webkit-appearance: none;
  appearance: none;
  margin: 0;
}
.toolbar-input[type='number'] {
  -moz-appearance: textfield;
  appearance: textfield;
}

/* Format toggle buttons (Bold / Italic / Underline / Alignment) */
.toolbar-fmt-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 26px;
  height: 26px;
  border-radius: 6px;
  font-size: 0.78rem;
  color: #6b7280;
  border: 1px solid transparent;
  background: transparent;
  cursor: pointer;
  transition: all 0.15s ease-in-out;
  padding: 0;
  line-height: 1;
}

.toolbar-fmt-btn:hover {
  background-color: #f3f4f6;
  border-color: #e5e7eb;
  color: #374151;
}

.toolbar-fmt-btn.active {
  background-color: #eff6ff;
  border-color: #bfdbfe;
  color: #1d4ed8;
}

/* Spacing / limits popover — tight to content */
.spacing-popover-panel {
  box-sizing: border-box;
  width: max-content;
  max-width: min(18rem, calc(100vw - 1.5rem));
  padding: 0.35rem 0.45rem 0.4rem;
  border-radius: 10px;
  background: #fff;
  box-shadow:
    0 4px 6px -1px rgba(0, 0, 0, 0.06),
    0 12px 28px -8px rgba(0, 0, 0, 0.14);
}

.spacing-popover-section {
  margin-bottom: 0.35rem;
}

.spacing-popover-section:last-child {
  margin-bottom: 0;
}

.spacing-popover-label {
  display: block;
  font-size: 0.68rem;
  font-weight: 600;
  color: #4b5563;
  margin-bottom: 0.15rem;
  line-height: 1.2;
  letter-spacing: 0.02em;
}

.spacing-popover-hint {
  font-size: 0.6rem;
  color: #9ca3af;
  margin: 0 0 0.2rem;
  line-height: 1.25;
}

.spacing-popover-divider {
  height: 1px;
  background: #e5e7eb;
  margin: 0.2rem 0 0.35rem;
}

.spacing-popover-stepper {
  display: inline-flex;
  align-items: stretch;
  max-width: 100%;
  border: 1px solid #e5e7eb;
  border-radius: 6px;
  overflow: hidden;
  background: #fafafa;
}

.spacing-stepper-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 24px;
  flex-shrink: 0;
  padding: 0;
  border: none;
  background: #f3f4f6;
  color: #4b5563;
  font-size: 0.95rem;
  font-weight: 500;
  line-height: 1;
  cursor: pointer;
  transition:
    background 0.12s ease,
    color 0.12s ease;
}

.spacing-stepper-btn:hover:not(:disabled) {
  background: #e5e7eb;
  color: #111827;
}

.spacing-stepper-btn:disabled {
  opacity: 0.35;
  cursor: not-allowed;
}

.spacing-popover-input-compact {
  box-sizing: border-box;
  width: 3.5rem;
  min-width: 3rem;
  max-width: 4.25rem;
  height: 26px;
  padding: 0 2px;
  font-size: 0.78rem;
  font-variant-numeric: tabular-nums;
  text-align: center;
  border: none;
  border-left: 1px solid #e5e7eb;
  border-right: 1px solid #e5e7eb;
  background: #fff;
  color: #374151;
}

.spacing-popover-input-compact:focus {
  outline: none;
  background: #fafafa;
  box-shadow: inset 0 0 0 1px #a5b4fc;
}

.spacing-popover-input-compact::-webkit-inner-spin-button,
.spacing-popover-input-compact::-webkit-outer-spin-button {
  -webkit-appearance: none;
  appearance: none;
  margin: 0;
}

.spacing-popover-input-compact[type='number'] {
  -moz-appearance: textfield;
  appearance: textfield;
}

.spacing-trigger-icon {
  display: inline-flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  line-height: 1;
  gap: 0;
}

.spacing-trigger-t {
  font-size: 0.65rem;
  font-weight: 800;
  letter-spacing: -0.03em;
  line-height: 1;
}

/* Date format popover */
.date-format-panel {
  max-width: min(22rem, calc(100vw - 1.5rem));
}

.date-format-preview {
  display: inline-block;
  font-size: 0.82rem;
  font-weight: 600;
  color: #1d4ed8;
  background: #eff6ff;
  border: 1px solid #bfdbfe;
  border-radius: 6px;
  padding: 0.2rem 0.5rem;
  margin: 0;
  min-width: 4rem;
}

.date-fmt-toggle-row {
  display: flex;
  align-items: center;
  gap: 0.25rem;
  flex-wrap: wrap;
}

.date-fmt-part-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  height: 24px;
  padding: 0 0.5rem;
  border-radius: 5px;
  font-size: 0.7rem;
  font-weight: 600;
  color: #6b7280;
  border: 1px solid #e5e7eb;
  background: #f9fafb;
  cursor: pointer;
  transition: all 0.12s ease;
  white-space: nowrap;
}

.date-fmt-part-btn:hover {
  background: #f3f4f6;
  border-color: #d1d5db;
  color: #374151;
}

.date-fmt-part-btn.active {
  background: #eff6ff;
  border-color: #bfdbfe;
  color: #1d4ed8;
}

.date-fmt-row {
  display: flex;
  align-items: center;
  gap: 0.4rem;
  flex-wrap: wrap;
}

.date-fmt-row-label {
  font-size: 0.65rem;
  font-weight: 600;
  color: #9ca3af;
}

.date-fmt-checkbox-row {
  display: inline-flex;
  align-items: center;
  gap: 0.35rem;
  font-size: 0.72rem;
  font-weight: 500;
  color: #374151;
  cursor: pointer;
}

.date-fmt-checkbox-row input[type='checkbox'] {
  width: 0.8rem;
  height: 0.8rem;
  accent-color: #3b82f6;
  cursor: pointer;
}
</style>
