import db from '~~/lib/db';
import { isActiveDelegateForRequest } from '~~/lib/db/queries/dean-delegation';
import { request, requestTemplate, requestTemplateValues, roles, signatureFlow, userRoles } from '~~/lib/db/schema';
import { and, asc, eq, isNull, sql } from 'drizzle-orm';

export default defineEventHandler(async (event) => {
  // await requirePermission(event, '<permission>', '<permission>', ...);

  try {
    const requestId = Number.parseInt(getRouterParam(event, 'id') || '0');
    const body = await readBody(event);
    const userId = event.context.user!.id;

    if (!requestId || !body.fieldValues) {
      return { success: false, error: 'Invalid request data' };
    }

    // Ownership check — only the request owner may write field values
    const [requestRecord] = await db
      .select({ userId: request.userId, status: request.status, templateId: request.templateId, facultyId: request.facultyId })
      .from(request)
      .where(eq(request.id, requestId))
      .limit(1);

    if (!requestRecord) {
      return { success: false, error: 'Request not found' };
    }

    const isOwner = requestRecord.userId === userId;

    let isAuthorizedSigner = false;
    let pendingFlowForSigner: typeof signatureFlow.$inferSelect | null = null;
    if (!isOwner) {
      const userRoleRows = await db
        .select({ roleId: userRoles.roleId })
        .from(userRoles)
        .where(eq(userRoles.userId, userId));
      const userRoleIds = userRoleRows.map(r => r.roleId);

      let deanRoleId: number | null = null;
      let userIsDeanDelegate = false;
      if (requestRecord.facultyId && requestRecord.templateId) {
        const [deanRoleRow, delegateCheck] = await Promise.all([
          db.select({ id: roles.id }).from(roles).where(sql`lower(${roles.name}) = 'dean'`).limit(1),
          isActiveDelegateForRequest(userId, Number(requestRecord.facultyId), Number(requestRecord.templateId)),
        ]);
        deanRoleId = deanRoleRow[0]?.id ?? null;
        userIsDeanDelegate = delegateCheck;
      }

      const [pendingFlow] = await db
        .select()
        .from(signatureFlow)
        .where(and(
          eq(signatureFlow.requestId, requestId),
          eq(signatureFlow.status, 'pending'),
          eq(signatureFlow.acknowledgeOnly, false),
        ))
        .orderBy(asc(signatureFlow.stepOrder))
        .limit(1);

      if (pendingFlow) {
        pendingFlowForSigner = pendingFlow;
        isAuthorizedSigner = pendingFlow.assignedUserId === userId
          || (pendingFlow.assignedUserId === null && userRoleIds.includes(pendingFlow.roleId))
          || (userIsDeanDelegate && deanRoleId !== null && pendingFlow.roleId === deanRoleId);
      }
    }

    if (!isOwner && !isAuthorizedSigner) {
      throw createError({ statusCode: 403, message: 'Forbidden' });
    }

    if (isOwner && requestRecord.status !== 'draft') {
      return { success: false, error: 'Field values can only be edited while the request is in draft' };
    }
    if (isAuthorizedSigner && !['in_progress', 'pending_signature'].includes(requestRecord.status ?? '')) {
      return { success: false, error: 'Request is not in a signable state' };
    }

    const fieldMaxLengthMap = new Map<number, number>();
    const checkboxFieldIds = new Set<number>();
    // NOTE: We no longer pre-collect autoGeneratedDateTimeFieldIds to skip them.
    // When a signer explicitly resolves and saves an auto-generated value (e.g. the
    // sign date for their step), that value must be persisted so subsequent signing
    // steps don't regenerate it with a fresh timestamp.

    if (requestRecord.templateId) {
      const [templateRecord] = await db
        .select({ placedFieldsData: requestTemplate.placedFieldsData })
        .from(requestTemplate)
        .where(eq(requestTemplate.id, Number(requestRecord.templateId)))
        .limit(1);

      if (Array.isArray(templateRecord?.placedFieldsData)) {
        for (const placedField of templateRecord.placedFieldsData as any[]) {
          const placedFieldId = Number.parseInt(String(placedField?.id ?? ''), 10);
          if (!Number.isFinite(placedFieldId) || placedFieldId <= 0)
            continue;

          if (isCheckboxField(placedField)) {
            checkboxFieldIds.add(placedFieldId);
          }

          const maxLength = parsePositiveInteger(placedField?.maxLength ?? placedField?.max_length);
          if (!maxLength)
            continue;

          const existingLimit = fieldMaxLengthMap.get(placedFieldId);
          fieldMaxLengthMap.set(
            placedFieldId,
            existingLimit ? Math.min(existingLimit, maxLength) : maxLength,
          );
        }
      }
    }

    if (!Array.isArray(body.fieldValues)) {
      return { success: false, error: 'fieldValues must be an array' };
    }

    const signerAllowedInstanceIds = new Set<string>();
    if (isAuthorizedSigner && pendingFlowForSigner?.assignedFieldInstanceIds) {
      for (const id of pendingFlowForSigner.assignedFieldInstanceIds as string[]) {
        const normalized = String(id ?? '').trim();
        if (normalized.length > 0) {
          signerAllowedInstanceIds.add(normalized);
        }
      }
    }

    const results = [];
    for (const fieldValue of body.fieldValues) {
      const { fieldId, value, instanceId } = fieldValue;

      const normalizedFieldId = Number.parseInt(String(fieldId ?? ''), 10);
      if (!Number.isFinite(normalizedFieldId) || normalizedFieldId <= 0)
        continue;
      const normalizedInstanceId = String(instanceId ?? '').trim();

      if (isAuthorizedSigner) {
        // Signer can only write fields that are assigned to the current pending step.
        // Enforce by instanceId to avoid cross-step overwrites on repeated fieldIds.
        if (!normalizedInstanceId.length || !signerAllowedInstanceIds.has(normalizedInstanceId)) {
          continue;
        }
      }

      let normalizedValue = String(value ?? '');
      if (checkboxFieldIds.has(normalizedFieldId)) {
        normalizedValue = normalizeCheckboxValue(normalizedValue);
      }

      const maxLength = fieldMaxLengthMap.get(normalizedFieldId);
      if (maxLength && normalizedValue.length > maxLength) {
        normalizedValue = normalizedValue.slice(0, maxLength);
      }

      const existing = await db
        .select()
        .from(requestTemplateValues)
        .where(
          and(
            eq(requestTemplateValues.requestId, requestId),
            eq(requestTemplateValues.fieldId, normalizedFieldId),
            normalizedInstanceId.length
              ? eq(requestTemplateValues.fieldInstanceId, normalizedInstanceId)
              : isNull(requestTemplateValues.fieldInstanceId),
          ),
        )
        .limit(1);

      if (existing.length > 0) {
        await db
          .update(requestTemplateValues)
          .set({ value: normalizedValue, createdAt: new Date().toISOString() })
          .where(eq(requestTemplateValues.id, existing[0].id));
        results.push({ fieldId: normalizedFieldId, instanceId: normalizedInstanceId || null, action: 'updated' });
      }
      else {
        await db.insert(requestTemplateValues).values({
          requestId,
          fieldId: normalizedFieldId,
          fieldInstanceId: normalizedInstanceId || null,
          value: normalizedValue,
        });
        results.push({ fieldId: normalizedFieldId, instanceId: normalizedInstanceId || null, action: 'created' });
      }
    }

    return { success: true, data: results };
  }
  catch (error: any) {
    console.error('Error saving field values:', error);
    return { success: false, error: error.message || 'Failed to save field values' };
  }
});

function parsePositiveInteger(value: unknown): number | null {
  const parsed = Number.parseInt(String(value ?? ''), 10);
  if (!Number.isFinite(parsed) || parsed <= 0)
    return null;
  return parsed;
}

function normalizeCheckboxValue(value: unknown): string {
  const normalized = String(value ?? '').trim().toLowerCase();
  return ['true', '1', 'yes', 'y', 'checked', 'on'].includes(normalized) ? 'true' : '';
}

function getFieldType(field: any): string {
  return String(field?.type ?? field?.fieldType ?? '').trim().toLowerCase();
}

function isCheckboxField(field: any): boolean {
  const fieldType = getFieldType(field);
  const fieldName = String(field?.name ?? '').trim().toLowerCase();
  return fieldType === 'checkbox' || fieldName === 'check mark';
}
