import { and, eq } from 'drizzle-orm';

import db from '../../../../lib/db';
import { request, requestTemplate, requestTemplateValues } from '../../../../lib/db/schema';

export default defineEventHandler(async (event) => {
  // await requirePermission(event, '<permission>', '<permission>', ...);

  try {
    const requestId = Number.parseInt(getRouterParam(event, 'id') || '0');
    const body = await readBody(event);
    const userId = event.context.user!.id; // We can assert this because of the require-auth middleware

    if (!requestId || !body.fieldValues) {
      return {
        success: false,
        error: 'Invalid request data',
      };
    }

    // Ownership check — only the request owner may write field values
    const [requestRecord] = await db
      .select({ userId: request.userId, status: request.status, templateId: request.templateId })
      .from(request)
      .where(eq(request.id, requestId))
      .limit(1);

    if (!requestRecord) {
      return { success: false, error: 'Request not found' };
    }

    if (requestRecord.userId !== userId) {
      throw createError({ statusCode: 403, message: 'Forbidden' });
    }

    if (requestRecord.status !== 'draft') {
      return { success: false, error: 'Field values can only be edited while the request is in draft' };
    }

    const fieldMaxLengthMap = new Map<number, number>();
    const autoGeneratedDateTimeFieldIds = new Set<number>();

    if (requestRecord.templateId) {
      const [templateRecord] = await db
        .select({ placedFieldsData: requestTemplate.placedFieldsData })
        .from(requestTemplate)
        .where(eq(requestTemplate.id, Number(requestRecord.templateId)))
        .limit(1);

      if (Array.isArray(templateRecord?.placedFieldsData)) {
        for (const placedField of templateRecord.placedFieldsData as any[]) {
          const placedFieldId = Number.parseInt(String(placedField?.id ?? ''), 10);
          if (!Number.isFinite(placedFieldId) || placedFieldId <= 0) {
            continue;
          }

          if (isAutoGeneratedDateOrTimeField(placedField)) {
            autoGeneratedDateTimeFieldIds.add(placedFieldId);
            continue;
          }

          const maxLength = parsePositiveInteger(placedField?.maxLength ?? placedField?.max_length);

          if (!maxLength) {
            continue;
          }

          const existingLimit = fieldMaxLengthMap.get(placedFieldId);
          fieldMaxLengthMap.set(placedFieldId, existingLimit ? Math.min(existingLimit, maxLength) : maxLength);
        }
      }
    }

    // Validate that fieldValues is an array
    if (!Array.isArray(body.fieldValues)) {
      return {
        success: false,
        error: 'fieldValues must be an array',
      };
    }

    // Process each field value
    const results = [];
    for (const fieldValue of body.fieldValues) {
      const { fieldId, value } = fieldValue;

      const normalizedFieldId = Number.parseInt(String(fieldId ?? ''), 10);
      if (!Number.isFinite(normalizedFieldId) || normalizedFieldId <= 0) {
        continue;
      }

      if (autoGeneratedDateTimeFieldIds.has(normalizedFieldId)) {
        continue;
      }

      let normalizedValue = String(value ?? '');
      const maxLength = fieldMaxLengthMap.get(normalizedFieldId);
      if (maxLength && normalizedValue.length > maxLength) {
        normalizedValue = normalizedValue.slice(0, maxLength);
      }

      // Check if this field value already exists
      const existing = await db
        .select()
        .from(requestTemplateValues)
        .where(
          and(
            eq(requestTemplateValues.requestId, requestId),
            eq(requestTemplateValues.fieldId, normalizedFieldId),
          ),
        )
        .limit(1);

      if (existing.length > 0) {
        // Update existing value
        await db
          .update(requestTemplateValues)
          .set({ value: normalizedValue, createdAt: new Date().toISOString() })
          .where(eq(requestTemplateValues.id, existing[0].id));

        results.push({ fieldId: normalizedFieldId, action: 'updated' });
      }
      else {
        // Insert new value
        await db.insert(requestTemplateValues).values({
          requestId,
          fieldId: normalizedFieldId,
          value: normalizedValue,
        });

        results.push({ fieldId: normalizedFieldId, action: 'created' });
      }
    }

    return {
      success: true,
      data: results,
    };
  }
  catch (error: any) {
    console.error('Error saving field values:', error);
    return {
      success: false,
      error: error.message || 'Failed to save field values',
    };
  }
});

function parsePositiveInteger(value: unknown): number | null {
  const parsed = Number.parseInt(String(value ?? ''), 10);
  if (!Number.isFinite(parsed) || parsed <= 0) {
    return null;
  }
  return parsed;
}

function getFieldType(field: any): string {
  return String(field?.type ?? field?.fieldType ?? '').trim().toLowerCase();
}

function isAutoGeneratedDateOrTimeField(field: any): boolean {
  const fieldType = getFieldType(field);
  if (fieldType === 'time') {
    return true;
  }
  if (fieldType !== 'date') {
    return false;
  }

  return field?.isAutoGenerate === true || field?.isAutoGenerated === true || field?.is_auto_generated === true;
}
