export type AutoDateTimeFormatConfig = {
  dateSeparator: string;
  dateSeparatorSpacing: number;
  dateShowDay: boolean;
  dateShowMonth: boolean;
  dateShowYear: boolean;
  dateShowDayOfWeek: boolean;
  dateDayOfWeekStyle: 'long' | 'short';
  dateDayOfWeekGap: number;
  dateMonthStyle: 'numeric' | 'short' | 'long';
  dateCalendar: 'ad' | 'be';
  timeSeparator: string;
  timeSeparatorSpacing: number;
  timeShowHour: boolean;
  timeShowMinute: boolean;
};

const DEFAULT_AUTO_DATE_TIME_CONFIG: AutoDateTimeFormatConfig = {
  dateSeparator: '/',
  dateSeparatorSpacing: 0,
  dateShowDay: true,
  dateShowMonth: true,
  dateShowYear: true,
  dateShowDayOfWeek: false,
  dateDayOfWeekStyle: 'long',
  dateDayOfWeekGap: 1,
  dateMonthStyle: 'numeric',
  dateCalendar: 'ad',
  timeSeparator: ':',
  timeSeparatorSpacing: 0,
  timeShowHour: true,
  timeShowMinute: true,
};

const THAI_DAY_LONG = ['วันอาทิตย์', 'วันจันทร์', 'วันอังคาร', 'วันพุธ', 'วันพฤหัสบดี', 'วันศุกร์', 'วันเสาร์'];
const THAI_DAY_SHORT = ['อา.', 'จ.', 'อ.', 'พ.', 'พฤ.', 'ศ.', 'ส.'];
const THAI_MONTH_SHORT = ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'];
const THAI_MONTH_LONG = ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'];

const BANGKOK_DATE_FORMATTER = new Intl.DateTimeFormat('en-GB', {
  day: '2-digit',
  month: '2-digit',
  year: 'numeric',
  timeZone: 'Asia/Bangkok',
});

const BANGKOK_TIME_FORMATTER = new Intl.DateTimeFormat('en-GB', {
  hour: '2-digit',
  minute: '2-digit',
  hour12: false,
  timeZone: 'Asia/Bangkok',
});

function normalizeSeparator(value: unknown, fallback: string): string {
  if (typeof value !== 'string') {
    return fallback;
  }
  return value;
}

function normalizeSeparatorSpacing(value: unknown, fallback: number): number {
  const parsed = Number.parseInt(String(value ?? ''), 10);
  if (!Number.isFinite(parsed) || parsed < 0) {
    return fallback;
  }

  return parsed;
}

function normalizeBoolean(value: unknown, fallback: boolean): boolean {
  if (typeof value === 'boolean') {
    return value;
  }
  return fallback;
}

function normalizeMonthStyle(value: unknown): 'numeric' | 'short' | 'long' {
  if (value === 'short' || value === 'long') {
    return value;
  }
  return 'numeric';
}

function normalizeDayOfWeekStyle(value: unknown): 'long' | 'short' {
  if (value === 'short') {
    return 'short';
  }
  return 'long';
}

function normalizeCalendar(value: unknown): 'ad' | 'be' {
  if (value === 'be') {
    return 'be';
  }
  return 'ad';
}

function getBangkokWeekday(date: Date): number {
  // Bangkok is UTC+7 with no DST
  const bangkokMs = date.getTime() + 7 * 60 * 60 * 1000;
  return new Date(bangkokMs).getUTCDay();
}

function withSeparatorSpacing(separator: string, spacing: number): string {
  if (spacing <= 0) {
    return separator;
  }

  const padding = ' '.repeat(spacing);

  if (!separator.length) {
    return padding;
  }

  return `${padding}${separator}${padding}`;
}

function getFieldType(field: any): string {
  return String(field?.type || field?.fieldType || '').toLowerCase();
}

function isAutoGeneratedField(field: any): boolean {
  return field?.isAutoGenerate === true || field?.isAutoGenerated === true || field?.is_auto_generated === true;
}

function getFormattedPart(formatter: Intl.DateTimeFormat, partType: 'day' | 'month' | 'year' | 'hour' | 'minute', date: Date): string {
  const part = formatter.formatToParts(date).find(p => p.type === partType);
  return part?.value ?? '';
}

export function getAutoDateTimeFormatConfig(field: any): AutoDateTimeFormatConfig {
  return {
    dateSeparator: normalizeSeparator(field?.dateSeparator, DEFAULT_AUTO_DATE_TIME_CONFIG.dateSeparator),
    dateSeparatorSpacing: normalizeSeparatorSpacing(field?.dateSeparatorSpacing, DEFAULT_AUTO_DATE_TIME_CONFIG.dateSeparatorSpacing),
    dateShowDay: normalizeBoolean(field?.dateShowDay, DEFAULT_AUTO_DATE_TIME_CONFIG.dateShowDay),
    dateShowMonth: normalizeBoolean(field?.dateShowMonth, DEFAULT_AUTO_DATE_TIME_CONFIG.dateShowMonth),
    dateShowYear: normalizeBoolean(field?.dateShowYear, DEFAULT_AUTO_DATE_TIME_CONFIG.dateShowYear),
    dateShowDayOfWeek: normalizeBoolean(field?.dateShowDayOfWeek, DEFAULT_AUTO_DATE_TIME_CONFIG.dateShowDayOfWeek),
    dateDayOfWeekStyle: normalizeDayOfWeekStyle(field?.dateDayOfWeekStyle),
    dateDayOfWeekGap: normalizeSeparatorSpacing(field?.dateDayOfWeekGap, DEFAULT_AUTO_DATE_TIME_CONFIG.dateDayOfWeekGap),
    dateMonthStyle: normalizeMonthStyle(field?.dateMonthStyle),
    dateCalendar: normalizeCalendar(field?.dateCalendar),
    timeSeparator: normalizeSeparator(field?.timeSeparator, DEFAULT_AUTO_DATE_TIME_CONFIG.timeSeparator),
    timeSeparatorSpacing: normalizeSeparatorSpacing(field?.timeSeparatorSpacing, DEFAULT_AUTO_DATE_TIME_CONFIG.timeSeparatorSpacing),
    timeShowHour: normalizeBoolean(field?.timeShowHour, DEFAULT_AUTO_DATE_TIME_CONFIG.timeShowHour),
    timeShowMinute: normalizeBoolean(field?.timeShowMinute, DEFAULT_AUTO_DATE_TIME_CONFIG.timeShowMinute),
  };
}

export function formatAutoGeneratedDate(field: any, now: Date = new Date()): string {
  const config = getAutoDateTimeFormatConfig(field);
  const separator = withSeparatorSpacing(config.dateSeparator, config.dateSeparatorSpacing);

  const dayNumeric = getFormattedPart(BANGKOK_DATE_FORMATTER, 'day', now);
  const monthNumeric = getFormattedPart(BANGKOK_DATE_FORMATTER, 'month', now);
  const yearAD = getFormattedPart(BANGKOK_DATE_FORMATTER, 'year', now);

  // Month display based on style
  const monthIdx = Number.parseInt(monthNumeric, 10) - 1;
  let monthDisplay: string;
  if (config.dateMonthStyle === 'short') {
    monthDisplay = THAI_MONTH_SHORT[monthIdx] ?? monthNumeric;
  }
  else if (config.dateMonthStyle === 'long') {
    monthDisplay = THAI_MONTH_LONG[monthIdx] ?? monthNumeric;
  }
  else {
    monthDisplay = monthNumeric;
  }

  // Year display: ค.ศ. or พ.ศ.
  const yearDisplay = config.dateCalendar === 'be'
    ? String(Number.parseInt(yearAD, 10) + 543)
    : yearAD;

  const orderedParts: Array<'day' | 'month' | 'year'> = ['day', 'month', 'year'];
  const selectedParts = orderedParts.filter((part) => {
    if (part === 'day') {
      return config.dateShowDay;
    }
    if (part === 'month') {
      return config.dateShowMonth;
    }
    return config.dateShowYear;
  });

  const finalParts = selectedParts.length ? selectedParts : orderedParts;

  const dateParts = finalParts.map((part) => {
    if (part === 'day') {
      return dayNumeric;
    }
    if (part === 'month') {
      return monthDisplay;
    }
    return yearDisplay;
  });

  let result = dateParts.join(separator);

  // Prepend day-of-week name
  if (config.dateShowDayOfWeek) {
    const weekday = getBangkokWeekday(now);
    const dowText = config.dateDayOfWeekStyle === 'short'
      ? (THAI_DAY_SHORT[weekday] ?? '')
      : (THAI_DAY_LONG[weekday] ?? '');
    const dowGap = ' '.repeat(Math.max(0, config.dateDayOfWeekGap));
    result = `${dowText}${dowGap}${result}`;
  }

  return result;
}

export function formatAutoGeneratedTime(field: any, now: Date = new Date()): string {
  const config = getAutoDateTimeFormatConfig(field);
  const separator = withSeparatorSpacing(config.timeSeparator, config.timeSeparatorSpacing);

  const hour = getFormattedPart(BANGKOK_TIME_FORMATTER, 'hour', now);
  const minute = getFormattedPart(BANGKOK_TIME_FORMATTER, 'minute', now);

  const selectedParts: string[] = [];
  if (config.timeShowHour) {
    selectedParts.push(hour);
  }
  if (config.timeShowMinute) {
    selectedParts.push(minute);
  }

  const finalParts = selectedParts.length ? selectedParts : [hour, minute];
  return finalParts.join(separator);
}

export function resolveAutoGeneratedDateTimeValue(field: any, now: Date = new Date()): string {
  const fieldType = getFieldType(field);
  if (!isAutoGeneratedField(field)) {
    return '';
  }

  if (fieldType === 'time') {
    return formatAutoGeneratedTime(field, now);
  }

  if (fieldType === 'date') {
    return formatAutoGeneratedDate(field, now);
  }

  return '';
}
