export type AutoDateTimeFormatConfig = {
  dateSeparator: string;
  dateSeparatorSpacing: number;
  dateShowDay: boolean;
  dateShowMonth: boolean;
  dateShowYear: boolean;
  timeSeparator: string;
  timeSeparatorSpacing: number;
  timeShowHour: boolean;
  timeShowMinute: boolean;
};

const DEFAULT_AUTO_DATE_TIME_CONFIG: AutoDateTimeFormatConfig = {
  dateSeparator: '/',
  dateSeparatorSpacing: 0,
  dateShowDay: true,
  dateShowMonth: true,
  dateShowYear: true,
  timeSeparator: ':',
  timeSeparatorSpacing: 0,
  timeShowHour: true,
  timeShowMinute: true,
};

const BANGKOK_DATE_FORMATTER = new Intl.DateTimeFormat('en-GB', {
  day: '2-digit',
  month: '2-digit',
  year: 'numeric',
  timeZone: 'Asia/Bangkok',
});

const BANGKOK_TIME_FORMATTER = new Intl.DateTimeFormat('en-GB', {
  hour: '2-digit',
  minute: '2-digit',
  hour12: false,
  timeZone: 'Asia/Bangkok',
});

function normalizeSeparator(value: unknown, fallback: string): string {
  if (typeof value !== 'string') {
    return fallback;
  }
  return value;
}

function normalizeSeparatorSpacing(value: unknown, fallback: number): number {
  const parsed = Number.parseInt(String(value ?? ''), 10);
  if (!Number.isFinite(parsed) || parsed < 0) {
    return fallback;
  }

  return parsed;
}

function normalizeBoolean(value: unknown, fallback: boolean): boolean {
  if (typeof value === 'boolean') {
    return value;
  }
  return fallback;
}

function withSeparatorSpacing(separator: string, spacing: number): string {
  if (spacing <= 0) {
    return separator;
  }

  const padding = ' '.repeat(spacing);

  if (!separator.length) {
    return padding;
  }

  return `${padding}${separator}${padding}`;
}

function getFieldType(field: any): string {
  return String(field?.type || field?.fieldType || '').toLowerCase();
}

function isAutoGeneratedField(field: any): boolean {
  const fieldType = getFieldType(field);
  if (fieldType === 'time') {
    return true;
  }

  return field?.isAutoGenerate === true || field?.isAutoGenerated === true || field?.is_auto_generated === true;
}

function getFormattedPart(formatter: Intl.DateTimeFormat, partType: 'day' | 'month' | 'year' | 'hour' | 'minute', date: Date): string {
  const part = formatter.formatToParts(date).find(p => p.type === partType);
  return part?.value ?? '';
}

export function getAutoDateTimeFormatConfig(field: any): AutoDateTimeFormatConfig {
  return {
    dateSeparator: normalizeSeparator(field?.dateSeparator, DEFAULT_AUTO_DATE_TIME_CONFIG.dateSeparator),
    dateSeparatorSpacing: normalizeSeparatorSpacing(field?.dateSeparatorSpacing, DEFAULT_AUTO_DATE_TIME_CONFIG.dateSeparatorSpacing),
    dateShowDay: normalizeBoolean(field?.dateShowDay, DEFAULT_AUTO_DATE_TIME_CONFIG.dateShowDay),
    dateShowMonth: normalizeBoolean(field?.dateShowMonth, DEFAULT_AUTO_DATE_TIME_CONFIG.dateShowMonth),
    dateShowYear: normalizeBoolean(field?.dateShowYear, DEFAULT_AUTO_DATE_TIME_CONFIG.dateShowYear),
    timeSeparator: normalizeSeparator(field?.timeSeparator, DEFAULT_AUTO_DATE_TIME_CONFIG.timeSeparator),
    timeSeparatorSpacing: normalizeSeparatorSpacing(field?.timeSeparatorSpacing, DEFAULT_AUTO_DATE_TIME_CONFIG.timeSeparatorSpacing),
    timeShowHour: normalizeBoolean(field?.timeShowHour, DEFAULT_AUTO_DATE_TIME_CONFIG.timeShowHour),
    timeShowMinute: normalizeBoolean(field?.timeShowMinute, DEFAULT_AUTO_DATE_TIME_CONFIG.timeShowMinute),
  };
}

export function formatAutoGeneratedDate(field: any, now: Date = new Date()): string {
  const config = getAutoDateTimeFormatConfig(field);
  const separator = withSeparatorSpacing(config.dateSeparator, config.dateSeparatorSpacing);

  const day = getFormattedPart(BANGKOK_DATE_FORMATTER, 'day', now);
  const month = getFormattedPart(BANGKOK_DATE_FORMATTER, 'month', now);
  const year = getFormattedPart(BANGKOK_DATE_FORMATTER, 'year', now);

  const orderedParts: Array<'day' | 'month' | 'year'> = ['day', 'month', 'year'];
  const selectedParts = orderedParts.filter((part) => {
    if (part === 'day') {
      return config.dateShowDay;
    }
    if (part === 'month') {
      return config.dateShowMonth;
    }
    return config.dateShowYear;
  });

  const finalParts = selectedParts.length ? selectedParts : orderedParts;

  return finalParts
    .map((part) => {
      if (part === 'day') {
        return day;
      }
      if (part === 'month') {
        return month;
      }
      return year;
    })
    .join(separator);
}

export function formatAutoGeneratedTime(field: any, now: Date = new Date()): string {
  const config = getAutoDateTimeFormatConfig(field);
  const separator = withSeparatorSpacing(config.timeSeparator, config.timeSeparatorSpacing);

  const hour = getFormattedPart(BANGKOK_TIME_FORMATTER, 'hour', now);
  const minute = getFormattedPart(BANGKOK_TIME_FORMATTER, 'minute', now);

  const selectedParts: string[] = [];
  if (config.timeShowHour) {
    selectedParts.push(hour);
  }
  if (config.timeShowMinute) {
    selectedParts.push(minute);
  }

  const finalParts = selectedParts.length ? selectedParts : [hour, minute];
  return finalParts.join(separator);
}

export function resolveAutoGeneratedDateTimeValue(field: any, now: Date = new Date()): string {
  const fieldType = getFieldType(field);
  if (fieldType === 'time') {
    return formatAutoGeneratedTime(field, now);
  }

  if (fieldType === 'date' && isAutoGeneratedField(field)) {
    return formatAutoGeneratedDate(field, now);
  }

  return '';
}
