export type AutoDateTimeFormatConfig = {
  dateSeparator: string;
  dateSeparatorSpacing: number;
  dateShowDay: boolean;
  dateShowMonth: boolean;
  dateShowYear: boolean;
  dateShowDayOfWeek: boolean;
  dateDayOfWeekStyle: 'long' | 'short';
  dateDayOfWeekGap: number;
  dateMonthStyle: 'numeric' | 'short' | 'long';
  dateCalendar: 'ad' | 'be';
  timeSeparator: string;
  timeSeparatorSpacing: number;
  timeShowHour: boolean;
  timeShowMinute: boolean;
};

const DEFAULT_AUTO_DATE_TIME_CONFIG: AutoDateTimeFormatConfig = {
  dateSeparator: '/',
  dateSeparatorSpacing: 0,
  dateShowDay: true,
  dateShowMonth: true,
  dateShowYear: true,
  dateShowDayOfWeek: false,
  dateDayOfWeekStyle: 'long',
  dateDayOfWeekGap: 1,
  dateMonthStyle: 'numeric',
  dateCalendar: 'ad',
  timeSeparator: ':',
  timeSeparatorSpacing: 0,
  timeShowHour: true,
  timeShowMinute: true,
};

const THAI_DAY_LONG = ['วันอาทิตย์', 'วันจันทร์', 'วันอังคาร', 'วันพุธ', 'วันพฤหัสบดี', 'วันศุกร์', 'วันเสาร์'];
const THAI_DAY_SHORT = ['อา.', 'จ.', 'อ.', 'พ.', 'พฤ.', 'ศ.', 'ส.'];
const THAI_MONTH_SHORT = ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'];
const THAI_MONTH_LONG = ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'];

const BANGKOK_DATE_FORMATTER = new Intl.DateTimeFormat('en-GB', {
  day: '2-digit',
  month: '2-digit',
  year: 'numeric',
  timeZone: 'Asia/Bangkok',
});

const BANGKOK_TIME_FORMATTER = new Intl.DateTimeFormat('en-GB', {
  hour: '2-digit',
  minute: '2-digit',
  hour12: false,
  timeZone: 'Asia/Bangkok',
});

function normalizeSeparator(value: unknown, fallback: string): string {
  if (typeof value !== 'string') {
    return fallback;
  }
  return value;
}

function normalizeSeparatorSpacing(value: unknown, fallback: number): number {
  const parsed = Number.parseInt(String(value ?? ''), 10);
  if (!Number.isFinite(parsed) || parsed < 0) {
    return fallback;
  }

  return parsed;
}

function normalizeBoolean(value: unknown, fallback: boolean): boolean {
  if (typeof value === 'boolean') {
    return value;
  }
  return fallback;
}

function normalizeMonthStyle(value: unknown): 'numeric' | 'short' | 'long' {
  if (value === 'short' || value === 'long') {
    return value;
  }
  return 'numeric';
}

function normalizeDayOfWeekStyle(value: unknown): 'long' | 'short' {
  if (value === 'short') {
    return 'short';
  }
  return 'long';
}

function normalizeCalendar(value: unknown): 'ad' | 'be' {
  if (value === 'be') {
    return 'be';
  }
  return 'ad';
}

function getBangkokWeekday(date: Date): number {
  // Bangkok is UTC+7 with no DST
  const bangkokMs = date.getTime() + 7 * 60 * 60 * 1000;
  return new Date(bangkokMs).getUTCDay();
}

function makeBangkokDateFromParts(parts: { year: number; month: number; day: number; hour: number; minute: number }): Date {
  // Create a Date that represents Bangkok local time for the provided parts.
  const utcMs = Date.UTC(parts.year, parts.month - 1, parts.day, parts.hour - 7, parts.minute, 0, 0);
  return new Date(utcMs);
}

export function parseDateInputToBangkokDate(value: string): Date | null {
  const raw = String(value ?? '').trim();
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(raw);
  if (!match) {
    return null;
  }

  let year = Number.parseInt(match[1], 10);
  const month = Number.parseInt(match[2], 10);
  const day = Number.parseInt(match[3], 10);

  if (!Number.isFinite(year) || !Number.isFinite(month) || !Number.isFinite(day)) {
    return null;
  }
  if (year >= 2400) {
    year -= 543;
  }
  if (month < 1 || month > 12 || day < 1 || day > 31) {
    return null;
  }

  const utcCheck = new Date(Date.UTC(year, month - 1, day));
  if (
    utcCheck.getUTCFullYear() !== year
    || utcCheck.getUTCMonth() !== month - 1
    || utcCheck.getUTCDate() !== day
  ) {
    return null;
  }

  return makeBangkokDateFromParts({ year, month, day, hour: 12, minute: 0 });
}

function withSeparatorSpacing(separator: string, spacing: number): string {
  if (spacing <= 0) {
    return separator;
  }

  const padding = ' '.repeat(spacing);

  if (!separator.length) {
    return padding;
  }

  return `${padding}${separator}${padding}`;
}

function getFieldType(field: any): string {
  return String(field?.type || field?.fieldType || '').toLowerCase();
}

function isAutoGeneratedField(field: any): boolean {
  return field?.isAutoGenerate === true || field?.isAutoGenerated === true || field?.is_auto_generated === true;
}

function getFormattedPart(formatter: Intl.DateTimeFormat, partType: 'day' | 'month' | 'year' | 'hour' | 'minute', date: Date): string {
  const part = formatter.formatToParts(date).find(p => p.type === partType);
  return part?.value ?? '';
}

export function getAutoDateTimeFormatConfig(field: any): AutoDateTimeFormatConfig {
  return {
    dateSeparator: normalizeSeparator(field?.dateSeparator, DEFAULT_AUTO_DATE_TIME_CONFIG.dateSeparator),
    dateSeparatorSpacing: normalizeSeparatorSpacing(field?.dateSeparatorSpacing, DEFAULT_AUTO_DATE_TIME_CONFIG.dateSeparatorSpacing),
    dateShowDay: normalizeBoolean(field?.dateShowDay, DEFAULT_AUTO_DATE_TIME_CONFIG.dateShowDay),
    dateShowMonth: normalizeBoolean(field?.dateShowMonth, DEFAULT_AUTO_DATE_TIME_CONFIG.dateShowMonth),
    dateShowYear: normalizeBoolean(field?.dateShowYear, DEFAULT_AUTO_DATE_TIME_CONFIG.dateShowYear),
    dateShowDayOfWeek: normalizeBoolean(field?.dateShowDayOfWeek, DEFAULT_AUTO_DATE_TIME_CONFIG.dateShowDayOfWeek),
    dateDayOfWeekStyle: normalizeDayOfWeekStyle(field?.dateDayOfWeekStyle),
    dateDayOfWeekGap: normalizeSeparatorSpacing(field?.dateDayOfWeekGap, DEFAULT_AUTO_DATE_TIME_CONFIG.dateDayOfWeekGap),
    dateMonthStyle: normalizeMonthStyle(field?.dateMonthStyle),
    dateCalendar: normalizeCalendar(field?.dateCalendar),
    timeSeparator: normalizeSeparator(field?.timeSeparator, DEFAULT_AUTO_DATE_TIME_CONFIG.timeSeparator),
    timeSeparatorSpacing: normalizeSeparatorSpacing(field?.timeSeparatorSpacing, DEFAULT_AUTO_DATE_TIME_CONFIG.timeSeparatorSpacing),
    timeShowHour: normalizeBoolean(field?.timeShowHour, DEFAULT_AUTO_DATE_TIME_CONFIG.timeShowHour),
    timeShowMinute: normalizeBoolean(field?.timeShowMinute, DEFAULT_AUTO_DATE_TIME_CONFIG.timeShowMinute),
  };
}

export function formatAutoGeneratedDate(field: any, now: Date = new Date()): string {
  const config = getAutoDateTimeFormatConfig(field);
  return formatDateWithConfig(now, config);
}

export function formatAutoGeneratedTime(field: any, now: Date = new Date()): string {
  const config = getAutoDateTimeFormatConfig(field);
  return formatTimeWithConfig(now, config);
}

export function resolveAutoGeneratedDateTimeValue(field: any, now: Date = new Date()): string {
  const fieldType = getFieldType(field);
  if (!isAutoGeneratedField(field)) {
    return '';
  }

  if (fieldType === 'time') {
    return formatAutoGeneratedTime(field, now);
  }

  if (fieldType === 'date') {
    return formatAutoGeneratedDate(field, now);
  }

  return '';
}

function formatDateWithConfig(date: Date, config: AutoDateTimeFormatConfig): string {
  const separator = withSeparatorSpacing(config.dateSeparator, config.dateSeparatorSpacing);

  const dayNumeric = getFormattedPart(BANGKOK_DATE_FORMATTER, 'day', date);
  const monthNumeric = getFormattedPart(BANGKOK_DATE_FORMATTER, 'month', date);
  const yearAD = getFormattedPart(BANGKOK_DATE_FORMATTER, 'year', date);

  const monthIdx = Number.parseInt(monthNumeric, 10) - 1;
  let monthDisplay: string;
  if (config.dateMonthStyle === 'short') {
    monthDisplay = THAI_MONTH_SHORT[monthIdx] ?? monthNumeric;
  }
  else if (config.dateMonthStyle === 'long') {
    monthDisplay = THAI_MONTH_LONG[monthIdx] ?? monthNumeric;
  }
  else {
    monthDisplay = monthNumeric;
  }

  const yearDisplay = config.dateCalendar === 'be'
    ? String(Number.parseInt(yearAD, 10) + 543)
    : yearAD;

  const orderedParts: Array<'day' | 'month' | 'year'> = ['day', 'month', 'year'];
  const selectedParts = orderedParts.filter((part) => {
    if (part === 'day') {
      return config.dateShowDay;
    }
    if (part === 'month') {
      return config.dateShowMonth;
    }
    return config.dateShowYear;
  });

  const finalParts = selectedParts.length ? selectedParts : orderedParts;

  const dateParts = finalParts.map((part) => {
    if (part === 'day') {
      return dayNumeric;
    }
    if (part === 'month') {
      return monthDisplay;
    }
    return yearDisplay;
  });

  let result = dateParts.join(separator);

  if (config.dateShowDayOfWeek) {
    const weekday = getBangkokWeekday(date);
    const dowText = config.dateDayOfWeekStyle === 'short'
      ? (THAI_DAY_SHORT[weekday] ?? '')
      : (THAI_DAY_LONG[weekday] ?? '');
    const dowGap = ' '.repeat(Math.max(0, config.dateDayOfWeekGap));
    result = `${dowText}${dowGap}${result}`;
  }

  return result;
}

function formatTimeWithConfig(date: Date, config: AutoDateTimeFormatConfig): string {
  const separator = withSeparatorSpacing(config.timeSeparator, config.timeSeparatorSpacing);

  const hour = getFormattedPart(BANGKOK_TIME_FORMATTER, 'hour', date);
  const minute = getFormattedPart(BANGKOK_TIME_FORMATTER, 'minute', date);

  const selectedParts: string[] = [];
  if (config.timeShowHour) {
    selectedParts.push(hour);
  }
  if (config.timeShowMinute) {
    selectedParts.push(minute);
  }

  const finalParts = selectedParts.length ? selectedParts : [hour, minute];
  return finalParts.join(separator);
}

function parseManualDateTimeValue(rawValue: string): Date | null {
  const trimmed = rawValue.trim();
  if (!trimmed) {
    return null;
  }

  const dateOnlyMatch = trimmed.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (dateOnlyMatch) {
    const year = Number.parseInt(dateOnlyMatch[1], 10);
    const month = Number.parseInt(dateOnlyMatch[2], 10);
    const day = Number.parseInt(dateOnlyMatch[3], 10);
    if (Number.isFinite(year) && Number.isFinite(month) && Number.isFinite(day)) {
      return makeBangkokDateFromParts({ year, month, day, hour: 0, minute: 0 });
    }
  }

  const timeOnlyMatch = trimmed.match(/^(\d{2}):(\d{2})$/);
  if (timeOnlyMatch) {
    const hour = Number.parseInt(timeOnlyMatch[1], 10);
    const minute = Number.parseInt(timeOnlyMatch[2], 10);
    if (Number.isFinite(hour) && Number.isFinite(minute)) {
      return makeBangkokDateFromParts({ year: 1970, month: 1, day: 1, hour, minute });
    }
  }

  const dateTimeMatch = trimmed.match(/^(\d{4})-(\d{2})-(\d{2})[T\s](\d{2}):(\d{2})(?::\d{2})?$/);
  if (dateTimeMatch) {
    const year = Number.parseInt(dateTimeMatch[1], 10);
    const month = Number.parseInt(dateTimeMatch[2], 10);
    const day = Number.parseInt(dateTimeMatch[3], 10);
    const hour = Number.parseInt(dateTimeMatch[4], 10);
    const minute = Number.parseInt(dateTimeMatch[5], 10);
    if ([year, month, day, hour, minute].every(Number.isFinite)) {
      return makeBangkokDateFromParts({ year, month, day, hour, minute });
    }
  }

  const parsed = new Date(trimmed);
  if (!Number.isNaN(parsed.getTime())) {
    return parsed;
  }

  return null;
}

export function formatManualDateTimeValue(field: any, rawValue: string): string {
  const fieldType = getFieldType(field);
  if (!['date', 'time', 'datetime'].includes(fieldType)) {
    return rawValue;
  }

  const parsed = parseManualDateTimeValue(rawValue);
  if (!parsed) {
    return rawValue;
  }

  const config = getAutoDateTimeFormatConfig(field);
  if (fieldType === 'date') {
    return formatDateWithConfig(parsed, config);
  }

  if (fieldType === 'time') {
    return formatTimeWithConfig(parsed, config);
  }

  const datePart = formatDateWithConfig(parsed, config);
  const timePart = formatTimeWithConfig(parsed, config);
  if (datePart && timePart) {
    return `${datePart} ${timePart}`;
  }

  return datePart || timePart || rawValue;
}
