<script setup>
const props = defineProps({
  modelValue: Boolean,
  mode: {
    type: String,
    default: 'create', // 'create' or 'edit'
  },
  editField: {
    type: Object,
    default: null,
  },
});

const emit = defineEmits(['update:modelValue', 'fieldCreated', 'fieldUpdated', 'fieldDeleted', 'fieldUpdated', 'fieldDeleted']);

const toast = useToast();
const isSubmitting = ref(false);
const isDeleting = ref(false);
const showDeleteConfirm = ref(false);

function parsePositiveInteger(value) {
  const parsed = Number.parseInt(String(value ?? ''), 10);
  if (!Number.isFinite(parsed) || parsed <= 0) {
    return null;
  }
  return parsed;
}

function parseFiniteNumber(value, fallback) {
  const parsed = Number.parseFloat(String(value ?? ''));
  if (!Number.isFinite(parsed)) {
    return fallback;
  }
  return parsed;
}

function normalizeMaxLength(value) {
  return parsePositiveInteger(value);
}

const allowedSessionFieldBindings = ['studentName', 'studentId', 'studentYearCurrent', 'facultyNameTh', 'departmentNameTh', 'departmentCode'];

const formData = ref({
  name: '',
  type: 'Text',
  sessionField: 'none',
  icon: getIconForType('Text'),
  amount: 1,
  width: 150,
  height: 40,
  isFillable: true,
  isAutoGenerated: false,
  font: 'Sarabun',
  fontSize: 14,
  fontWeight: 'normal',
  fontStyle: 'normal',
  textDecoration: 'none',
  textAlign: 'left',
  letterSpacing: 0,
  lineHeight: 1.5,
  maxLength: null,
  strikeThroughGroupMode: false,
  strikeLineThickness: 1.5,
});

const fieldTypes = ['Text', 'Number', 'Checkbox', 'Signature', 'Date', 'Time'];

function getIconForType(type) {
  const t = String(type || '').toLowerCase();
  switch (t) {
    case 'number':
      return 'i-heroicons-hashtag';
    case 'checkbox':
      return 'i-heroicons-check';
    case 'signature':
      return 'i-heroicons-pencil-square';
    case 'date':
      return 'i-heroicons-calendar';
    case 'time':
      return 'i-heroicons-clock';
    default:
      return 'i-heroicons-document';
  }
}

const fontOptions = ['Sarabun'];

const selectedFieldType = computed(() => String(formData.value.type || '').toLowerCase());

const supportsTextSettings = computed(() => {
  return !['signature', 'icon', 'checkbox'].includes(selectedFieldType.value);
});

const supportsFontControls = computed(() => {
  if (['signature', 'checkbox'].includes(selectedFieldType.value)) {
    return false;
  }

  return true;
});

const supportsAmountSetting = computed(() => selectedFieldType.value === 'checkbox');

const supportsLetterSpacing = computed(() => {
  return !['date', 'time'].includes(selectedFieldType.value);
});

const supportsMaxLength = computed(() => {
  return !['signature', 'icon', 'date', 'time', 'checkbox'].includes(selectedFieldType.value);
});

const supportsSessionFieldBinding = computed(() => {
  return ['text', 'number'].includes(selectedFieldType.value);
});

const isOpen = computed({
  get: () => props.modelValue,
  set: value => emit('update:modelValue', value),
});

// Watch for edit field changes
watch(() => props.editField, (newField) => {
  if (newField && props.mode === 'edit') {
    const normalizedAmount = parsePositiveInteger(newField.amount) ?? 1;
    const isCheckboxGroup = String(newField.type || '').toLowerCase() === 'checkbox' && normalizedAmount > 1;
    formData.value = {
      name: newField.name || newField.label || '',
      type: newField.type || 'Text',
      sessionField: String(newField.sessionField ?? newField.session_field ?? '').trim() || 'none',
      icon: newField.icon || getIconForType(newField.type || 'Text'),
      amount: normalizedAmount,
      width: newField.default_width || newField.width || 150,
      height: newField.default_height || newField.height || 40,
      isFillable: newField.isFillable ?? true,
      isAutoGenerated: newField.isAutoGenerated ?? false,
      font: newField.font || 'Sarabun',
      fontSize: newField.fontSize || 14,
      fontWeight: newField.fontWeight || 'normal',
      fontStyle: newField.fontStyle || 'normal',
      textDecoration: newField.textDecoration || 'none',
      textAlign: newField.textAlign || 'left',
      letterSpacing: parseFiniteNumber(newField.letterSpacing, 0),
      lineHeight: parseFiniteNumber(newField.lineHeight, 1.5),
      maxLength: normalizeMaxLength(newField.maxLength ?? newField.max_length),
      strikeThroughGroupMode: isCheckboxGroup
        ? Boolean(newField.strikeThroughGroupMode ?? newField.strike_through_group_mode ?? false)
        : false,
      strikeLineThickness: Math.min(8, Math.max(0.5, parseFiniteNumber(newField.strikeLineThickness ?? newField.strike_line_thickness, 1.5))),
    };
  }
}, { immediate: true });

// Auto-set icon based on selected type when creating a new field.
watch(() => formData.value.type, (type) => {
  // If we're in edit mode and editing an existing field, do not overwrite the stored icon.
  if (props.mode === 'edit' && props.editField)
    return;
  formData.value.icon = getIconForType(type);
}, { immediate: true });

watch(supportsAmountSetting, (enabled) => {
  if (!enabled) {
    formData.value.amount = 1;
    formData.value.strikeThroughGroupMode = false;
  }
});

watch(supportsSessionFieldBinding, (enabled) => {
  if (!enabled) {
    formData.value.sessionField = 'none';
  }
});

watch(
  () => [String(formData.value.type || '').toLowerCase(), parsePositiveInteger(formData.value.amount) ?? 1],
  ([type, amount]) => {
    const isCheckboxGroup = type === 'checkbox' && amount > 1;
    if (!isCheckboxGroup) {
      formData.value.strikeThroughGroupMode = false;
    }
  },
  { immediate: true },
);

function resetForm() {
  formData.value = {
    name: '',
    type: 'Text',
    sessionField: 'none',
    icon: getIconForType('Text'),
    amount: 1,
    width: 150,
    height: 40,
    isFillable: true,
    isAutoGenerated: false,
    font: 'Sarabun',
    fontSize: 14,
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
    textAlign: 'left',
    letterSpacing: 0,
    lineHeight: 1.5,
    maxLength: null,
    strikeThroughGroupMode: false,
    strikeLineThickness: 1.5,
  };
}

function closeModal() {
  isOpen.value = false;
  resetForm();
}

function buildFieldPayload() {
  const normalizedFontSize = parsePositiveInteger(formData.value.fontSize) ?? 14;
  const normalizedAmount = supportsAmountSetting.value
    ? (parsePositiveInteger(formData.value.amount) ?? 1)
    : 1;
  const normalizedWidth = parsePositiveInteger(formData.value.width) ?? 150;
  const normalizedHeight = parsePositiveInteger(formData.value.height) ?? 40;

  return {
    ...formData.value,
    label: formData.value.name,
    amount: normalizedAmount,
    width: normalizedWidth,
    height: normalizedHeight,
    fontSize: normalizedFontSize,
    fontWeight: formData.value.fontWeight === 'bold' ? 'bold' : 'normal',
    fontStyle: formData.value.fontStyle === 'italic' ? 'italic' : 'normal',
    textDecoration: formData.value.textDecoration === 'underline' ? 'underline' : 'none',
    textAlign: ['left', 'center', 'right'].includes(formData.value.textAlign) ? formData.value.textAlign : 'left',
    letterSpacing: supportsLetterSpacing.value ? parseFiniteNumber(formData.value.letterSpacing, 0) : 0,
    lineHeight: parseFiniteNumber(formData.value.lineHeight, 1.5),
    maxLength: supportsMaxLength.value ? normalizeMaxLength(formData.value.maxLength) : null,
    sessionField: supportsSessionFieldBinding.value && allowedSessionFieldBindings.includes(formData.value.sessionField)
      ? formData.value.sessionField
      : null,
    strikeThroughGroupMode: supportsAmountSetting.value
      ? Boolean(formData.value.strikeThroughGroupMode)
      : false,
    strikeLineThickness: supportsAmountSetting.value
      ? Math.min(8, Math.max(0.5, parseFiniteNumber(formData.value.strikeLineThickness, 1.5)))
      : 1.5,
    isFillable: formData.value.isFillable ?? true,
    isAutoGenerated: Boolean(formData.value.type === 'Time' || formData.value.type === 'Date'),
  };
}

async function handleSubmit() {
  if (!formData.value.name) {
    toast.add({
      title: 'กรุณากรอกข้อมูลให้ครบ',
      color: 'error',
    });
    return;
  }

  isSubmitting.value = true;
  try {
    const payload = buildFieldPayload();
    const strikeModePayload = {
      strikeThroughGroupMode: Boolean(payload.strikeThroughGroupMode),
      strikeLineThickness: Math.min(8, Math.max(0.5, parseFiniteNumber(payload.strikeLineThickness, 1.5))),
    };

    if (props.mode === 'edit' && props.editField?.id) {
      // Update existing field
      const response = await $fetch(`/api/template-fields/${props.editField.id}`, {
        method: 'PUT',
        body: payload,
      });

      if (response.success) {
        toast.add({
          title: 'อัพเดท Field สำเร็จ',
          color: 'success',
        });
        emit('fieldUpdated', {
          ...response.data,
          ...strikeModePayload,
        });
        closeModal();
      }
      else {
        toast.add({
          title: 'เกิดข้อผิดพลาด',
          description: response.error,
          color: 'error',
        });
      }
    }
    else {
      // Create new field
      const response = await $fetch('/api/template-fields', {
        method: 'POST',
        body: payload,
      });

      if (response.success) {
        toast.add({
          title: 'สร้าง Field สำเร็จ',
          color: 'success',
        });
        emit('fieldCreated', {
          ...response.data,
          ...strikeModePayload,
        });
        closeModal();
      }
      else {
        toast.add({
          title: 'เกิดข้อผิดพลาด',
          description: response.error,
          color: 'error',
        });
      }
    }
  }
  catch (error) {
    console.error('Error submitting field:', error);
    toast.add({
      title: props.mode === 'edit' ? 'ไม่สามารถอัพเดท Field ได้' : 'ไม่สามารถสร้าง Field ได้',
      description: error.message,
      color: 'error',
    });
  }
  finally {
    isSubmitting.value = false;
  }
}

async function handleDelete() {
  if (!props.editField?.id)
    return;

  isDeleting.value = true;
  try {
    const response = await $fetch(`/api/template-fields/${props.editField.id}`, {
      method: 'DELETE',
    });

    if (response.success) {
      toast.add({
        title: 'ลบ Field สำเร็จ',
        color: 'success',
      });
      emit('fieldDeleted', props.editField.id);
      closeModal();
    }
    else {
      toast.add({
        title: 'เกิดข้อผิดพลาด',
        description: response.error,
        color: 'error',
      });
    }
  }
  catch (error) {
    console.error('Error deleting field:', error);
    toast.add({
      title: 'ไม่สามารถลบ Field ได้',
      description: error.message,
      color: 'error',
    });
  }
  finally {
    isDeleting.value = false;
    showDeleteConfirm.value = false;
  }
}
</script>

<template>
  <div v-if="isOpen" class="fixed inset-0 z-50 overflow-y-auto">
    <div class="flex min-h-screen items-center justify-center p-2">
      <div class="relative transform overflow-y-auto rounded-lg bg-white dark:bg-gray-900 text-left shadow-2xl transition-all sm:my-8 sm:w-full sm:max-w-sm max-h-[80vh]">
        <div class="bg-white dark:bg-gray-900 px-4 pb-3 pt-4 sm:px-4 sm:pb-3 sm:pt-4">
          <div class="flex items-center justify-between mb-2">
            <h3 class="text-xl font-bold leading-6 text-gray-900 dark:text-white">
              {{ mode === 'edit' ? 'แก้ไข Field' : 'เพิ่ม Field ใหม่' }}
            </h3>
            <button
              type="button"
              class="rounded-md text-gray-400 hover:text-gray-500 focus:outline-none"
              @click="closeModal"
            >
              <UIcon name="i-heroicons-x-mark-20-solid" class="h-6 w-6" />
            </button>
          </div>

          <div class="space-y-2">
            <!-- Field Name -->
            <div>
              <label class="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1.5">
                ชื่อ Field <span class="text-red-500">*</span>
              </label>
              <UInput
                v-model="formData.name"
                placeholder="เช่น Student Name"
                size="md"
              />
            </div>

            <!-- Field Type with icon preview -->
            <div class="grid grid-cols-1 gap-1.5">
              <div>
                <label class="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1.5">
                  ประเภท
                </label>
                <div class="flex items-center gap-3">
                  <select
                    v-model="formData.type"
                    class="w-full sm:w-40 rounded-md border-gray-300 dark:border-gray-700 dark:bg-gray-900 shadow-sm focus:border-primary-500 focus:ring-primary-500 px-3 py-2 text-sm"
                  >
                    <option v-for="type in fieldTypes" :key="type" :value="type">
                      {{ type }}
                    </option>
                  </select>

                  <div class="flex items-center gap-2 pl-2">
                    <div class="w-10 h-10 rounded-md flex items-center justify-center border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800">
                      <UIcon :name="formData.icon" class="w-5 h-5 text-gray-700 dark:text-gray-200" />
                    </div>
                    <div class="text-sm text-gray-600 dark:text-gray-300">
                      {{ formData.type }}
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!-- Font & Font Size -->
            <div v-if="supportsFontControls" class="grid grid-cols-2 gap-1.5">
              <div>
                <label class="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1.5">
                  ฟอนต์
                </label>
                <select
                  v-model="formData.font"
                  class="w-full sm:w-40 rounded-md border-gray-300 dark:border-gray-700 dark:bg-gray-900 shadow-sm focus:border-primary-500 focus:ring-primary-500 px-3 py-2 text-sm"
                >
                  <option v-for="font in fontOptions" :key="font" :value="font">
                    {{ font }}
                  </option>
                </select>
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1.5">
                  ขนาดฟอนต์
                </label>
                <UInput
                  v-model.number="formData.fontSize"
                  type="number"
                  min="8"
                  max="72"
                  size="md"
                />
              </div>
            </div>

            <!-- Width & Height -->
            <div class="grid grid-cols-3 gap-1.5">
              <div v-if="supportsAmountSetting">
                <label class="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1.5">
                  จำนวนชุด (amount)
                </label>
                <UInput
                  v-model.number="formData.amount"
                  type="number"
                  min="1"
                  max="20"
                  size="md"
                />
              </div>
              <div :class="supportsAmountSetting ? '' : 'col-span-2'">
                <label class="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1.5">
                  ความกว้าง (px)
                </label>
                <UInput
                  v-model.number="formData.width"
                  type="number"
                  min="10"
                  max="500"
                  size="md"
                />
              </div>
              <div :class="supportsAmountSetting ? '' : 'col-span-1'">
                <label class="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1.5">
                  ความสูง (px)
                </label>
                <UInput
                  v-model.number="formData.height"
                  type="number"
                  min="10"
                  max="500"
                  size="md"
                />
              </div>
            </div>

            <div v-if="supportsSessionFieldBinding">
              <label class="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1.5">
                การกรอกข้อมูลอัตโนมัติ
              </label>
              <select
                v-model="formData.sessionField"
                class="w-full rounded-md border-gray-300 dark:border-gray-700 dark:bg-gray-900 shadow-sm focus:border-primary-500 focus:ring-primary-500 px-3 py-2 text-sm"
              >
                <option value="none">
                  ให้ผู้ยื่นกรอกเอง
                </option>
                <option value="studentName">
                  ชื่อ-นามสกุลนักศึกษา (กรอกอัตโนมัติ)
                </option>
                <option value="studentId">
                  รหัสนิสิต (กรอกอัตโนมัติ)
                </option>
                <option value="studentYearCurrent">
                  ชั้นปีนิสิต (กรอกอัตโนมัติ)
                </option>
                <option value="facultyNameTh">
                  คณะ (กรอกอัตโนมัติ)
                </option>
                <option value="departmentNameTh">
                  สาขา (กรอกอัตโนมัติ)
                </option>
                <option value="departmentCode">
                  รหัสสาขา (กรอกอัตโนมัติ)
                </option>
              </select>
            </div>

            <div v-if="supportsAmountSetting" class="space-y-1.5 border-t border-gray-100 pt-2">
              <label class="flex items-center gap-2 text-sm font-medium text-gray-700 dark:text-gray-200">
                <input
                  v-model="formData.strikeThroughGroupMode"
                  type="checkbox"
                  class="h-4 w-4 rounded border-gray-300 text-primary-600 focus:ring-primary-500"
                  :disabled="Number(formData.amount) <= 1"
                >
                เปิดโหมดขีดฆ่าช่องที่ไม่ติ๊กในกลุ่ม
              </label>
              <div v-if="formData.strikeThroughGroupMode" class="max-w-44">
                <label class="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1.5">
                  ความหนาเส้นขีดฆ่า
                </label>
                <UInput
                  v-model.number="formData.strikeLineThickness"
                  type="number"
                  min="0.5"
                  max="8"
                  step="0.1"
                  size="md"
                />
              </div>
            </div>

            <!-- Text styling controls (mirror field-toolbar options) -->
            <div v-if="supportsTextSettings" class="space-y-2 border-t border-gray-100 pt-2.5">
              <div class="grid grid-cols-2 gap-1.5">
                <div>
                  <label class="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1.5">
                    รูปแบบตัวอักษร
                  </label>
                  <div class="flex items-center gap-1.5">
                    <button
                      type="button"
                      class="h-8 w-8 rounded-md border text-sm font-semibold transition-colors"
                      :class="formData.fontWeight === 'bold' ? 'border-primary-500 bg-primary-50 text-primary-700' : 'border-gray-300 text-gray-600 hover:bg-gray-50'"
                      @click="formData.fontWeight = formData.fontWeight === 'bold' ? 'normal' : 'bold'"
                    >
                      B
                    </button>
                    <button
                      type="button"
                      class="h-8 w-8 rounded-md border text-sm italic transition-colors"
                      :class="formData.fontStyle === 'italic' ? 'border-primary-500 bg-primary-50 text-primary-700' : 'border-gray-300 text-gray-600 hover:bg-gray-50'"
                      @click="formData.fontStyle = formData.fontStyle === 'italic' ? 'normal' : 'italic'"
                    >
                      I
                    </button>
                    <button
                      type="button"
                      class="h-8 w-8 rounded-md border text-sm underline transition-colors"
                      :class="formData.textDecoration === 'underline' ? 'border-primary-500 bg-primary-50 text-primary-700' : 'border-gray-300 text-gray-600 hover:bg-gray-50'"
                      @click="formData.textDecoration = formData.textDecoration === 'underline' ? 'none' : 'underline'"
                    >
                      U
                    </button>
                  </div>
                </div>

                <div>
                  <label class="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1.5">
                    จัดตำแหน่งข้อความ
                  </label>
                  <div class="flex items-center gap-1.5">
                    <button
                      type="button"
                      class="h-8 w-8 rounded-md border transition-colors"
                      :class="formData.textAlign === 'left' ? 'border-primary-500 bg-primary-50 text-primary-700' : 'border-gray-300 text-gray-600 hover:bg-gray-50'"
                      @click="formData.textAlign = 'left'"
                    >
                      <UIcon name="i-heroicons-bars-3-bottom-left" class="w-3.5 h-3.5 mx-auto" />
                    </button>
                    <button
                      type="button"
                      class="h-8 w-8 rounded-md border transition-colors"
                      :class="formData.textAlign === 'center' ? 'border-primary-500 bg-primary-50 text-primary-700' : 'border-gray-300 text-gray-600 hover:bg-gray-50'"
                      @click="formData.textAlign = 'center'"
                    >
                      <UIcon name="i-heroicons-bars-3" class="w-3.5 h-3.5 mx-auto" />
                    </button>
                    <button
                      type="button"
                      class="h-8 w-8 rounded-md border transition-colors"
                      :class="formData.textAlign === 'right' ? 'border-primary-500 bg-primary-50 text-primary-700' : 'border-gray-300 text-gray-600 hover:bg-gray-50'"
                      @click="formData.textAlign = 'right'"
                    >
                      <UIcon name="i-heroicons-bars-3-bottom-right" class="w-3.5 h-3.5 mx-auto" />
                    </button>
                  </div>
                </div>
              </div>

              <div class="grid grid-cols-2 gap-1.5">
                <div v-if="supportsLetterSpacing">
                  <label class="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1.5">
                    ระยะห่างตัวอักษร
                  </label>
                  <UInput
                    v-model.number="formData.letterSpacing"
                    type="number"
                    min="-5"
                    max="20"
                    step="0.5"
                    size="md"
                  />
                </div>
                <div :class="supportsLetterSpacing ? '' : 'col-span-2'">
                  <label class="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1.5">
                    ความห่างบรรทัด
                  </label>
                  <UInput
                    v-model.number="formData.lineHeight"
                    type="number"
                    min="0.5"
                    max="5"
                    step="0.1"
                    size="md"
                  />
                </div>
              </div>

              <div v-if="supportsMaxLength">
                <label class="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1.5">
                  จำนวนตัวอักษรสูงสุด
                </label>
                <UInput
                  v-model.number="formData.maxLength"
                  type="number"
                  min="1"
                  max="5000"
                  step="1"
                  placeholder="∞"
                  size="md"
                />
              </div>
            </div>
          </div>
        </div>

        <div class="bg-gray-50 dark:bg-gray-800 px-3 py-2.5 sm:flex sm:flex-row-reverse sm:px-4 gap-2">
          <UButton
            :loading="isSubmitting"
            :label="mode === 'edit' ? 'บันทึก' : 'สร้าง Field'"
            @click="handleSubmit"
          />
          <UButton
            color="gray"
            variant="outline"
            label="ยกเลิก"
            @click="closeModal"
          />
          <UButton
            v-if="mode === 'edit'"
            color="red"
            label="ลบ"
            :loading="isDeleting"
            @click="showDeleteConfirm = true"
          />
        </div>
      </div>
    </div>

    <!-- Delete Confirmation Modal -->
    <div v-if="showDeleteConfirm" class="fixed inset-0 overflow-y-auto">
      <div class="flex min-h-screen items-center justify-center p-4">
        <div class="relative transform overflow-hidden rounded-lg bg-white dark:bg-gray-900 text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-md">
          <div class="bg-white dark:bg-gray-900 px-4 pb-4 pt-5 sm:p-6">
            <div class="sm:flex sm:items-start">
              <div class="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-red-100 sm:mx-0 sm:h-10 sm:w-10">
                <UIcon name="i-heroicons-exclamation-triangle" class="h-6 w-6 text-red-600" />
              </div>
              <div class="mt-3 text-center sm:ml-4 sm:mt-0 sm:text-left">
                <h3 class="text-lg font-semibold leading-6 text-gray-900 dark:text-white">
                  ยืนยันการลบ
                </h3>
                <div class="mt-2">
                  <p class="text-sm text-gray-500 dark:text-gray-400">
                    คุณต้องการลบ Field "{{ editField?.name }}" หรือไม่? การกระทำนี้ไม่สามารถย้อนกลับได้
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div class="bg-gray-50 dark:bg-gray-800 px-4 py-3 sm:flex sm:flex-row-reverse sm:px-6 gap-3">
            <UButton
              color="red"
              :loading="isDeleting"
              label="ลบ"
              @click="handleDelete"
            />
            <UButton
              color="gray"
              variant="outline"
              label="ยกเลิก"
              @click="showDeleteConfirm = false"
            />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
