<script setup lang="ts">
import type { FieldInstance, FileTypeValue, SigningStep } from '~/types/template';

import { SIGNER_COLORS } from '~/types/template';

const props = defineProps<{
  signingSteps: SigningStep[];
  placedFields: FieldInstance[];
  pdfFile: File | null;
  fileType: FileTypeValue;
  uiScale: number;
}>();

const emit = defineEmits<{
  'update:signingSteps': [steps: SigningStep[]];
  'update:placedFields': [fields: FieldInstance[]];
}>();

const { t, locale } = useI18n();

// Local state
const selectedStepId = ref<string | null>(null);
const isAddingStep = ref(false);
const newStepRoleId = ref<number | undefined>(undefined);
const newStepIsRequired = ref(true);

// Fetch roles from database
type RoleRecord = { id: number; name: string; descriptionEn: string | null; descriptionTh: string | null };
const roles = ref<RoleRecord[]>([]);
const isLoadingRoles = ref(false);

function getRoleDescription(role: RoleRecord | null | undefined): string | undefined {
  if (!role)
    return undefined;
  return (locale.value === 'th' ? role.descriptionTh : role.descriptionEn) ?? role.descriptionEn ?? undefined;
}

async function fetchRoles(): Promise<void> {
  isLoadingRoles.value = true;
  try {
    const data = await $fetch<RoleRecord[]>('/api/roles');
    roles.value = data;
  }
  catch (error) {
    console.error('Failed to fetch roles:', error);
  }
  finally {
    isLoadingRoles.value = false;
  }
}

onMounted(async () => {
  await fetchRoles();
});

// Roles formatted for USelect (Shows Description, falls back to Name)
const roleItems = computed(() => {
  return roles.value.map(r => ({
    label: getRoleDescription(r) || r.name,
    value: r.id,
  }));
});

// Selected role object (for auto-filling description)
const selectedNewRole = computed(() => {
  if (!newStepRoleId.value)
    return null;
  return roles.value.find(r => r.id === newStepRoleId.value) ?? null;
});

// Computed
const selectedStep = computed<SigningStep | null>(() => {
  if (!selectedStepId.value)
    return null;
  return props.signingSteps.find(s => s.id === selectedStepId.value) || null;
});

function getFieldType(field: FieldInstance): string {
  return String((field as any)?.type || field?.fieldType || '').toLowerCase();
}

function isStrictlyAutoGeneratedField(field: FieldInstance): boolean {
  const fieldType = getFieldType(field);

  // Date fields with isAutoGenerate are assignable — they stamp the date at the
  // moment the assigned step is completed. Do NOT treat them as non-assignable.
  if (fieldType === 'date') {
    return false;
  }

  // Time fields with isAutoGenerate are also assignable for the same reason.
  if (fieldType === 'time') {
    return false;
  }

  // All other fields that carry the auto-generate flag remain non-assignable.
  return (field as any).isAutoGenerate === true
    || (field as any).isAutoGenerated === true
    || (field as any).is_auto_generated === true;
}

/**
 * Returns true when the field is a date or time field that will be
 * auto-populated — used purely for display (badge / icon) in the UI so users
 * understand the field value is generated automatically at the step's completion.
 */
function isAutoGeneratedDateOrTimeField(field: FieldInstance): boolean {
  const fieldType = getFieldType(field);

  if (fieldType === 'time') {
    return true;
  }

  if (fieldType === 'date') {
    return (field as any).isAutoGenerate === true
      || (field as any).isAutoGenerated === true
      || (field as any).is_auto_generated === true;
  }

  return false;
}

/**
 * Icon helper for field type display.
 */
function getFieldTypeIcon(field: FieldInstance): string {
  const fieldType = getFieldType(field);
  if (fieldType === 'date')
    return 'i-heroicons-calendar-days';
  if (fieldType === 'time')
    return 'i-heroicons-clock';
  if (fieldType === 'signature')
    return 'i-heroicons-pencil';
  if (fieldType === 'checkbox')
    return 'i-heroicons-check-circle';
  return 'i-heroicons-document-text';
}

// Unassigned fields: exclude only strictly-auto-generated fields (NOT date/time)
const unassignedFields = computed<FieldInstance[]>(() => {
  return props.placedFields.filter(f => !f.signerStepId && !isStrictlyAutoGeneratedField(f));
});

const assignedFieldsForSelectedStep = computed<FieldInstance[]>(() => {
  if (!selectedStepId.value)
    return [];
  return props.placedFields.filter(f => f.signerStepId === selectedStepId.value);
});

const unassignedCount = computed(() => unassignedFields.value.length);

// ── Stage / parallel-group helpers ────────────────────────────────────────

/**
 * Returns steps grouped by their order number, sorted ascending.
 * Steps that share the same order belong to the same parallel stage.
 */
const stages = computed(() => {
  const groups = new Map<number, SigningStep[]>();
  for (const step of props.signingSteps) {
    const group = groups.get(step.order) ?? [];
    group.push(step);
    groups.set(step.order, group);
  }
  return Array.from(groups.entries())
    .sort((a, b) => a[0] - b[0])
    .map(([order, steps]) => ({ order, steps }));
});

/** Sorted unique order-numbers (one per stage). */
const stageOrders = computed(() => stages.value.map(s => s.order));

// Which stage the "add step" form is targeting.
// null  → new sequential stage
// number → parallel to that stage's order
const addingToStageOrder = ref<number | null>(null);

function openAddStepForm(toStageOrder: number | null): void {
  addingToStageOrder.value = toStageOrder;
  isAddingStep.value = true;
  newStepRoleId.value = undefined;
  newStepIsRequired.value = true;
}

// Get the next available color
function getNextColor(): string {
  const usedColors = props.signingSteps.map(s => s.color);
  const available = SIGNER_COLORS.filter(c => !usedColors.includes(c));
  return available.length > 0 ? available[0]! : SIGNER_COLORS[props.signingSteps.length % SIGNER_COLORS.length]!;
}

// Add a new signing step (parallel to addingToStageOrder, or new sequential stage)
function addStep(): void {
  if (!selectedNewRole.value)
    return;

  // Capture role info before resetting form
  const role = selectedNewRole.value;

  const maxOrder = props.signingSteps.length > 0
    ? Math.max(...props.signingSteps.map(s => s.order))
    : 0;
  const targetOrder = addingToStageOrder.value ?? (maxOrder + 1);

  const newStep: SigningStep = {
    id: `step_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
    order: targetOrder,
    roleId: role.id,
    roleName: role.name,
    description: getRoleDescription(role) || undefined,
    isRequired: newStepIsRequired.value,
    assignedFieldInstanceIds: [],
    color: getNextColor(),
  };

  const updatedSteps = [...props.signingSteps, newStep];
  emit('update:signingSteps', updatedSteps);

  // Reset form
  newStepRoleId.value = undefined;
  newStepIsRequired.value = true;
  isAddingStep.value = false;
  addingToStageOrder.value = null;

  // Auto-select the new step
  selectedStepId.value = newStep.id;
}

// Remove a signing step (parallel-aware)
function removeStep(stepId: string): void {
  const stepToRemove = props.signingSteps.find(s => s.id === stepId);
  if (!stepToRemove)
    return;

  // Unassign all fields from this step
  const updatedFields = props.placedFields.map((f) => {
    if (f.signerStepId === stepId)
      return { ...f, signerStepId: undefined };
    return f;
  });
  emit('update:placedFields', updatedFields);

  const remaining = props.signingSteps.filter(s => s.id !== stepId);

  // If the stage still has other steps, remove without re-numbering.
  // If the stage is now empty, collapse it by decrementing later stages.
  const stageStillHasSteps = remaining.some(s => s.order === stepToRemove.order);
  const updatedSteps = stageStillHasSteps
    ? remaining
    : remaining.map(s => s.order > stepToRemove.order ? { ...s, order: s.order - 1 } : s);

  emit('update:signingSteps', updatedSteps);

  if (selectedStepId.value === stepId) {
    selectedStepId.value = updatedSteps.length > 0 ? updatedSteps[0]!.id : null;
  }
}

// Move an entire stage up (swap its order with the previous stage)
function moveStageUp(stageOrder: number): void {
  const idx = stageOrders.value.indexOf(stageOrder);
  if (idx <= 0)
    return;
  const prevOrder = stageOrders.value[idx - 1]!;
  const updatedSteps = props.signingSteps.map((s) => {
    if (s.order === stageOrder)
      return { ...s, order: prevOrder };
    if (s.order === prevOrder)
      return { ...s, order: stageOrder };
    return s;
  });
  emit('update:signingSteps', updatedSteps);
}

// Move an entire stage down (swap its order with the next stage)
function moveStageDown(stageOrder: number): void {
  const idx = stageOrders.value.indexOf(stageOrder);
  if (idx < 0 || idx >= stageOrders.value.length - 1)
    return;
  const nextOrder = stageOrders.value[idx + 1]!;
  const updatedSteps = props.signingSteps.map((s) => {
    if (s.order === stageOrder)
      return { ...s, order: nextOrder };
    if (s.order === nextOrder)
      return { ...s, order: stageOrder };
    return s;
  });
  emit('update:signingSteps', updatedSteps);
}

// Handle field click from PDF preview — assign/unassign to selected step
function handleFieldClicked(field: FieldInstance): void {
  if (!selectedStepId.value)
    return;
  // Allow date/time auto-generated fields to be toggled; only block strictly
  // auto-generated non-date/time fields.
  if (isStrictlyAutoGeneratedField(field))
    return;

  const updatedFields = props.placedFields.map((f) => {
    if (f.instanceId === field.instanceId) {
      // Toggle: if already assigned to this step, unassign; otherwise assign
      const newSignerStepId = f.signerStepId === selectedStepId.value ? undefined : selectedStepId.value;
      return { ...f, signerStepId: newSignerStepId };
    }
    return f;
  }) as FieldInstance[];
  emit('update:placedFields', updatedFields);

  // Update step's assignedFieldInstanceIds
  syncStepFieldIds(updatedFields);
}

// Assign a field from the right panel
function assignFieldToStep(fieldInstanceId: string): void {
  if (!selectedStepId.value)
    return;

  const targetField = props.placedFields.find(f => f.instanceId === fieldInstanceId);
  // Allow date/time auto-generated fields; only block strictly auto-generated ones
  if (!targetField || isStrictlyAutoGeneratedField(targetField))
    return;

  const updatedFields = props.placedFields.map((f) => {
    if (f.instanceId === fieldInstanceId) {
      return { ...f, signerStepId: selectedStepId.value! };
    }
    return f;
  }) as FieldInstance[];
  emit('update:placedFields', updatedFields);
  syncStepFieldIds(updatedFields);
}

// Unassign a field from the selected step
function unassignFieldFromStep(fieldInstanceId: string): void {
  const updatedFields = props.placedFields.map((f) => {
    if (f.instanceId === fieldInstanceId) {
      return { ...f, signerStepId: undefined };
    }
    return f;
  }) as FieldInstance[];
  emit('update:placedFields', updatedFields);
  syncStepFieldIds(updatedFields);
}

// Sync assignedFieldInstanceIds on all steps
function syncStepFieldIds(fields: FieldInstance[]): void {
  const updatedSteps = props.signingSteps.map(step => ({
    ...step,
    assignedFieldInstanceIds: fields
      .filter(f => f.signerStepId === step.id)
      .map(f => f.instanceId),
  }));
  emit('update:signingSteps', updatedSteps);
}

// Select first step by default when steps exist
watch(() => props.signingSteps.length, (newLen) => {
  if (newLen > 0 && !selectedStepId.value) {
    selectedStepId.value = props.signingSteps[0]!.id;
  }
}, { immediate: true });
</script>

<template>
  <div class="flex-1 flex overflow-hidden">
    <!-- LEFT PANEL: Signing Steps List -->
    <aside class="w-72 flex flex-col shrink-0 z-10 border-r border-gray-200">
      <div class="p-4 border-b">
        <h3 class="font-bold flex items-center gap-2">
          <UIcon name="i-heroicons-queue-list" class="text-primary-500" />
          {{ t('signingFlow') }}
        </h3>
      </div>

      <div class="overflow-y-auto flex-1 p-4 space-y-3">
        <!-- Stage Groups (parallel-aware) -->
        <div
          v-for="(stage, stageIndex) in stages"
          :key="stage.order"
          class="rounded-lg border border-gray-200 overflow-hidden"
        >
          <!-- Stage header -->
          <div class="bg-gray-50 border-b border-gray-200 px-3 py-1.5 flex items-center justify-between gap-2">
            <div class="flex items-center gap-1.5 min-w-0">
              <span class="text-xs font-semibold text-gray-500 uppercase shrink-0">
                {{ t('stage') }} {{ stageIndex + 1 }}
              </span>
              <UBadge
                v-if="stage.steps.length > 1"
                color="info"
                variant="subtle"
                size="xs"
                icon="i-heroicons-arrows-right-left"
                class="shrink-0"
              >
                {{ t('parallel') }}
              </UBadge>
            </div>
            <div class="flex items-center gap-0.5 shrink-0">
              <UButton
                icon="i-heroicons-chevron-up"
                size="xs"
                color="neutral"
                variant="ghost"
                :disabled="stageIndex === 0"
                @click="moveStageUp(stage.order)"
              />
              <UButton
                icon="i-heroicons-chevron-down"
                size="xs"
                color="neutral"
                variant="ghost"
                :disabled="stageIndex === stages.length - 1"
                @click="moveStageDown(stage.order)"
              />
            </div>
          </div>

          <!-- Steps within this stage -->
          <div class="p-2 space-y-1.5">
            <div
              v-for="step in stage.steps"
              :key="step.id"
              class="rounded-md border-2 p-2.5 cursor-pointer transition-all hover:shadow-sm"
              :class="selectedStepId === step.id
                ? 'border-primary-500 bg-primary-50'
                : 'border-gray-200 bg-white hover:border-gray-300'"
              @click="selectedStepId = step.id"
            >
              <div class="flex items-start justify-between gap-1.5">
                <div class="flex items-center gap-1.5 min-w-0 flex-1">
                  <span
                    class="w-5 h-5 rounded-full flex items-center justify-center text-white text-xs font-bold shrink-0"
                    :style="{ backgroundColor: step.color }"
                  >
                    {{ stageIndex + 1 }}
                  </span>
                  <div class="min-w-0 flex-1">
                    <p class="font-semibold text-sm text-gray-900 truncate">
                      {{ step.description || step.roleName }}
                    </p>
                  </div>
                </div>
                <UButton
                  icon="i-heroicons-trash"
                  size="xs"
                  color="error"
                  variant="ghost"
                  @click.stop="removeStep(step.id)"
                />
              </div>
              <div class="mt-1.5 flex items-center gap-1.5 flex-wrap">
                <UBadge color="neutral" variant="subtle" size="xs">
                  {{ step.assignedFieldInstanceIds.length }} {{ t('fields') }}
                </UBadge>
              </div>
            </div>

            <!-- Add parallel signer form (inline within stage) -->
            <div
              v-if="isAddingStep && addingToStageOrder === stage.order"
              class="rounded-md border-2 border-dashed border-info-300 bg-info-50 p-2.5 space-y-2"
            >
              <p class="text-xs font-semibold text-info-600 flex items-center gap-1">
                <UIcon name="i-heroicons-arrows-right-left" class="w-3.5 h-3.5" />
                {{ t('addParallelSigner') }}
              </p>
              <USelect
                v-model="newStepRoleId"
                :items="roleItems"
                :placeholder="t('selectRole')"
                value-key="value"
                label-key="label"
                size="sm"
                :loading="isLoadingRoles"
                icon="i-heroicons-user-circle"
                class="w-full"
              />
              <div class="flex items-center justify-end gap-1">
                <UButton
                  size="xs"
                  color="neutral"
                  variant="ghost"
                  :label="t('cancel')"
                  @click="isAddingStep = false; newStepRoleId = undefined; addingToStageOrder = null"
                />
                <UButton
                  size="xs"
                  color="info"
                  :label="t('add')"
                  :disabled="!newStepRoleId"
                  @click="addStep"
                />
              </div>
            </div>

            <!-- Add parallel signer button (only when not already adding to this stage) -->
            <UButton
              v-if="!(isAddingStep && addingToStageOrder === stage.order)"
              icon="i-heroicons-arrows-right-left"
              :label="t('addParallelSigner')"
              color="info"
              variant="ghost"
              size="xs"
              block
              @click="openAddStepForm(stage.order)"
            />
          </div>
        </div>

        <!-- Add New Stage form (sequential) -->
        <div v-if="isAddingStep && addingToStageOrder === null" class="rounded-lg border-2 border-dashed border-primary-300 bg-primary-50 p-3 space-y-2">
          <p class="text-xs font-semibold text-primary-600 flex items-center gap-1">
            <UIcon name="i-heroicons-queue-list" class="w-3.5 h-3.5" />
            {{ t('addNewStage') }}
          </p>
          <USelect
            v-model="newStepRoleId"
            :items="roleItems"
            :placeholder="t('selectRole')"
            value-key="value"
            label-key="label"
            size="sm"
            :loading="isLoadingRoles"
            icon="i-heroicons-user-circle"
            class="w-full"
          />
          <div class="flex items-center justify-end mt-2">
            <div class="flex gap-1">
              <UButton
                size="xs"
                color="neutral"
                variant="ghost"
                :label="t('cancel')"
                @click="isAddingStep = false; newStepRoleId = undefined; addingToStageOrder = null"
              />
              <UButton
                size="xs"
                color="primary"
                :label="t('addSigningStep')"
                :disabled="!newStepRoleId"
                @click="addStep"
              />
            </div>
          </div>
        </div>

        <!-- Add New Stage Button -->
        <UButton
          v-if="!isAddingStep"
          icon="i-heroicons-plus"
          :label="t('addNewStage')"
          color="primary"
          variant="soft"
          block
          @click="openAddStepForm(null)"
        />
      </div>
    </aside>

    <!-- CENTER: PDF Preview (read-only mode) -->
    <section class="flex-1 flex flex-col overflow-hidden bg-gray-100">
      <div class="p-3 border-b bg-white flex items-center gap-2 text-xs text-gray-500">
        <UIcon name="i-heroicons-cursor-arrow-rays" class="text-primary-500" />
        {{ t('clickFieldOnDocumentToAssign') }}
      </div>

      <!-- Scrollable Canvas (read-only mode) -->
      <div class="flex-1 overflow-auto p-8 flex justify-center items-start">
        <template-pdf-create
          v-if="fileType === 'pdf' && pdfFile"
          :pdf-file="pdfFile"
          :placed-fields="placedFields"
          :ui-scale="uiScale"
          :read-only="true"
          :signing-steps="signingSteps"
          @field-clicked="handleFieldClicked"
        />
      </div>
    </section>

    <!-- RIGHT PANEL: Step Details & Field Assignment -->
    <aside class="w-64 flex flex-col shrink-0 z-10 border-l border-gray-200">
      <div class="p-4 border-b">
        <h3 class="font-bold flex items-center gap-2">
          <UIcon name="i-heroicons-adjustments-horizontal" class="text-primary-500" />
          {{ t('stepDetails') }}
        </h3>
      </div>

      <div v-if="selectedStep" class="overflow-y-auto flex-1 p-4 space-y-4">
        <!-- Selected Step Info -->
        <div class="space-y-2">
          <div class="flex items-center gap-2">
            <span
              class="w-6 h-6 rounded-full flex items-center justify-center text-white text-xs font-bold"
              :style="{ backgroundColor: selectedStep.color }"
            >
              {{ stageOrders.indexOf(selectedStep.order) + 1 }}
            </span>
            <span class="font-semibold text-sm">{{ selectedStep.roleName }}</span>
          </div>
          <p v-if="selectedStep.description" class="text-xs text-gray-500">
            {{ selectedStep.description }}
          </p>
          <div class="flex items-center gap-1 flex-wrap">
            <UBadge color="neutral" variant="outline" size="xs">
              {{ t('stage') }} {{ stageOrders.indexOf(selectedStep.order) + 1 }}
            </UBadge>
            <UBadge
              v-if="(stages.find(s => s.order === selectedStep.order)?.steps.length ?? 0) > 1"
              color="info"
              variant="subtle"
              size="xs"
              icon="i-heroicons-arrows-right-left"
            >
              {{ t('parallel') }}
            </UBadge>
          </div>
        </div>

        <!-- Assigned Fields -->
        <div>
          <label class="text-xs font-semibold text-gray-500 uppercase mb-2 block">
            {{ t('assignedFields') }} ({{ assignedFieldsForSelectedStep.length }})
          </label>
          <div class="space-y-1.5">
            <div
              v-for="field in assignedFieldsForSelectedStep"
              :key="field.instanceId"
              class="flex items-center justify-between p-2 rounded-md bg-white border border-gray-200"
            >
              <div class="flex items-center gap-2 min-w-0 flex-1">
                <!-- Color dot matches the step -->
                <div
                  class="w-2 h-2 rounded-full shrink-0"
                  :style="{ backgroundColor: selectedStep.color }"
                />
                <!-- Field type icon -->
                <UIcon
                  :name="getFieldTypeIcon(field)"
                  class="w-3.5 h-3.5 shrink-0 text-gray-400"
                />
                <span class="text-xs text-gray-700 truncate">{{ field.label || field.name }}</span>
                <!-- Auto-generated badge for date/time fields -->
                <UBadge
                  v-if="isAutoGeneratedDateOrTimeField(field)"
                  color="info"
                  variant="subtle"
                  size="xs"
                  class="shrink-0"
                >
                  {{ t('auto') }}
                </UBadge>
              </div>
              <UButton
                icon="i-heroicons-x-mark"
                size="xs"
                color="error"
                variant="ghost"
                @click="unassignFieldFromStep(field.instanceId)"
              />
            </div>
            <p v-if="assignedFieldsForSelectedStep.length === 0" class="text-xs text-gray-400 text-center py-2">
              {{ t('clickFieldToAssign') }}
            </p>
          </div>
        </div>

        <!-- Unassigned Fields -->
        <div>
          <label class="text-xs font-semibold text-gray-500 uppercase mb-2 block">
            {{ t('unassignedFields') }} ({{ unassignedCount }})
          </label>
          <div class="space-y-1.5">
            <div
              v-for="field in unassignedFields"
              :key="field.instanceId"
              class="flex items-center justify-between p-2 rounded-md bg-gray-50 border border-dashed border-gray-300 hover:border-primary-400 hover:bg-primary-50 cursor-pointer transition-colors"
              @click="assignFieldToStep(field.instanceId)"
            >
              <div class="flex items-center gap-2 min-w-0 flex-1">
                <div class="w-2 h-2 rounded-full bg-gray-300 shrink-0" />
                <!-- Field type icon -->
                <UIcon
                  :name="getFieldTypeIcon(field)"
                  class="w-3.5 h-3.5 shrink-0 text-gray-400"
                />
                <span class="text-xs text-gray-600 truncate">{{ field.label || field.name }}</span>
                <!-- Auto-generated badge for date/time fields in the unassigned list -->
                <UBadge
                  v-if="isAutoGeneratedDateOrTimeField(field)"
                  color="info"
                  variant="subtle"
                  size="xs"
                  class="shrink-0"
                >
                  {{ t('auto') }}
                </UBadge>
              </div>
              <UIcon name="i-heroicons-plus-circle" class="w-4 h-4 text-gray-400 shrink-0" />
            </div>
          </div>
        </div>
      </div>

      <!-- No Step Selected -->
      <div v-else class="flex-1 flex items-center justify-center p-4">
        <p class="text-sm text-gray-400 text-center">
          {{ signingSteps.length > 0 ? t('clickFieldToAssign') : t('addFirstStep') }}
        </p>
      </div>
    </aside>
  </div>
</template>
