import db from '~~/lib/db';
import { request, requestTemplate, requestTemplateValues, signatureFlow, signatures, userRoles } from '~~/lib/db/schema';
import { resolveAutoGeneratedDateTimeValue } from '~~/shared/auto-date-time-format';
import { and, asc, eq } from 'drizzle-orm';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

/**
 * Builds a filled PDF in memory (same output as POST generate-filled-pdf) without uploading.
 * Used to avoid an extra round-trip + re-fetch when signing immediately after saving field values.
 */
export async function buildFilledPdfBytesForRequest(
  requestId: number,
  userId: string,
  options?: {
    /**
     * Incremental mode: only render these field instance IDs on top of basePdfUrl.
     * Previous signatures and field data already baked into basePdfUrl are preserved.
     * When omitted, all fields are rendered (full rebuild mode).
     */
    fieldInstanceIdFilter?: string[];
    /**
     * Incremental mode: base PDF URL to load instead of the clean template.
     * Typically requestRecord.filledDocumentUrl from the previous step.
     */
    basePdfUrl?: string;
  },
): Promise<{ success: true; bytes: Uint8Array } | { success: false; error: string }> {
  const isIncrementalMode = Array.isArray(options?.fieldInstanceIdFilter) && !!options?.basePdfUrl;
  const requestData = await db
    .select()
    .from(request)
    .where(eq(request.id, requestId))
    .limit(1);

  const requestRecord = requestData[0];
  if (!requestRecord) {
    return { success: false, error: 'Request not found' };
  }

  const isOwner = requestRecord.userId === userId;

  let isAuthorizedSigner = false;
  if (!isOwner) {
    const userRoleRows = await db
      .select({ roleId: userRoles.roleId })
      .from(userRoles)
      .where(eq(userRoles.userId, userId));
    const userRoleIds = userRoleRows.map(r => r.roleId);

    const [pendingFlow] = await db
      .select()
      .from(signatureFlow)
      .where(and(
        eq(signatureFlow.requestId, requestId),
        eq(signatureFlow.status, 'pending'),
      ))
      .orderBy(asc(signatureFlow.stepOrder))
      .limit(1);

    if (pendingFlow) {
      isAuthorizedSigner = pendingFlow.assignedUserId === userId
        || (pendingFlow.assignedUserId === null && userRoleIds.includes(pendingFlow.roleId));
    }
  }

  if (!isOwner && !isAuthorizedSigner) {
    return { success: false, error: 'Forbidden' };
  }

  const templateData = await db
    .select()
    .from(requestTemplate)
    .where(eq(requestTemplate.id, Number(requestRecord.templateId)))
    .limit(1);

  const template = templateData[0];
  if (!template) {
    return { success: false, error: 'Template not found' };
  }

  const fieldValuesData = await db
    .select()
    .from(requestTemplateValues)
    .where(eq(requestTemplateValues.requestId, requestId));

  const fieldValuesMap = new Map<string, string>();
  fieldValuesData.forEach((fv) => {
    const fieldId = Number.parseInt(String(fv.fieldId ?? ''), 10);
    if (!Number.isFinite(fieldId) || fieldId <= 0) {
      return;
    }
    const normalizedInstanceId = String(fv.fieldInstanceId ?? '').trim();
    if (normalizedInstanceId.length > 0) {
      fieldValuesMap.set(getFieldValueStorageKey(fieldId, normalizedInstanceId), fv.value || '');
    }
    else {
      fieldValuesMap.set(getFieldValueStorageKey(fieldId), fv.value || '');
    }
  });

  const sourcePdfUrl = isIncrementalMode ? options!.basePdfUrl! : template.documentUrl;
  if (!sourcePdfUrl) {
    return { success: false, error: 'Source PDF URL not found' };
  }

  if (!requestRecord.templateId) {
    return { success: false, error: 'Template ID not found in request' };
  }

  const pdfResponse = await fetch(sourcePdfUrl);
  if (!pdfResponse.ok) {
    return { success: false, error: 'Failed to fetch source PDF' };
  }

  const pdfArrayBuffer = await pdfResponse.arrayBuffer();
  const pdfBytes = new Uint8Array(pdfArrayBuffer);

  const placedFields = (template.placedFieldsData as any[]) || [];

  function resolveFieldInputValue(field: any): string {
    const manualFieldValue = applyFieldCharacterLimit(getStoredFieldValue(fieldValuesMap, field), field).trim();

    if (isAutoGeneratedDateOrTimeField(field)) {
      if (manualFieldValue) {
        return manualFieldValue;
      }
      return applyFieldCharacterLimit(resolveAutoGeneratedDateTimeValue(field), field).trim();
    }

    return manualFieldValue;
  }

  function isFieldVisible(field: any): boolean {
    const rule = getVisibilityRule(field);
    if (!rule || rule.enabled === false) {
      return true;
    }

    let isChecked = false;
    if (rule.sourceGroupId) {
      const groupFields = placedFields.filter((candidate) => {
        return isCheckboxField(candidate) && String(candidate?.groupId ?? '').trim() === rule.sourceGroupId;
      });
      isChecked = groupFields.some(candidate => normalizeCheckboxValue(resolveFieldInputValue(candidate)) === 'true');
    }
    else {
      const sourceField = placedFields.find(
        candidate => String(candidate?.instanceId ?? '').trim() === String(rule.sourceFieldInstanceId ?? ''),
      );

      if (!sourceField) {
        return true;
      }

      const sourceValue = normalizeCheckboxValue(resolveFieldInputValue(sourceField));
      isChecked = sourceValue === 'true';
    }
    return rule.operator === 'isUnchecked' ? !isChecked : isChecked;
  }

  const fieldsWithValues = placedFields
    .filter((field) => {
      if (!isFieldVisible(field))
        return false;
      // In incremental mode, only render fields assigned to the current step.
      // All other fields are already baked into the base PDF.
      if (isIncrementalMode) {
        return options!.fieldInstanceIdFilter!.includes(String(field?.instanceId ?? '').trim());
      }
      return true;
    })
    .map((field: any) => {
      const resolvedValue = resolveFieldInputValue(field);
      const fieldValue = isCheckboxField(field)
        ? normalizeCheckboxValue(resolvedValue)
        : resolvedValue;

      return {
        ...field,
        label: fieldValue,
        value: fieldValue,
      };
    });

  const filledPdfBytes = await generateFilledPdf(pdfBytes, fieldsWithValues, template);

  if (!filledPdfBytes) {
    return { success: false, error: 'Failed to generate filled PDF' };
  }

  // In incremental mode the base PDF (filledDocumentUrl) already contains all
  // previous signatures baked in as graphics, so no re-embedding is needed.
  if (isIncrementalMode) {
    return { success: true, bytes: filledPdfBytes };
  }

  // Full rebuild mode: re-embed all previously recorded signatures from the
  // signatures table because we started from the clean template and the
  // signature images are not stored in requestTemplateValues.
  const previousSignatures = await db
    .select()
    .from(signatures)
    .where(eq(signatures.requestId, requestId));

  if (previousSignatures.length === 0) {
    return { success: true, bytes: filledPdfBytes };
  }

  try {
    const PDFLib = await import('pdf-lib');
    const pdfDoc = await PDFLib.PDFDocument.load(filledPdfBytes);
    const pages = pdfDoc.getPages();

    for (const sig of previousSignatures) {
      if (!sig.dataUrl || !sig.fieldInstanceId)
        continue;

      const field = placedFields.find(
        (f: any) => String(f?.instanceId ?? '').trim() === sig.fieldInstanceId,
      );
      if (!field)
        continue;

      const pageIndex = (field.pageNumber || 1) - 1;
      const targetPage = pages[pageIndex];
      if (!targetPage)
        continue;

      const { width: pageWidth, height: pageHeight } = targetPage.getSize();

      let x: number, y: number, w: number, h: number;
      if (field.normalizedX !== undefined) {
        x = field.normalizedX * pageWidth;
        y = field.normalizedY * pageHeight;
        w = field.normalizedWidth * pageWidth;
        h = field.normalizedHeight * pageHeight;
      }
      else {
        x = field.x || 0;
        y = field.y || 0;
        w = field.width || 150;
        h = field.height || 60;
      }

      const base64Data = sig.dataUrl.replace(/^data:image\/\w+;base64,/, '');
      const sigBytes = Uint8Array.from(atob(base64Data), c => c.charCodeAt(0));

      let sigImage: any;
      try {
        sigImage = sig.dataUrl.startsWith('data:image/png')
          ? await pdfDoc.embedPng(sigBytes)
          : await pdfDoc.embedJpg(sigBytes);
      }
      catch {
        try {
          sigImage = await pdfDoc.embedPng(sigBytes);
        }
        catch { continue; }
      }

      targetPage.drawImage(sigImage, {
        x,
        y: pageHeight - y - h,
        width: w,
        height: h,
        opacity: 1,
      });
    }

    const finalBytes = await pdfDoc.save();
    return { success: true, bytes: finalBytes };
  }
  catch (err) {
    console.error('Failed to re-embed previous signatures:', err);
    // Fall back to returning the field-values-only PDF rather than blocking the flow
    return { success: true, bytes: filledPdfBytes };
  }
}

function parsePositiveInteger(value: unknown): number | null {
  const parsed = Number.parseInt(String(value ?? ''), 10);
  if (!Number.isFinite(parsed) || parsed <= 0) {
    return null;
  }
  return parsed;
}

function getFieldValueStorageKey(fieldId: number, fieldInstanceId?: string): string {
  const normalizedInstanceId = String(fieldInstanceId ?? '').trim();
  if (normalizedInstanceId.length > 0) {
    return `${fieldId}::${normalizedInstanceId}`;
  }
  return String(fieldId);
}

function getStoredFieldValue(fieldValuesMap: Map<string, string>, field: any): string {
  const fieldId = Number.parseInt(String(field?.id ?? ''), 10);
  if (!Number.isFinite(fieldId) || fieldId <= 0) {
    return '';
  }

  const instanceId = String(field?.instanceId ?? '').trim();
  if (instanceId.length > 0) {
    const byInstance = fieldValuesMap.get(getFieldValueStorageKey(fieldId, instanceId));
    if (typeof byInstance === 'string') {
      return byInstance;
    }
  }

  return fieldValuesMap.get(getFieldValueStorageKey(fieldId)) ?? '';
}

function getFieldType(field: any): string {
  return String(field?.type ?? field?.fieldType ?? '').trim().toLowerCase();
}

function normalizeCheckboxValue(value: unknown): string {
  const normalized = String(value ?? '').trim().toLowerCase();
  return ['true', '1', 'yes', 'y', 'checked', 'on'].includes(normalized) ? 'true' : '';
}

function isCheckboxField(field: any): boolean {
  const fieldType = getFieldType(field);
  const fieldName = String(field?.name ?? '').trim().toLowerCase();
  return fieldType === 'checkbox' || fieldName === 'check mark';
}

function isStrikeThroughGroupField(field: any): boolean {
  if (!isCheckboxField(field)) {
    return false;
  }

  if (Object.prototype.hasOwnProperty.call(field || {}, 'strikeThroughGroupMode')) {
    return field?.strikeThroughGroupMode === true;
  }

  return field?.strike_through_group_mode === true;
}

function getStrikeLineThickness(field: any): number {
  const parsed = Number.parseFloat(String(field?.strikeLineThickness ?? field?.strike_line_thickness ?? 1.5));
  if (!Number.isFinite(parsed) || parsed <= 0) {
    return 1.5;
  }
  return Math.min(8, Math.max(0.5, parsed));
}

function getVisibilityRule(field: any) {
  const rawRule = field?.visibilityRule ?? field?.visibility_rule;
  if (!rawRule || typeof rawRule !== 'object') {
    return null;
  }

  const sourceFieldInstanceId = String(rawRule.sourceFieldInstanceId ?? rawRule.source_field_instance_id ?? '').trim();
  const sourceGroupId = String(rawRule.sourceGroupId ?? rawRule.source_group_id ?? '').trim();
  if (!sourceFieldInstanceId.length && !sourceGroupId.length) {
    return null;
  }

  return {
    enabled: rawRule.enabled !== false,
    sourceFieldInstanceId: sourceFieldInstanceId || null,
    sourceGroupId: sourceGroupId || null,
    operator: rawRule.operator === 'isUnchecked' ? 'isUnchecked' : 'isChecked',
  };
}

function isDateOrTimeField(field: any): boolean {
  const fieldType = getFieldType(field);
  return fieldType === 'date' || fieldType === 'time';
}

function isAutoGeneratedDateOrTimeField(field: any): boolean {
  const fieldType = getFieldType(field);
  if (fieldType === 'time') {
    return true;
  }
  if (fieldType !== 'date') {
    return false;
  }

  return field?.isAutoGenerate === true || field?.isAutoGenerated === true || field?.is_auto_generated === true;
}

function applyFieldCharacterLimit(value: unknown, field: any): string {
  const normalizedValue = String(value ?? '');
  if (isDateOrTimeField(field)) {
    return normalizedValue;
  }
  const maxLength = parsePositiveInteger(field?.maxLength ?? field?.max_length);
  if (!maxLength) {
    return normalizedValue;
  }
  if (normalizedValue.length <= maxLength) {
    return normalizedValue;
  }
  return normalizedValue.slice(0, maxLength);
}

async function generateFilledPdf(pdfBytes: Uint8Array, fields: any[], _template: any) {
  try {
    const PDFLib = await import('pdf-lib');
    const fontkitModule = await import('@pdf-lib/fontkit');
    const fontkit = (fontkitModule as any).default ?? fontkitModule;

    const pdfDoc = await PDFLib.PDFDocument.load(pdfBytes);
    pdfDoc.registerFontkit(fontkit);

    const pages = pdfDoc.getPages();
    const CSS_PX_TO_PT = 72 / 96;
    const embeddedFontCache = new Map<string, any>();

    function getSarabunVariantFileName(bold: boolean, italic: boolean): string {
      if (bold && italic)
        return 'Sarabun-BoldItalic.ttf';
      if (bold)
        return 'Sarabun-Bold.ttf';
      if (italic)
        return 'Sarabun-Italic.ttf';
      return 'Sarabun-Regular.ttf';
    }

    async function getFont(fontFamily: string, bold: boolean, italic: boolean) {
      const normalizedFamily = String(fontFamily || 'Sarabun').trim().toLowerCase() || 'sarabun';
      const cacheKey = `${normalizedFamily}|${bold}|${italic}`;
      if (embeddedFontCache.has(cacheKey)) {
        return embeddedFontCache.get(cacheKey);
      }

      let font: any;
      try {
        const fontPath = join(process.cwd(), 'public', 'fonts', getSarabunVariantFileName(bold, italic));
        const fontBytes = new Uint8Array(await readFile(fontPath));
        font = await pdfDoc.embedFont(fontBytes, { subset: true });
      }
      catch (variantError) {
        try {
          const fallbackPath = join(process.cwd(), 'public', 'fonts', 'Sarabun-Regular.ttf');
          const fallbackBytes = new Uint8Array(await readFile(fallbackPath));
          font = await pdfDoc.embedFont(fallbackBytes, { subset: true });
        }
        catch (fallbackError) {
          console.warn('Failed to load local Sarabun font variant:', variantError);
          console.warn('Failed to load fallback Sarabun-Regular font:', fallbackError);
          font = await pdfDoc.embedFont(PDFLib.StandardFonts.Helvetica);
        }
      }

      embeddedFontCache.set(cacheKey, font);
      return font;
    }

    function drawCheckboxTick(targetPage: any, fieldX: number, fieldYBottom: number, fieldW: number, fieldH: number) {
      const iconSide = Math.max(8, Math.min(fieldW, fieldH) * 0.78);
      const iconX = fieldX + ((fieldW - iconSide) / 2);
      const iconY = fieldYBottom + ((fieldH - iconSide) / 2);
      const strokeWidth = Math.max(1.2, Math.min(3.5, iconSide * 0.12));

      const start = {
        x: iconX + (iconSide * 0.18),
        y: iconY + (iconSide * 0.52),
      };
      const mid = {
        x: iconX + (iconSide * 0.40),
        y: iconY + (iconSide * 0.30),
      };
      const end = {
        x: iconX + (iconSide * 0.82),
        y: iconY + (iconSide * 0.76),
      };

      targetPage.drawLine({
        start,
        end: mid,
        thickness: strokeWidth,
        color: PDFLib.rgb(0, 0, 0),
      });

      targetPage.drawLine({
        start: mid,
        end,
        thickness: strokeWidth,
        color: PDFLib.rgb(0, 0, 0),
      });
    }

    function drawUncheckedStrikeLine(targetPage: any, fieldX: number, fieldYBottom: number, fieldW: number, fieldH: number, field: any) {
      const lineY = fieldYBottom + (fieldH / 2);
      targetPage.drawLine({
        start: { x: fieldX, y: lineY },
        end: { x: fieldX + fieldW, y: lineY },
        thickness: getStrikeLineThickness(field),
        color: PDFLib.rgb(0, 0, 0),
      });
    }

    function hasCheckedCheckboxInGroupForRender(groupId: string): boolean {
      const normalizedGroupId = String(groupId ?? '').trim();
      if (!normalizedGroupId) {
        return false;
      }

      return fields.some((candidate) => {
        if (!isCheckboxField(candidate) || String(candidate?.groupId ?? '').trim() !== normalizedGroupId) {
          return false;
        }
        const candidateValue = applyFieldCharacterLimit(candidate?.value ?? '', candidate);
        return normalizeCheckboxValue(candidateValue) === 'true';
      });
    }

    for (const field of fields) {
      const normalizedFieldValue = applyFieldCharacterLimit(field.value, field);
      const isCheckbox = isCheckboxField(field);
      const isCheckboxChecked = isCheckbox && normalizeCheckboxValue(normalizedFieldValue) === 'true';
      const groupId = String(field?.groupId ?? '').trim();
      const shouldDrawStrikeLine = isStrikeThroughGroupField(field)
        && groupId.length > 0
        && hasCheckedCheckboxInGroupForRender(groupId)
        && !isCheckboxChecked;
      if (!normalizedFieldValue.trim() && !shouldDrawStrikeLine)
        continue;

      try {
        const pageIndex = (field.pageNumber || 1) - 1;
        const targetPage = pages[pageIndex];

        if (!targetPage)
          continue;

        const { width: pageWidth, height: pageHeight } = targetPage.getSize();

        let fieldX: number;
        let fieldYTop: number;
        let fieldW: number;
        let fieldH: number;

        if (field.normalizedX !== undefined) {
          fieldX = field.normalizedX * pageWidth;
          fieldYTop = field.normalizedY * pageHeight;
          fieldW = field.normalizedWidth * pageWidth;
          fieldH = field.normalizedHeight * pageHeight;
        }
        else {
          fieldX = field.x || 0;
          fieldYTop = field.y || 0;
          fieldW = field.width || 100;
          fieldH = field.height || 30;
        }

        const fieldYBottom = pageHeight - fieldYTop - fieldH;

        if (isCheckbox && shouldDrawStrikeLine) {
          drawUncheckedStrikeLine(targetPage, fieldX, fieldYBottom, fieldW, fieldH, field);
          continue;
        }

        if (isCheckbox && isStrikeThroughGroupField(field)) {
          continue;
        }

        if (isCheckbox) {
          drawCheckboxTick(targetPage, fieldX, fieldYBottom, fieldW, fieldH);
          continue;
        }

        const isBold = String(field.fontWeight || '').toLowerCase() === 'bold';
        const isItalic = String(field.fontStyle || '').toLowerCase() === 'italic';
        const font = await getFont(field.fontFamily || field.font || 'Sarabun', isBold, isItalic);

        const requestedFontSizePx = Number(field.fontSize || 12);
        const fontSize = Math.max(4, Math.min(requestedFontSizePx * CSS_PX_TO_PT, fieldH * 0.9));

        let textY = fieldYBottom + fieldH - fontSize;
        try {
          const ascenderHeight = Number(font.heightAtSize(fontSize, { descender: false }));
          if (ascenderHeight > 0) {
            textY = fieldYBottom + fieldH - ascenderHeight - (fontSize * 0.1);
          }
        }
        catch {}

        let text = normalizedFieldValue.trim();

        const lines: string[] = [];
        const paragraphs = text.split('\n');
        for (const paragraph of paragraphs) {
          const words = paragraph.split(/(\s+)/);
          let currentLine = '';
          for (const word of words) {
            if (word.trim() === '') {
              currentLine += word;
              continue;
            }
            try {
              const testWidth = font.widthOfTextAtSize(currentLine + word, fontSize);
              if (testWidth > fieldW && currentLine !== '') {
                lines.push(currentLine);
                currentLine = word;
              }
              else if (testWidth > fieldW && currentLine === '') {
                let tempWord = '';
                for (const char of word) {
                  const charTestWidth = font.widthOfTextAtSize(tempWord + char, fontSize);
                  if (charTestWidth > fieldW && tempWord !== '') {
                    lines.push(tempWord);
                    tempWord = char;
                  }
                  else {
                    tempWord += char;
                  }
                }
                currentLine = tempWord;
              }
              else {
                currentLine += word;
              }
            }
            catch {
              currentLine += word;
            }
          }
          if (currentLine) {
            lines.push(currentLine);
          }
        }
        text = lines.join('\n');

        let textX = fieldX;

        if (field.textAlign === 'center' || field.textAlign === 'right') {
          try {
            const spacing = Number(field.letterSpacing ?? 0) || 0;
            const spacingExtra = spacing !== 0 ? Math.max(0, text.length - 1) * spacing * CSS_PX_TO_PT : 0;
            const textW = font.widthOfTextAtSize(text.split('\n')[0], fontSize) + spacingExtra;
            textX = field.textAlign === 'center'
              ? fieldX + (fieldW - textW) / 2
              : fieldX + fieldW - textW;
          }
          catch { /* keep left */ }
        }

        textX = Math.max(fieldX, textX);

        const letterSpacing = (Number(field.letterSpacing ?? 0) || 0) * CSS_PX_TO_PT;

        if (letterSpacing !== 0 && text.length > 0) {
          let cursorX = textX;
          for (const char of text) {
            if (char === '\n') {
              textY -= (Number(field.lineHeight) || 1.5) * fontSize;
              cursorX = textX;
              continue;
            }
            if (cursorX >= fieldX + fieldW) {
              textY -= (Number(field.lineHeight) || 1.5) * fontSize;
              cursorX = textX;
            }
            targetPage.drawText(char, {
              x: cursorX,
              y: textY,
              size: fontSize,
              font,
              color: PDFLib.rgb(0, 0, 0),
            });
            try {
              cursorX += font.widthOfTextAtSize(char, fontSize) + letterSpacing;
            }
            catch {
              cursorX += fontSize * 0.6 + letterSpacing;
            }
          }
        }
        else {
          const customLineHeight = (Number(field.lineHeight) || 1.5) * fontSize;
          targetPage.drawText(text, {
            x: textX,
            y: textY,
            size: fontSize,
            font,
            color: PDFLib.rgb(0, 0, 0),
            maxWidth: fieldW,
            lineHeight: customLineHeight,
          });
        }
      }
      catch (error) {
        console.error('Error processing field:', field, error);
      }
    }

    const filledPdfBytes = await pdfDoc.save();
    return filledPdfBytes;
  }
  catch (error) {
    console.error('Error in generateFilledPdf:', error);
    return null;
  }
}
